-- Music Match v5: uitsluitend vaste originele soundtracktracks (songs 1-100)
-- Uitvoeren in Supabase SQL Editor. Veilig opnieuw uitvoerbaar.

begin;

with exact_songs (song_number, label, title, film, year, artist, spotify_url, enabled) as (
  values
  (1, 'Song 001', 'Let It Go', 'Frozen', 2013, 'Idina Menzel', 'https://open.spotify.com/track/0glJ7u9DUVB8y47FHSDXNI', true),
  (2, 'Song 002', 'Do You Want to Build a Snowman?', 'Frozen', 2013, 'Kristen Bell, Agatha Lee Monn, Katie Lopez', 'https://open.spotify.com/track/6OMgkUElawaacpfN9rvlpr', true),
  (3, 'Song 003', 'For the First Time in Forever', 'Frozen', 2013, 'Kristen Bell, Idina Menzel', 'https://open.spotify.com/track/3kmcY7TZIY2rsRid66cy2a', true),
  (4, 'Song 004', 'Love Is an Open Door', 'Frozen', 2013, 'Kristen Bell, Santino Fontana', 'https://open.spotify.com/track/7ytvapRZjOvWmYa4GouK11', true),
  (5, 'Song 005', 'Into the Unknown', 'Frozen II', 2019, 'Idina Menzel, AURORA', 'https://open.spotify.com/track/3Z0oQ8r78OUaHvGPiDBR3W', true),
  (6, 'Song 006', 'Show Yourself', 'Frozen II', 2019, 'Idina Menzel, Evan Rachel Wood', 'https://open.spotify.com/track/50WeOnXhM1H7AZEeIDoWfZ', true),
  (7, 'Song 007', 'Some Things Never Change', 'Frozen II', 2019, 'Kristen Bell, Idina Menzel, Josh Gad, Jonathan Groff, Cast of Frozen 2', 'https://open.spotify.com/track/4Xbotg4PCLJw9cDx2dtZLK', true),
  (8, 'Song 008', 'Lost in the Woods', 'Frozen II', 2019, 'Jonathan Groff', 'https://open.spotify.com/track/7namdlOhbtsc8FvoSafOQt', true),
  (9, 'Song 009', 'Hakuna Matata', 'The Lion King', 1994, 'Nathan Lane, Ernie Sabella, Jason Weaver, Joseph Williams', 'https://open.spotify.com/track/7AFEEaP4T9jORisZ0BL9HQ', true),
  (10, 'Song 010', 'Circle of Life', 'The Lion King', 1994, 'Carmen Twillie, Lebo M.', 'https://open.spotify.com/track/1HJqf1qlNs02vzM3NKe8PQ', true),
  (11, 'Song 011', 'I Just Can''t Wait to Be King', 'The Lion King', 1994, 'Jason Weaver, Rowan Atkinson, Laura Williams', 'https://open.spotify.com/track/2RSsWDVXWSUVNRW2DEx0PK', true),
  (12, 'Song 012', 'Can You Feel the Love Tonight', 'The Lion King', 1994, 'Joseph Williams, Sally Dworsky, Nathan Lane, Ernie Sabella, Kristle Edwards', 'https://open.spotify.com/track/4yKNMqJvLWAoZAvIISNeCu', true),
  (13, 'Song 013', 'Be Prepared', 'The Lion King', 1994, 'Jeremy Irons, Whoopi Goldberg, Cheech Marin, Jim Cummings', 'https://open.spotify.com/track/7HMJUdGZaJ42D8ghtuZyI5', true),
  (14, 'Song 014', 'He Lives in You', 'The Lion King II: Simba''s Pride', 1998, 'Lebo M.', 'https://open.spotify.com/track/2ahrqdsWQEbDkZqE7nwbaT', true),
  (15, 'Song 015', 'A Whole New World', 'Aladdin', 1992, 'Lea Salonga, Brad Kane', 'https://open.spotify.com/track/1zHQ1JyEOnjnWFFaNVNQ9y', true),
  (16, 'Song 016', 'Friend Like Me', 'Aladdin', 1992, 'Robin Williams', 'https://open.spotify.com/track/6iPy2jaqzxXa8SpHQkiDCZ', true),
  (17, 'Song 017', 'Prince Ali', 'Aladdin', 1992, 'Robin Williams', 'https://open.spotify.com/track/7EUzqaEPOyn8qc0jDioveR', true),
  (18, 'Song 018', 'Arabian Nights', 'Aladdin', 1992, 'Bruce Adler', 'https://open.spotify.com/track/6gVp1rjtB3cFa8aTpuMjxw', true),
  (19, 'Song 019', 'One Jump Ahead', 'Aladdin', 1992, 'Brad Kane', 'https://open.spotify.com/track/1bYr31moIqTVRfcWMbAt0H', true),
  (20, 'Song 020', 'Part of Your World', 'The Little Mermaid', 1989, 'Jodi Benson', 'https://open.spotify.com/track/4kRBST99wHY6ZGXwdmUC5h', true),
  (21, 'Song 021', 'Under the Sea', 'The Little Mermaid', 1989, 'Samuel E. Wright', 'https://open.spotify.com/track/0m2ZeItBjdQ2sfPa6MxtlU', true),
  (22, 'Song 022', 'Kiss the Girl', 'The Little Mermaid', 1989, 'Samuel E. Wright', 'https://open.spotify.com/track/1zpjPQJW5lwPuwsMSIN52Q', true),
  (23, 'Song 023', 'Poor Unfortunate Souls', 'The Little Mermaid', 1989, 'Pat Carroll', 'https://open.spotify.com/track/3gcwl72tizQiWT07Oui0RD', true),
  (24, 'Song 024', 'Fathoms Below', 'The Little Mermaid', 1989, 'Ship''s Chorus', 'https://open.spotify.com/track/3cjVVHKtm6fEreZGPnlqBc', true),
  (25, 'Song 025', 'How Far I''ll Go', 'Moana', 2016, 'Auli''i Cravalho', 'https://open.spotify.com/track/5WPh0pzmmVg2USYCiRWxBR', true),
  (26, 'Song 026', 'You''re Welcome', 'Moana', 2016, 'Dwayne Johnson', 'https://open.spotify.com/track/3w5PE9CQbhOq8JsDp4aspt', true),
  (27, 'Song 027', 'Shiny', 'Moana', 2016, 'Jemaine Clement', 'https://open.spotify.com/track/5XprWL9Jr3dJQcQUcbniWf', true),
  (28, 'Song 028', 'Where You Are', 'Moana', 2016, 'Christopher Jackson, Rachel House, Nicole Scherzinger, Auli''i Cravalho, Louise Bush', 'https://open.spotify.com/track/7uZzghGGS1XvvUroz5rDqh', true),
  (29, 'Song 029', 'We Know the Way', 'Moana', 2016, 'Opetaia Foa''i, Lin-Manuel Miranda', 'https://open.spotify.com/track/1EOEVA3HK3lcPyfvRq9tYN', true),
  (30, 'Song 030', 'We Don''t Talk About Bruno', 'Encanto', 2021, 'Carolina Gaitán, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz, Encanto Cast', 'https://open.spotify.com/track/52xJxFP6TqMuO4Yt0eOkMz', true),
  (31, 'Song 031', 'Surface Pressure', 'Encanto', 2021, 'Jessica Darrow', 'https://open.spotify.com/track/760jhRscwGbIIe1m1IIQpU', true),
  (32, 'Song 032', 'The Family Madrigal', 'Encanto', 2021, 'Stephanie Beatriz, Olga Merediz, Encanto Cast', 'https://open.spotify.com/track/4b1yxSdlumA8N4fEk4UOZp', true),
  (33, 'Song 033', 'What Else Can I Do?', 'Encanto', 2021, 'Diane Guerrero, Stephanie Beatriz', 'https://open.spotify.com/track/3XoYqtiWHhsk59frZupImG', true),
  (34, 'Song 034', 'Waiting on a Miracle', 'Encanto', 2021, 'Stephanie Beatriz', 'https://open.spotify.com/track/3oRW9ZGPRbLRMneQ5lwflt', true),
  (35, 'Song 035', 'All of You', 'Encanto', 2021, 'Stephanie Beatriz, Olga Merediz, John Leguizamo, Adassa, Maluma, Encanto Cast', 'https://open.spotify.com/track/4X25mFLehFnxa1TwtLKcE2', true),
  (36, 'Song 036', 'Remember Me', 'Coco', 2017, 'Benjamin Bratt', 'https://open.spotify.com/track/6gF8tPWPRoPt2j4SZWOUXC', true),
  (37, 'Song 037', 'Un Poco Loco', 'Coco', 2017, 'Anthony Gonzalez, Gael García Bernal', 'https://open.spotify.com/track/0inaxid9CcJYsu9CdF0s4m', true),
  (38, 'Song 038', 'The World Es Mi Familia', 'Coco', 2017, 'Anthony Gonzalez, Antonio Sol', 'https://open.spotify.com/track/0TbQ1pDJpSEfRn6pa791Ls', true),
  (39, 'Song 039', 'Proud Corazón', 'Coco', 2017, 'Anthony Gonzalez', 'https://open.spotify.com/track/4xUzgBNEzJCVerZZLwRRSH', true),
  (40, 'Song 040', 'You''ve Got a Friend in Me', 'Toy Story', 1995, 'Randy Newman', 'https://open.spotify.com/track/1i2JdlGZCs1svvMedNHQfZ', true),
  (41, 'Song 041', 'When She Loved Me', 'Toy Story 2', 1999, 'Sarah McLachlan', 'https://open.spotify.com/track/0ppN8ns8UX79H14RyUatRc', true),
  (42, 'Song 042', 'We Belong Together', 'Toy Story 3', 2010, 'Randy Newman', 'https://open.spotify.com/track/2m1mYan1nvOMORlb12q2Y9', true),
  (43, 'Song 043', 'I See the Light', 'Tangled', 2010, 'Mandy Moore, Zachary Levi', 'https://open.spotify.com/track/6klpXs2uAjagnZMFkt4qkl', true),
  (44, 'Song 044', 'When Will My Life Begin?', 'Tangled', 2010, 'Mandy Moore', 'https://open.spotify.com/track/03xWMkKEbeO4SnylA53ipj', true),
  (45, 'Song 045', 'Mother Knows Best', 'Tangled', 2010, 'Donna Murphy', 'https://open.spotify.com/track/1lOSxJNCLvWm2bYaTcTSmK', true),
  (46, 'Song 046', 'I''ve Got a Dream', 'Tangled', 2010, 'Mandy Moore, Brad Garrett, Ensemble - Tangled, Zachary Levi, Jeffrey Tambor', 'https://open.spotify.com/track/0TCt7OFRdD8PQ6vTRQxNgQ', true),
  (47, 'Song 047', 'Be Our Guest', 'Beauty and the Beast', 1991, 'Angela Lansbury, Jerry Orbach, Chorus - Beauty and the Beast', 'https://open.spotify.com/track/0hWTIrbmyuAGwQYXGQOVH0', true),
  (48, 'Song 048', 'Beauty and the Beast', 'Beauty and the Beast', 1991, 'Angela Lansbury', 'https://open.spotify.com/track/2xS0Aybg4e8cQ8xiv3DeoH', true),
  (49, 'Song 049', 'Belle', 'Beauty and the Beast', 1991, 'Richard White, Paige O''Hara, Chorus - Beauty and the Beast', 'https://open.spotify.com/track/4FrfQdZaZnudSHPwgliazB', true),
  (50, 'Song 050', 'Gaston', 'Beauty and the Beast', 1991, 'Richard White, Jesse Corti, Chorus - Beauty and the Beast', 'https://open.spotify.com/track/64lQ4g5QiFNDC7gTUCe3DY', true),
  (51, 'Song 051', 'Something There', 'Beauty and the Beast', 1991, 'Robby Benson, Jerry Orbach, Paige O''Hara, Angela Lansbury, David Ogden Stiers', 'https://open.spotify.com/track/5S3vVcKLO8p5TH58448T48', true),
  (52, 'Song 052', 'I''ll Make a Man Out of You', 'Mulan', 1998, 'Donny Osmond & Chorus - Mulan', 'https://open.spotify.com/track/40lNlmrek40tfBOiQzf6qK', true),
  (53, 'Song 053', 'Reflection', 'Mulan', 1998, 'Lea Salonga', 'https://open.spotify.com/track/2AILbz83cBnrAMAG06rZts', true),
  (54, 'Song 054', 'Honor to Us All', 'Mulan', 1998, 'Lea Salonga, Beth Fowler, Marni Nixon & Chorus - Mulan', 'https://open.spotify.com/track/78EMhiyAcalWWtnpk20Eoo', true),
  (55, 'Song 055', 'A Girl Worth Fighting For', 'Mulan', 1998, 'Lea Salonga, Harvey Fierstein, Matthew Wilder, James Hong, Jerry Tondo', 'https://open.spotify.com/track/3wjgPeXocinhLyPL37p70e', true),
  (56, 'Song 056', 'Go the Distance', 'Hercules', 1997, 'Roger Bart', 'https://open.spotify.com/track/0D1OY0M5A0qD5HGBvFmFid', true),
  (57, 'Song 057', 'Zero to Hero', 'Hercules', 1997, 'Chorus - Hercules, Lillias White, Cheryl Freeman, LaChanze, Roz Ryan, Vaneese Thomas, Tawatha Agee', 'https://open.spotify.com/track/4zDfgax6Ihb0UWdour1ZEs', true),
  (58, 'Song 058', 'I Won''t Say (I''m in Love)', 'Hercules', 1997, 'Susan Egan, Cheryl Freeman, LaChanze, Vaneese Thomas, Lillias White, Roz Ryan', 'https://open.spotify.com/track/0PKmDncVOiNQLO6D1P6PXi', true),
  (59, 'Song 059', 'The Gospel Truth', 'Hercules', 1997, 'Cheryl Freeman, LaChanze, Vaneese Thomas, Lillias White, Roz Ryan', 'https://open.spotify.com/track/6uW03WHG3qv2FzxPIW6SUP', true),
  (60, 'Song 060', 'Colors of the Wind', 'Pocahontas', 1995, 'Judy Kuhn', 'https://open.spotify.com/track/1O841LULHXexH8W7fqtctA', true),
  (61, 'Song 061', 'Just Around the Riverbend', 'Pocahontas', 1995, 'Judy Kuhn', 'https://open.spotify.com/track/3SZXvtZabmTK2oRmdSjfBO', true),
  (62, 'Song 062', 'Savages', 'Pocahontas', 1995, 'Chorus - Pocahontas, David Ogden Stiers, Jim Cummings, Judy Kuhn', 'https://open.spotify.com/track/5KLCfUQh7sgWek4C0lbmvs', true),
  (63, 'Song 063', 'Almost There', 'The Princess and the Frog', 2009, 'Anika Noni Rose', 'https://open.spotify.com/track/2GLyruWagsv8o7aGNXboH1', true),
  (64, 'Song 064', 'Friends on the Other Side', 'The Princess and the Frog', 2009, 'Keith David', 'https://open.spotify.com/track/14mNTV7rsvzkVfBmRepX1X', true),
  (65, 'Song 065', 'Dig a Little Deeper', 'The Princess and the Frog', 2009, 'Jenifer Lewis, The Pinnacle Gospel Choir', 'https://open.spotify.com/track/7kh64k3P9Fk4EsA6vOdwmj', true),
  (66, 'Song 066', 'Down in New Orleans', 'The Princess and the Frog', 2009, 'Dr. John', 'https://open.spotify.com/track/4tCdoXt7EiwZZhMevxmY8u', true),
  (67, 'Song 067', 'The Bare Necessities', 'The Jungle Book', 1967, 'Phil Harris, Bruce Reitherman', 'https://open.spotify.com/track/0fzcz7acLp523Dyrd43Sm3', true),
  (68, 'Song 068', 'I Wan''na Be Like You', 'The Jungle Book', 1967, 'Louis Prima, Phil Harris, Bruce Reitherman', 'https://open.spotify.com/track/517vxmOFgKFJvuucKuUdar', true),
  (69, 'Song 069', 'Trust in Me', 'The Jungle Book', 1967, 'Sterling Holloway', 'https://open.spotify.com/track/4wgaxfyAPwib9born5r5NT', true),
  (70, 'Song 070', 'Ev''rybody Wants to Be a Cat', 'The Aristocats', 1970, 'Scatman Crothers, Phil Harris, Thurl Ravenscroft, Liz English', 'https://open.spotify.com/track/3uZIfWx5ridUBQevmgHDUt', true),
  (71, 'Song 071', 'Thomas O''Malley Cat', 'The Aristocats', 1970, 'Phil Harris', 'https://open.spotify.com/track/2Kf7dwNBp8pUNE8iOpg5oT', true),
  (72, 'Song 072', 'Cruella De Vil', 'One Hundred and One Dalmatians', 1961, 'Bill Lee', 'https://open.spotify.com/track/4VF8YWqMsY3Y1UcKJBg5XO', true),
  (73, 'Song 073', 'When You Wish Upon a Star', 'Pinocchio', 1940, 'Cliff Edwards, Disney Studio Chorus', 'https://open.spotify.com/track/60B62YnQ30umayqPNjZIEe', true),
  (74, 'Song 074', 'I''ve Got No Strings', 'Pinocchio', 1940, 'Dickie Jones', 'https://open.spotify.com/track/0Gn3KmW9A4YfJH1fc3aR44', true),
  (75, 'Song 075', 'Heigh-Ho', 'Snow White and the Seven Dwarfs', 1937, 'The Dwarf Chorus', 'https://open.spotify.com/track/7sYaJXMEvq3q91jJNm8I7I', true),
  (76, 'Song 076', 'Someday My Prince Will Come', 'Snow White and the Seven Dwarfs', 1937, 'Adriana Caselotti', 'https://open.spotify.com/track/0UzrSV4nUqkYUUTyhjRf7Z', true),
  (77, 'Song 077', 'Whistle While You Work', 'Snow White and the Seven Dwarfs', 1937, 'Adriana Caselotti', 'https://open.spotify.com/track/6SuebnXnUXBtgtqH871UtF', true),
  (78, 'Song 078', 'A Dream Is a Wish Your Heart Makes', 'Cinderella', 1950, 'Ilene Woods, Cinderella''s Mice Chorus', 'https://open.spotify.com/track/4lQqPnkYEUfVaV1i4K5bLI', true),
  (79, 'Song 079', 'Bibbidi-Bobbidi-Boo', 'Cinderella', 1950, 'Verna Felton', 'https://open.spotify.com/track/7HBGPzKSFqxaArcNRVN6m5', true),
  (80, 'Song 080', 'Once Upon a Dream', 'Sleeping Beauty', 1959, 'Mary Costa, Bill Shirley, Chorus - Sleeping Beauty', 'https://open.spotify.com/track/6fMn04i0iZy3uCpJWqPMhr', true),
  (81, 'Song 081', 'The Siamese Cat Song', 'Lady and the Tramp', 1955, 'Si and Am, Peggy Lee', 'https://open.spotify.com/track/280NsxgRP7Km14FqzGpMQN', true),
  (82, 'Song 082', 'He''s a Tramp', 'Lady and the Tramp', 1955, 'Peggy Lee', 'https://open.spotify.com/track/3wVDE3ZEVzJIWhxwUVYgWd', true),
  (83, 'Song 083', 'Bella Notte', 'Lady and the Tramp', 1955, 'George Givot, Bill Thompson, Disney Studio Chorus', 'https://open.spotify.com/track/0YhEQcaLrrMSiDmNLvmgSs', true),
  (84, 'Song 084', 'The Wonderful Thing About Tiggers', 'The Many Adventures of Winnie the Pooh', 1977, 'Tigger', 'https://open.spotify.com/track/7tEPLrFXaPYmNcYsU85eHB', true),
  (85, 'Song 085', 'Winnie the Pooh', 'Winnie the Pooh and the Honey Tree', 1966, 'Disney Studio Chorus', 'https://open.spotify.com/track/1iy9VefoeBRoeKrfmPPzPc', true),
  (86, 'Song 086', 'Oo-De-Lally', 'Robin Hood', 1973, 'Roger Miller', 'https://open.spotify.com/track/5Asz9rHr2rViBdl6pkXpoq', true),
  (87, 'Song 087', 'Love', 'Robin Hood', 1973, 'Nancy Adams', 'https://open.spotify.com/track/0A3vD4ErvR6j3PakvY6EBC', true),
  (88, 'Song 088', 'Why Should I Worry?', 'Oliver & Company', 1988, 'Billy Joel', 'https://open.spotify.com/track/0wGh31bYM4IuRdJ7xTvgKN', true),
  (89, 'Song 089', 'Once Upon a Time in New York City', 'Oliver & Company', 1988, 'Huey Lewis', 'https://open.spotify.com/track/3GyU4gHxuhybQMVFBWwdzP', true),
  (90, 'Song 090', 'Best of Friends', 'The Fox and the Hound', 1981, 'Pearl Bailey', 'https://open.spotify.com/track/7ctiw2LWeIL68pJ58OC7AT', true),
  (91, 'Song 091', 'The Mob Song', 'Beauty and the Beast', 1991, 'Chorus - Beauty and the Beast & Richard White', 'https://open.spotify.com/track/5Us0yEljTVRRQoO7vuIuU9', true),
  (92, 'Song 092', 'One Jump Ahead (Reprise)', 'Aladdin', 1992, 'Brad Kane', 'https://open.spotify.com/track/3ISfJ9qfVh0IDwAgSbeQQf', true),
  (93, 'Song 093', 'Out There', 'The Hunchback of Notre Dame', 1996, 'Tony Jay, Tom Hulce', 'https://open.spotify.com/track/7cX2nwvVfWW3bfScg2f15K', true),
  (94, 'Song 094', 'Heaven''s Light/Hellfire', 'The Hunchback of Notre Dame', 1996, 'Tony Jay, Tom Hulce, Chorus - The Hunchback of Notre Dame', 'https://open.spotify.com/track/4rp9YObc6Q5xc6X1S8c7m9', true),
  (95, 'Song 095', 'The Bells of Notre Dame', 'The Hunchback of Notre Dame', 1996, 'David Ogden Stiers, Tony Jay, Paul Kandel, Chorus - The Hunchback of Notre Dame', 'https://open.spotify.com/track/47Wo2LeGbzdZTdEFNRZXV0', true),
  (96, 'Song 096', 'Strangers Like Me', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/3T74kgnbHw8JqkYGJKD4Tl', true),
  (97, 'Song 097', 'You''ll Be in My Heart', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/4Y8vb1uy9IjM2V1hqvrAid', true),
  (98, 'Song 098', 'Son of Man', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/1LhFadk0aWYczltTjIbFlI', true),
  (99, 'Song 099', 'Two Worlds', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/3icOFPIciIN8FQSyVlpYSF', true),
  (100, 'Song 100', 'Try Everything', 'Zootopia', 2016, 'Shakira', 'https://open.spotify.com/track/1N3dZ7TTWO6VcD4Y3hHYLZ', true)
)
update public.dmq_songs as target
set
  label = exact_songs.label,
  title = exact_songs.title,
  film = exact_songs.film,
  year = exact_songs.year,
  artist = exact_songs.artist,
  spotify_url = exact_songs.spotify_url,
  code_image_url = null,
  enabled = exact_songs.enabled,
  updated_at = now()
from exact_songs
where target.song_number = exact_songs.song_number;

commit;

select
  count(*) filter (where spotify_url like 'https://open.spotify.com/track/%') as exacte_tracks,
  count(*) filter (where spotify_url like 'https://open.spotify.com/search/%') as zoeklinks
from public.dmq_songs
where song_number between 1 and 100;
