-- Music Match v6: 300 originele Disney- en Pixar-soundtracktracks met vraagprofielen
-- Veilig opnieuw uitvoerbaar in Supabase SQL Editor.

begin;
alter table public.dmq_songs drop constraint if exists dmq_songs_song_number_check;
alter table public.dmq_songs add constraint dmq_songs_song_number_check check (song_number between 1 and 300);
alter table public.dmq_songs add column if not exists question_profile text not null default 'familiar';
alter table public.dmq_songs add column if not exists allowed_questions text[] not null default array['film','title','year','artist']::text[];
alter table public.dmq_songs drop constraint if exists dmq_songs_question_profile_check;
alter table public.dmq_songs add constraint dmq_songs_question_profile_check check (question_profile in ('iconic','familiar','deep','score'));

with new_songs (song_number,label,title,film,year,artist,spotify_url,enabled,question_profile,allowed_questions) as (
 values
  (151, 'Song 151', 'Chim Chim Cher-ee', 'Mary Poppins', 1964, 'Dick Van Dyke, Julie Andrews', 'https://open.spotify.com/track/23NtySnCSYOnjuhuLErsS5', true, 'familiar', array['film','title','year','artist']::text[]),
  (152, 'Song 152', 'Jolly Holiday', 'Mary Poppins', 1964, 'Dick Van Dyke, Julie Andrews', 'https://open.spotify.com/track/3sSpgPbDF16wncH7Zw4kqh', true, 'familiar', array['film','title','year','artist']::text[]),
  (153, 'Song 153', 'Let''s Get Together', 'The Parent Trap', 1961, 'Hayley Mills', 'https://open.spotify.com/track/6g3YUqir5Gngxn5lcA1wDL', true, 'deep', array['film','title','year','artist']::text[]),
  (154, 'Song 154', 'The Ugly Bug Ball', 'Summer Magic', 1963, 'Burl Ives', 'https://open.spotify.com/track/2CK9yTLAJEg6sLzLhn2LHY', true, 'deep', array['film','title','year','artist']::text[]),
  (155, 'Song 155', 'The Spectrum Song', 'An Adventure in Color', 1961, 'Paul Frees', 'https://open.spotify.com/track/6aMg4mBvBXotBg4zE6cJ4z', true, 'deep', array['film','title','year','artist']::text[]),
  (156, 'Song 156', 'Colonel Hathi''s March', 'The Jungle Book', 1967, 'J. Pat O''Malley', 'https://open.spotify.com/track/3VEV9UsGggVjjiworiuscR', true, 'familiar', array['film','title','year','artist']::text[]),
  (157, 'Song 157', 'A Whale of a Tale', '20,000 Leagues Under the Sea', 1954, 'Kirk Douglas', 'https://open.spotify.com/track/6ambk6KgfytRADHb0x8rx0', true, 'deep', array['film','title','year','artist']::text[]),
  (158, 'Song 158', 'You Can Fly! You Can Fly! You Can Fly!', 'Peter Pan', 1953, 'Bobby Driscoll, Kathryn Beaumont', 'https://open.spotify.com/track/7JD4aIrbFXH3eI7eqmIKhi', true, 'iconic', array['film','title','year','artist']::text[]),
  (159, 'Song 159', 'The Work Song', 'Cinderella', 1950, 'James MacDonald, The Mouse Chorus', 'https://open.spotify.com/track/38oDrV3xYjeivR8X10fFr1', true, 'familiar', array['film','title','year','artist']::text[]),
  (160, 'Song 160', 'Nutcracker Suite: Dance of the Reed Flutes', 'Fantasia', 1940, 'Pyotr Ilyich Tchaikovsky', 'https://open.spotify.com/track/6lvapUEO0jY0whLxFtXkNy', true, 'score', array['film','title','year']::text[]),
  (161, 'Song 161', 'Main Title (Love Is a Song)', 'Bambi', 1942, 'Donald Novis', 'https://open.spotify.com/track/6ZP66zQZjwN1P0QWR9fdSP', true, 'deep', array['film','title','year','artist']::text[]),
  (162, 'Song 162', 'Minnie''s Yoo Hoo', 'Mickey Mouse', 1929, 'Walt Disney, Carl Stalling', 'https://open.spotify.com/track/4Z5u4KsPcnTKPMcHzTbMTg', true, 'deep', array['film','title','year','artist']::text[]),
  (163, 'Song 163', 'Candle on the Water', 'Pete''s Dragon', 1977, 'Helen Reddy', 'https://open.spotify.com/track/74UZSX03wVCDrZoQQ0d2ZV', true, 'familiar', array['film','title','year','artist']::text[]),
  (164, 'Song 164', 'The Age of Not Believing', 'Bedknobs and Broomsticks', 1971, 'Angela Lansbury', 'https://open.spotify.com/track/1Afzcuo0XKgOiGS9sdq8ko', true, 'deep', array['film','title','year','artist']::text[]),
  (165, 'Song 165', 'Feed the Birds', 'Mary Poppins', 1964, 'Julie Andrews', 'https://open.spotify.com/track/4P73qgh9VA1S9Hct6VhLI4', true, 'iconic', array['film','title','year','artist']::text[]),
  (166, 'Song 166', 'Let''s Go Fly a Kite', 'Mary Poppins', 1964, 'David Tomlinson, Dick Van Dyke', 'https://open.spotify.com/track/3BHxMGVE3tN2dZsVU1l487', true, 'iconic', array['film','title','year','artist']::text[]),
  (167, 'Song 167', 'it''s a small world', 'Disneyland Park', 1964, 'Disneyland Children''s Chorus', 'https://open.spotify.com/track/5ouuPi1o6eOVSgHn2exemw', true, 'iconic', array['film','title','year','artist']::text[]),
  (168, 'Song 168', 'The Tiki, Tiki, Tiki Room', 'Disneyland Park', 1963, 'The Mellomen', 'https://open.spotify.com/track/0QQHnY4ZCg1m3NrmP5wI1B', true, 'familiar', array['film','title','year','artist']::text[]),
  (169, 'Song 169', 'Mickey Mouse March', 'The Mickey Mouse Club', 1955, 'Jimmie Dodd', 'https://open.spotify.com/track/1ejNfxKt0g11lIXsGsdZU0', true, 'iconic', array['film','title','year','artist']::text[]),
  (170, 'Song 170', 'The Second Star to the Right', 'Peter Pan', 1953, 'The Jud Conlon Chorus', 'https://open.spotify.com/track/2q1LwxkM3q9L96cPrykyzd', true, 'iconic', array['film','title','year','artist']::text[]),
  (171, 'Song 171', 'So This Is Love', 'Cinderella', 1950, 'Ilene Woods, Mike Douglas', 'https://open.spotify.com/track/1EwRMgWXS9U8Oet39tlYwY', true, 'iconic', array['film','title','year','artist']::text[]),
  (172, 'Song 172', 'Who''s Afraid of the Big Bad Wolf?', 'Three Little Pigs', 1933, 'Mary Moder, Dorothy Compton, Pinto Colvig', 'https://open.spotify.com/track/7e0SeoYblUCKeVHqFpKEt7', true, 'familiar', array['film','title','year','artist']::text[]),
  (173, 'Song 173', 'Family', 'James and the Giant Peach', 1996, 'James and the Giant Peach Cast', 'https://open.spotify.com/track/2AhzgGDcGC7jkimbYDN6Bc', true, 'deep', array['film','title','year','artist']::text[]),
  (174, 'Song 174', 'Les Poissons', 'The Little Mermaid', 1989, 'René Auberjonois', 'https://open.spotify.com/track/04LkB4linu702YDzlrQNDi', true, 'familiar', array['film','title','year','artist']::text[]),
  (175, 'Song 175', 'Mine, Mine, Mine', 'Pocahontas', 1995, 'David Ogden Stiers, Mel Gibson', 'https://open.spotify.com/track/41uJggpcL0qwQasVkKV50y', true, 'familiar', array['film','title','year','artist']::text[]),
  (176, 'Song 176', 'Jack''s Lament', 'The Nightmare Before Christmas', 1993, 'Danny Elfman', 'https://open.spotify.com/track/4VCexsNDyC2j8ZrY34RwV0', true, 'familiar', array['film','title','year','artist']::text[]),
  (177, 'Song 177', 'My Name Is James', 'James and the Giant Peach', 1996, 'Paul Terry', 'https://open.spotify.com/track/7EoLnnEPjNRWXdXrSxY4B5', true, 'deep', array['film','title','year','artist']::text[]),
  (178, 'Song 178', 'Heffalumps and Woozles', 'The Many Adventures of Winnie the Pooh', 1977, 'The Mellomen', 'https://open.spotify.com/track/2Nmmt8UIJATpJIdlmv4FrH', true, 'familiar', array['film','title','year','artist']::text[]),
  (179, 'Song 179', 'Portobello Road', 'Bedknobs and Broomsticks', 1971, 'David Tomlinson, Angela Lansbury', 'https://open.spotify.com/track/5IItAEDYGuoqvw6kRL7HO1', true, 'deep', array['film','title','year','artist']::text[]),
  (180, 'Song 180', 'Stay Awake', 'Mary Poppins', 1964, 'Julie Andrews', 'https://open.spotify.com/track/0DcxLrvPPkOQtytolEC5ZI', true, 'familiar', array['film','title','year','artist']::text[]),
  (181, 'Song 181', 'Following the Leader', 'Peter Pan', 1953, 'Bobby Driscoll, Paul Collins', 'https://open.spotify.com/track/5b4Z27O4GMxiqlHLZx8Pxb', true, 'familiar', array['film','title','year','artist']::text[]),
  (182, 'Song 182', 'The Ballad of Davy Crockett', 'Davy Crockett', 1955, 'The Wellingtons', 'https://open.spotify.com/track/5hDKXaqNk8QuwZoEIDAJU9', true, 'deep', array['film','title','year','artist']::text[]),
  (183, 'Song 183', 'Pink Elephants on Parade', 'Dumbo', 1941, 'The Sportsmen', 'https://open.spotify.com/track/06IWtDiU8D6DK8vSU072pa', true, 'familiar', array['film','title','year','artist']::text[]),
  (184, 'Song 184', 'Little April Shower', 'Bambi', 1942, 'Amy Lou Barnes, Sally Mueller', 'https://open.spotify.com/track/1ryI0iueOhVzXKSBO7ESxK', true, 'familiar', array['film','title','year','artist']::text[]),
  (185, 'Song 185', 'The Silly Song', 'Snow White and the Seven Dwarfs', 1937, 'The Dwarf Chorus', 'https://open.spotify.com/track/7qMriHg2jWHPQW9sdhLPZG', true, 'familiar', array['film','title','year','artist']::text[]),
  (186, 'Song 186', 'One Last Hope', 'Hercules', 1997, 'Danny DeVito', 'https://open.spotify.com/track/0Z06gAgsGv5hsLzvC06XMP', true, 'familiar', array['film','title','year','artist']::text[]),
  (187, 'Song 187', 'A Guy Like You', 'The Hunchback of Notre Dame', 1996, 'Jason Alexander, Charles Kimbrough, Mary Wickes', 'https://open.spotify.com/track/3BoaBZQsCU12IEEJeficPS', true, 'deep', array['film','title','year','artist']::text[]),
  (188, 'Song 188', 'On the Open Road', 'A Goofy Movie', 1995, 'Bill Farmer, Aaron Lohr', 'https://open.spotify.com/track/07XDfjpXYL8T0wOGMk81Xr', true, 'familiar', array['film','title','year','artist']::text[]),
  (189, 'Song 189', 'Fantasmic! Exit Music', 'Disneyland Park', 1992, 'Bruce Healey', 'https://open.spotify.com/track/0PZCJRizjjaygMsxthL0dr', true, 'score', array['film','title','year']::text[]),
  (190, 'Song 190', 'Oogie Boogie''s Song', 'The Nightmare Before Christmas', 1993, 'Ken Page, Ed Ivory', 'https://open.spotify.com/track/1TctVlWvNpmKGHMuPqJ5G2', true, 'iconic', array['film','title','year','artist']::text[]),
  (191, 'Song 191', 'I Will Go Sailing No More', 'Toy Story', 1995, 'Randy Newman', 'https://open.spotify.com/track/3oFSbVCS8conK9GwJWOSH6', true, 'familiar', array['film','title','year','artist']::text[]),
  (192, 'Song 192', 'Substitutiary Locomotion', 'Bedknobs and Broomsticks', 1971, 'Angela Lansbury, David Tomlinson', 'https://open.spotify.com/track/419PTTF9pRzns5EbDZoZ9y', true, 'deep', array['film','title','year','artist']::text[]),
  (193, 'Song 193', 'I''m No Fool', 'The Mickey Mouse Club', 1955, 'Cliff Edwards', 'https://open.spotify.com/track/5kYWUHX2dBohdyPo8upavM', true, 'deep', array['film','title','year','artist']::text[]),
  (194, 'Song 194', 'Love', 'Robin Hood', 1973, 'Nancy Adams', 'https://open.spotify.com/track/3M6YfoPwvvTHK1mnCQmqHI', true, 'iconic', array['film','title','year','artist']::text[]),
  (195, 'Song 195', 'That''s What Friends Are For', 'The Jungle Book', 1967, 'The Vultures, J. Pat O''Malley', 'https://open.spotify.com/track/35mtjM30xXExEbkEj3z1a0', true, 'familiar', array['film','title','year','artist']::text[]),
  (196, 'Song 196', 'Femininity', 'Summer Magic', 1963, 'Hayley Mills, Deborah Walley', 'https://open.spotify.com/track/24V30chf3YZQ2NhdT6K2JU', true, 'deep', array['film','title','year','artist']::text[]),
  (197, 'Song 197', 'Enjoy It!', 'In Search of the Castaways', 1962, 'Maurice Chevalier, Hayley Mills', 'https://open.spotify.com/track/4qPeTt9TjJPb2mZ9jvtYSC', true, 'deep', array['film','title','year','artist']::text[]),
  (198, 'Song 198', 'Give a Little Whistle', 'Pinocchio', 1940, 'Cliff Edwards, Dickie Jones', 'https://open.spotify.com/track/7KjviLuYXOGgK2TiyxJFQA', true, 'familiar', array['film','title','year','artist']::text[]),
  (199, 'Song 199', 'Sing Sweet Nightingale', 'Cinderella', 1950, 'Ilene Woods', 'https://open.spotify.com/track/3juY6Hy2uRCs5R8EaRxfQZ', true, 'familiar', array['film','title','year','artist']::text[]),
  (200, 'Song 200', 'I Wonder', 'Sleeping Beauty', 1959, 'Mary Costa', 'https://open.spotify.com/track/3BbRu8weo3dhszKcdxKhmZ', true, 'familiar', array['film','title','year','artist']::text[]),
  (201, 'Song 201', 'Steal the Show', 'Elemental', 2023, 'Lauv', 'https://open.spotify.com/track/0SccFtYdj75y6lL2OW10Cf', true, 'familiar', array['film','title','year','artist']::text[]),
  (202, 'Song 202', 'Across The Ocean', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/3y5jSJYfpY2ZA7G6XPKiOs', true, 'score', array['film','title','year']::text[]),
  (203, 'Song 203', 'Elemental', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1iueGRdZSh7qdbOsdWe7tC', true, 'score', array['film','title','year']::text[]),
  (204, 'Song 204', 'Sháshà r íshà', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/6Hx2Huog2Qmxr43DqGAX6E', true, 'score', array['film','title','year']::text[]),
  (205, 'Song 205', 'Stop Wade!', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1du3QeUSX87Vqh5Y3VM2mX', true, 'score', array['film','title','year']::text[]),
  (206, 'Song 206', 'Hot Air Balloon', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/4E4nEE57TjapzQzFy0ODjs', true, 'score', array['film','title','year']::text[]),
  (207, 'Song 207', 'Bubble Date', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/4YgXlFMMAuyFVwJ0OdUWwA', true, 'score', array['film','title','year']::text[]),
  (208, 'Song 208', 'Headphones', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1hWQ8PQXUJgOnG813wOFCc', true, 'score', array['film','title','year']::text[]),
  (209, 'Song 209', 'Fern Grouchwood', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/7qjLrCIp5rqg4HD6TH2655', true, 'score', array['film','title','year']::text[]),
  (210, 'Song 210', 'Beach Glass', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/6vgdSsMPw6F21V2VfSCgw2', true, 'score', array['film','title','year']::text[]),
  (211, 'Song 211', 'Cloud Puff Fireball', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/4RWNidPsWGyO0ul74yqxvk', true, 'score', array['film','title','year']::text[]),
  (212, 'Song 212', 'Clod', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/75Jzkzc6zKSmoOYGuxN2AZ', true, 'score', array['film','title','year']::text[]),
  (213, 'Song 213', 'Blue Flame', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/61qgjbKjre1DnYXkLxxVX1', true, 'score', array['film','title','year']::text[]),
  (214, 'Song 214', 'Meet The Ripples', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/6e90YafuWSeHcY40gLL8as', true, 'score', array['film','title','year']::text[]),
  (215, 'Song 215', 'Love Scooter', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/3T65eGpcbT44JqhAQvVrjw', true, 'score', array['film','title','year']::text[]),
  (216, 'Song 216', 'Crying Games', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/45BCHVBPs2fEZsvk8uPlZZ', true, 'score', array['film','title','year']::text[]),
  (217, 'Song 217', 'Grand Re-Opening', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/5G8MjzD0MYA5pyi5GUqmn8', true, 'score', array['film','title','year']::text[]),
  (218, 'Song 218', 'Tìshôk'' (Embrace The Light)', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/2NyKILRaWCWIxYJh4VoAMK', true, 'score', array['film','title','year']::text[]),
  (219, 'Song 219', 'Pipe Blows', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/6C5T5YxKZl54Nvv25HPmmH', true, 'score', array['film','title','year']::text[]),
  (220, 'Song 220', 'Run for Your Life', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/3kKa8DcvHRLtBi6MecHIq8', true, 'score', array['film','title','year']::text[]),
  (221, 'Song 221', 'Kol-Nuts', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/0e29orJAWxHkhGnk8nKVVl', true, 'score', array['film','title','year']::text[]),
  (222, 'Song 222', 'Red Dot Sale', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/50LEwKnAX7S7oA0em5TXHK', true, 'score', array['film','title','year']::text[]),
  (223, 'Song 223', '1000mph', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/7CrAG1A81G6LR44nfegQAW', true, 'score', array['film','title','year']::text[]),
  (224, 'Song 224', 'Smoke Reading', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1QKFRExSQyoHOkvoEqC0PZ', true, 'score', array['film','title','year']::text[]),
  (225, 'Song 225', 'Rusty Hint of Motor Oil', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/64YaaynpS4fLvkxY1VDcG0', true, 'score', array['film','title','year']::text[]),
  (226, 'Song 226', 'Mineral Lake', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/31ZGDoXEIJuDryYr4YXqeH', true, 'score', array['film','title','year']::text[]),
  (227, 'Song 227', 'Lucky', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/7xDCPW1WI1rkxM4HZAF6Ka', true, 'score', array['film','title','year']::text[]),
  (228, 'Song 228', 'Garden Central Station', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/7ckbtXr9pjwf5gLqDJw4mm', true, 'score', array['film','title','year']::text[]),
  (229, 'Song 229', 'Full Purple', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1Uspb8vWtI7vKWq9kwk0EG', true, 'score', array['film','title','year']::text[]),
  (230, 'Song 230', 'Vivisteria', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/0KqkxnPQ2mtIwd8oIPCF6N', true, 'score', array['film','title','year']::text[]),
  (231, 'Song 231', 'Firish', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/2XH9BE0K3gTco7K3pAB5lk', true, 'score', array['film','title','year']::text[]),
  (232, 'Song 232', 'A Lonely Man Awash in Sadness', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/3xw3LUpJ7JZB8vdkcSRpcX', true, 'score', array['film','title','year']::text[]),
  (233, 'Song 233', 'Firetown Flood', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1kNNeHUUCF4wkX4G04GLN7', true, 'score', array['film','title','year']::text[]),
  (234, 'Song 234', 'You Were The Dream', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/7AuiA0bXGugCPnyHEEq0Kz', true, 'score', array['film','title','year']::text[]),
  (235, 'Song 235', 'Make Connection', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/4dl7zywmrZvnl4eYvGAc4Y', true, 'score', array['film','title','year']::text[]),
  (236, 'Song 236', 'Bà Ksô (The Big Bow)', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/47Z7w345pJnOTlEyptrajv', true, 'score', array['film','title','year']::text[]),
  (237, 'Song 237', 'Grand Redux', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1AoKzksSinmK8wLoBM13PX', true, 'score', array['film','title','year']::text[]),
  (238, 'Song 238', 'Nobody Like U', 'Turning Red', 2022, '4*TOWN (From Disney and Pixar’s Turning Red), Jordan Fisher, Finneas O''Connell, Topher Ngo, Grayson Villanueva, Josh Levi', 'https://open.spotify.com/track/4bV5sf2B4hWBBd5HQ8S7KB', true, 'familiar', array['film','title','year','artist']::text[]),
  (239, 'Song 239', '1 True Love', 'Turning Red', 2022, '4*TOWN (From Disney and Pixar’s Turning Red), Jordan Fisher, Finneas O''Connell, Topher Ngo, Grayson Villanueva, Josh Levi', 'https://open.spotify.com/track/2dJ1UJEQQq3jkLSJP4ZIoi', true, 'familiar', array['film','title','year','artist']::text[]),
  (240, 'Song 240', 'U Know What''s Up', 'Turning Red', 2022, '4*TOWN (From Disney and Pixar’s Turning Red), Jordan Fisher, Finneas O''Connell, Topher Ngo, Grayson Villanueva, Josh Levi', 'https://open.spotify.com/track/0d83zVs3OmdjrhfoAxg1dE', true, 'familiar', array['film','title','year','artist']::text[]),
  (241, 'Song 241', 'Family', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/0Y4fHfh5mrsPZh6JPCkdiq', true, 'score', array['film','title','year']::text[]),
  (242, 'Song 242', 'Turning Red', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/14WCShU6Yz3a0xXVRaFkze', true, 'score', array['film','title','year']::text[]),
  (243, 'Song 243', 'Meilin Lee', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/2L8CCEd57JW9Doagvzbgvq', true, 'score', array['film','title','year']::text[]),
  (244, 'Song 244', 'Temple Duties', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/78Ti5nbVzqhZRJM8hcDjVB', true, 'score', array['film','title','year']::text[]),
  (245, 'Song 245', 'Jin''s Family Dinner', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/6GUtAVobfkf5zlXsIIzftu', true, 'score', array['film','title','year']::text[]),
  (246, 'Song 246', 'Drawing Love', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/2BtepU6hj1cYs896ohGFlM', true, 'score', array['film','title','year']::text[]),
  (247, 'Song 247', 'Never Again Dream', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/0VIv2Rlhgkt6UxEPUuetYd', true, 'score', array['film','title','year']::text[]),
  (248, 'Song 248', 'Turning Panda', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/3gTwos056r6nCqdIVG4sU7', true, 'score', array['film','title','year']::text[]),
  (249, 'Song 249', 'Panda-monium', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/5DZcOTy5wOfzlvVaqbnS7R', true, 'score', array['film','title','year']::text[]),
  (250, 'Song 250', 'Ancestors', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/2aYUdzMztAS2u1AzyEuhF3', true, 'score', array['film','title','year']::text[]),
  (251, 'Song 251', 'Inconvenient Genetics', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/2UXu6WZG90VWhRhcKC3FRw', true, 'score', array['film','title','year']::text[]),
  (252, 'Song 252', 'U Know What''s Up - The Panda Hustle Version', 'Turning Red', 2022, '4*TOWN (From Disney and Pixar’s Turning Red), Jordan Fisher, Finneas O''Connell, Topher Ngo, Grayson Villanueva, Josh Levi', 'https://open.spotify.com/track/6Xi7ye58IILUXhxcOyibUj', true, 'familiar', array['film','title','year','artist']::text[]),
  (253, 'Song 253', 'Tyler''s Deal', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/5C1E1Rb9cZsRJn93eE82PJ', true, 'score', array['film','title','year']::text[]),
  (254, 'Song 254', 'The Aunties', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/7rf7EPzOseqv5DZ0tfDWPM', true, 'score', array['film','title','year']::text[]),
  (255, 'Song 255', 'Grandma''s Warning', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/70zHcWrnnHfedQclKqBmV6', true, 'score', array['film','title','year']::text[]),
  (256, 'Song 256', 'Keeping The Panda', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/2iLimJrdD4YEfMtehEdoJW', true, 'score', array['film','title','year']::text[]),
  (257, 'Song 257', 'Dad Talk', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/7GwAdttIk9cVxTq9xlecfW', true, 'score', array['film','title','year']::text[]),
  (258, 'Song 258', 'Red Moon Ritual', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/7dyfRmJL0y2uS9tY1SSeNV', true, 'score', array['film','title','year']::text[]),
  (259, 'Song 259', 'I''m Keeping It', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/1skvW7rObp5T9Ih9E4ehxy', true, 'score', array['film','title','year']::text[]),
  (260, 'Song 260', 'Making It Right', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/0Nh5DZ4QR4zaVIIgUyWoUy', true, 'score', array['film','title','year']::text[]),
  (261, 'Song 261', 'Unleashing The Panda', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/35SyQXOC2BnAjIq5bffJ3x', true, 'score', array['film','title','year']::text[]),
  (262, 'Song 262', 'Stadium Ritual', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/3b7l6fz1rkWEbkNCLXna8O', true, 'score', array['film','title','year']::text[]),
  (263, 'Song 263', 'Pandas Unite / Nobody Like U (Reprise)', 'Turning Red', 2022, 'Ludwig Göransson, 4*TOWN (From Disney and Pixar’s Turning Red), Jordan Fisher, Finneas O''Connell, Topher Ngo, Grayson Villanueva, Turning Red - Cast, Josh Levi', 'https://open.spotify.com/track/4dksoaJqf0k9mwrvAuUcqR', true, 'familiar', array['film','title','year','artist']::text[]),
  (264, 'Song 264', 'The Real Ming', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/6QOhJlDwl2rQD9heV2wRoO', true, 'score', array['film','title','year']::text[]),
  (265, 'Song 265', 'No Going Back', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/68ktW79mI9wV8p8rzi3eTZ', true, 'score', array['film','title','year']::text[]),
  (266, 'Song 266', 'Let Your Inner Panda Out', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/7kfBaJPaU2c9x2FZ11Jf6y', true, 'score', array['film','title','year']::text[]),
  (267, 'Song 267', 'Nobody Like U - Instrumental', 'Turning Red', 2022, 'Finneas O''Connell', 'https://open.spotify.com/track/54NByBSOOk4BIADWdBOqy5', true, 'score', array['film','title','year']::text[]),
  (268, 'Song 268', '1 True Love - Instrumental', 'Turning Red', 2022, 'Finneas O''Connell', 'https://open.spotify.com/track/6Zn7RrR1nhndMKh5zgKfnF', true, 'score', array['film','title','year']::text[]),
  (269, 'Song 269', 'U Know What''s Up - Instrumental', 'Turning Red', 2022, 'Finneas O''Connell', 'https://open.spotify.com/track/4GzGqBXvIS2z2OXhAMnDJL', true, 'score', array['film','title','year']::text[]),
  (270, 'Song 270', 'Meet Luca', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/0Dpbz2JbQcECzhED9Mh5v1', true, 'score', array['film','title','year']::text[]),
  (271, 'Song 271', 'Did You Hide?', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/2sGfQd4bOMTrUdPLYqKB3p', true, 'score', array['film','title','year']::text[]),
  (272, 'Song 272', 'The Curious Fish', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/2HymCSDIrD8iidWwp8gCxr', true, 'score', array['film','title','year']::text[]),
  (273, 'Song 273', 'You Forgot Your Harpoon', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/1OZ7ZbsCXU11M1VSaToMOO', true, 'score', array['film','title','year']::text[]),
  (274, 'Song 274', 'Phantom Tail', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/3E8UJGk1fHXF97mU4Hm3cj', true, 'score', array['film','title','year']::text[]),
  (275, 'Song 275', 'Walking Is Just Like Swimming', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/1HO9pqZV4Yy2Wj8Rc73XCE', true, 'score', array['film','title','year']::text[]),
  (276, 'Song 276', 'Vespa è Libertà', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/4EpVsgCRzsyLBvgzN51uEh', true, 'score', array['film','title','year']::text[]),
  (277, 'Song 277', 'You Hold the Ramp', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/3H1uqrvsYCLRjTVJIapBiy', true, 'score', array['film','title','year']::text[]),
  (278, 'Song 278', 'Silenzio Bruno', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/2naKAHiRFfKStkVnYjZA6U', true, 'score', array['film','title','year']::text[]),
  (279, 'Song 279', 'That''s the Dream', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/2VseWmXoQ3mpyQNeFyr7zo', true, 'score', array['film','title','year']::text[]),
  (280, 'Song 280', 'The Bottom of the Ocean', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/6eP78WlOWQSGUyqoL7ikwC', true, 'score', array['film','title','year']::text[]),
  (281, 'Song 281', 'Take Me, Gravity', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/7pfDiHoNYGWZphw7fmBrXD', true, 'score', array['film','title','year']::text[]),
  (282, 'Song 282', 'Portorosso', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/7Kiw0qwDBYzXUVAXpNeNGk', true, 'score', array['film','title','year']::text[]),
  (283, 'Song 283', 'Signor Vespa', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/5fqsI6qgS19E5TnHZE06Qs', true, 'score', array['film','title','year']::text[]),
  (284, 'Song 284', 'This Isn''t Any Old Race', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/42RRZH2xPCakr6uL8icqQO', true, 'score', array['film','title','year']::text[]),
  (285, 'Song 285', 'Buonanotte, Boys', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/0U2433z85gy1yPPfZHOP7X', true, 'score', array['film','title','year']::text[]),
  (286, 'Song 286', 'Land Monsters Everywhere', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/12RsPKfCMUluznd32DZj3g', true, 'score', array['film','title','year']::text[]),
  (287, 'Song 287', 'Buongiorno Massimo', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/6a4l2exSGb3dmpfPqbTVlv', true, 'score', array['film','title','year']::text[]),
  (288, 'Song 288', 'The Out of Town Weirdo Tax', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/5I5EFxa7MWgSlCM7QUe5LR', true, 'score', array['film','title','year']::text[]),
  (289, 'Song 289', 'Rules Are for Rule People', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/4Tf2wuKrBt0wfhyazH3dpv', true, 'score', array['film','title','year']::text[]),
  (290, 'Song 290', 'How Humans Swim', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/1JV3eamC6SdiaQEUXJUFfX', true, 'score', array['film','title','year']::text[]),
  (291, 'Song 291', 'Not Our Kid', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/09YaOkh0tJFSAgGef8mPL0', true, 'score', array['film','title','year']::text[]),
  (292, 'Song 292', 'Telescope', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/7nEyry1XTeLdc5nqs1uFWH', true, 'score', array['film','title','year']::text[]),
  (293, 'Song 293', 'Beyond the Solar System', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/6byBlc1GyBEqaiNwIwL9iN', true, 'score', array['film','title','year']::text[]),
  (294, 'Song 294', 'We Don''t Need Anybody', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/0cbuhPUAqz288Mx4FZOORg', true, 'score', array['film','title','year']::text[]),
  (295, 'Song 295', 'The Sea Monster', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/4Lw00Tf3yA8b2uW5q18HVy', true, 'score', array['film','title','year']::text[]),
  (296, 'Song 296', 'I Wish I Could Take It Back', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/7zTyflHttnxEmnaWOAuiO8', true, 'score', array['film','title','year']::text[]),
  (297, 'Song 297', 'The Portorosso Cup', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/2LhkeDrqMIezpBnfMHNEPo', true, 'score', array['film','title','year']::text[]),
  (298, 'Song 298', 'How to Find the Good Ones', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/4EMGbgH7NdmrboU5GzvPaU', true, 'score', array['film','title','year']::text[]),
  (299, 'Song 299', 'Go Find Out for Me', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/3EwGfyOpbJqLGVAkXkuGmq', true, 'score', array['film','title','year']::text[]),
  (300, 'Song 300', 'Born to Play', 'Soul', 2020, 'Jon Batiste', 'https://open.spotify.com/track/4BmuAIPAsCiS2NhqT0gSfL', true, 'familiar', array['film','title','year','artist']::text[])
)
insert into public.dmq_songs (song_number,label,title,film,year,artist,spotify_url,enabled,question_profile,allowed_questions)
select * from new_songs
on conflict (song_number) do update set label=excluded.label,title=excluded.title,film=excluded.film,year=excluded.year,artist=excluded.artist,spotify_url=excluded.spotify_url,enabled=excluded.enabled,question_profile=excluded.question_profile,allowed_questions=excluded.allowed_questions,updated_at=now();

update public.dmq_songs set question_profile='iconic' where song_number between 1 and 150 and song_number in (1,2,3,4,5,6,9,10,11,12,15,16,17,20,21,22,25,26,30,31,40,43,47,48,96,97,100,101,102,103,104,107,108,110,113,115,119,122,126,127,130,132,134,135,143,144,147,148,149,150);
update public.dmq_songs set question_profile='deep' where song_number between 1 and 150 and question_profile<>'iconic' and song_number in (38,39,45,46,54,55,59,61,62,65,66,69,71,74,77,81,82,84,85,86,87,88,89,90,91,93,94,95,99,105,106,109,111,112,114,116,117,118,120,121,123,124,125,128,129,131,133,136,137,138,139,140,141,142,145,146);
update public.dmq_songs set question_profile='familiar' where song_number between 1 and 150 and question_profile not in ('iconic','deep');
commit;

select count(*) as actieve_songs,count(*) filter (where question_profile='iconic') as iconisch,count(*) filter (where question_profile='familiar') as bekend,count(*) filter (where question_profile='deep') as moeilijk,count(*) filter (where question_profile='score') as instrumentaal from public.dmq_songs where enabled=true;
