-- Music Match v7: 300 unieke originele Disney-soundtracktracks met vraagprofielen
-- Veilig opnieuw uitvoerbaar in Supabase SQL Editor.

begin;
alter table public.dmq_songs drop constraint if exists dmq_songs_song_number_check;
alter table public.dmq_songs add constraint dmq_songs_song_number_check check (song_number between 1 and 300);
alter table public.dmq_songs add column if not exists question_profile text not null default 'familiar';
alter table public.dmq_songs add column if not exists allowed_questions text[] not null default array['film','title','year','artist']::text[];
alter table public.dmq_songs drop constraint if exists dmq_songs_question_profile_check;
alter table public.dmq_songs add constraint dmq_songs_question_profile_check check (question_profile in ('iconic','familiar','deep','score'));

with new_songs (song_number,label,title,film,year,artist,spotify_url,enabled,question_profile,allowed_questions) as (
 values
  -- Vervang de 32 doublures uit de oude uitbreiding 101-150 door unieke originele soundtracktracks.
  (101, 'Song 101', 'VK Mashup', 'Descendants 3', 2019, 'Dove Cameron, Sofia Carson, Booboo Stewart, Cameron Boyce', 'https://open.spotify.com/track/7Ci4hHa9wvMajOqt5EpOQK', true, 'deep', array['film','title','year','artist']::text[]),
  (102, 'Song 102', 'The Climb', 'Hannah Montana: The Movie', 2009, 'Miley Cyrus', 'https://open.spotify.com/track/0V8FYVlBFuXXTIvRnMbZyS', true, 'familiar', array['film','title','year','artist']::text[]),
  (103, 'Song 103', 'On My Own', 'Teen Beach 2', 2015, 'Ross Lynch', 'https://open.spotify.com/track/51xUartdwQzXmtrwHyXRVp', true, 'deep', array['film','title','year','artist']::text[]),
  (107, 'Song 107', 'Hero', 'Starstruck', 2010, 'Christopher Wilde', 'https://open.spotify.com/track/3q3pZHncNkvIWJebMeuQqQ', true, 'familiar', array['film','title','year','artist']::text[]),
  (108, 'Song 108', 'Space Between', 'Descendants 2', 2017, 'Dove Cameron, Sofia Carson', 'https://open.spotify.com/track/3N1V03yrqyNPo5A4Fu2Wd7', true, 'familiar', array['film','title','year','artist']::text[]),
  (109, 'Song 109', 'Turn Up the Music', 'Lemonade Mouth', 2011, 'Bridgit Mendler, Adam Hicks, Naomi Scott, Hayley Kiyoko', 'https://open.spotify.com/track/4bb2UdCvi9LynD4rWvE06T', true, 'deep', array['film','title','year','artist']::text[]),
  (110, 'Song 110', 'You Are the Music in Me', 'High School Musical 2', 2007, 'Vanessa Hudgens, Zac Efron', 'https://open.spotify.com/track/6TRp2628QKH3kY6KrCnjqp', true, 'familiar', array['film','title','year','artist']::text[]),
  (113, 'Song 113', 'Did I Mention', 'Descendants', 2015, 'Jeff Lewis, Mitchell Hope', 'https://open.spotify.com/track/1YekSxsAlGlYvm9zjLsKdh', true, 'deep', array['film','title','year','artist']::text[]),
  (114, 'Song 114', 'Can''t Stop Singing', 'Teen Beach Movie', 2013, 'Ross Lynch, Maia Mitchell', 'https://open.spotify.com/track/2adTfABiJJQpZWlujYO3Qo', true, 'familiar', array['film','title','year','artist']::text[]),
  (115, 'Song 115', 'Can I Have This Dance', 'High School Musical 3', 2008, 'Vanessa Hudgens, Zac Efron', 'https://open.spotify.com/track/6YXG34IWbilypPwjBTOrUC', true, 'familiar', array['film','title','year','artist']::text[]),
  (116, 'Song 116', 'Something About the Sunshine', 'Starstruck', 2010, 'Anna Margaret, Christopher Wilde', 'https://open.spotify.com/track/0Jcnr8HUGQdaOiSkqpdEKX', true, 'deep', array['film','title','year','artist']::text[]),
  (117, 'Song 117', 'Somebody', 'Lemonade Mouth', 2011, 'Bridgit Mendler', 'https://open.spotify.com/track/0KXvGydCYbBgHUlqrDbz3N', true, 'familiar', array['film','title','year','artist']::text[]),
  (126, 'Song 126', 'Starstruck', 'Starstruck', 2010, 'Christopher Wilde', 'https://open.spotify.com/track/03teNQu8rWlFnNzF1ULXIq', true, 'familiar', array['film','title','year','artist']::text[]),
  (127, 'Song 127', 'He Could Be the One', 'Hannah Montana', 2009, 'Hannah Montana', 'https://open.spotify.com/track/07HPV6hzecJmMJwsIX8YVU', true, 'familiar', array['film','title','year','artist']::text[]),
  (128, 'Song 128', 'Cruisin'' for a Bruisin''', 'Teen Beach Movie', 2013, 'Ross Lynch, Jason Evigan, Grace Phipps', 'https://open.spotify.com/track/5e3UWcbvTaF5CJWu81MqlQ', true, 'familiar', array['film','title','year','artist']::text[]),
  (129, 'Song 129', 'So Far So Great', 'Sonny with a Chance', 2009, 'Demi Lovato', 'https://open.spotify.com/track/6bggFlWw1UcfiYepg8B3KH', true, 'deep', array['film','title','year','artist']::text[]),
  (130, 'Song 130', 'Wildside', 'Adventures in Babysitting', 2016, 'Sabrina Carpenter, Sofia Carson', 'https://open.spotify.com/track/0FgzKYAKXRPlu9BEZwYeV0', true, 'deep', array['film','title','year','artist']::text[]),
  (131, 'Song 131', 'Breakthrough', 'Lemonade Mouth', 2011, 'Bridgit Mendler, Adam Hicks, Naomi Scott, Hayley Kiyoko', 'https://open.spotify.com/track/7eAWmk6IDva2iA0q2Wx9Lv', true, 'deep', array['film','title','year','artist']::text[]),
  (132, 'Song 132', 'Brand New Day', 'Camp Rock 2: The Final Jam', 2010, 'Demi Lovato', 'https://open.spotify.com/track/7MG5A5HdsYjlHNjFp6Z7ec', true, 'deep', array['film','title','year','artist']::text[]),
  (133, 'Song 133', 'Falling for Ya', 'Teen Beach Movie', 2013, 'Grace Phipps', 'https://open.spotify.com/track/5zZJ9yrJw4bxoPTLoRXfIl', true, 'deep', array['film','title','year','artist']::text[]),
  (134, 'Song 134', 'Legendary', 'Disney Channel', 2018, 'Disney Channel Stars', 'https://open.spotify.com/track/6mVT7VRlkrwiFYhjG1XY5O', true, 'deep', array['film','title','year','artist']::text[]),
  (135, 'Song 135', 'That''s What I''m Talkin'' Bout', 'High School Musical: The Musical: The Series', 2023, 'Kylie Cantrall', 'https://open.spotify.com/track/71ggN92ZqqBtlbBPvnYiIx', true, 'deep', array['film','title','year','artist']::text[]),
  (136, 'Song 136', 'Stick to the Status Quo', 'High School Musical', 2006, 'High School Musical Cast', 'https://open.spotify.com/track/5aNagthlHAudbDZozQMjYP', true, 'familiar', array['film','title','year','artist']::text[]),
  (137, 'Song 137', 'One and the Same', 'Princess Protection Program', 2009, 'Selena Gomez, Demi Lovato', 'https://open.spotify.com/track/1QkJBQnCv81ef7gyWMDL3Q', true, 'deep', array['film','title','year','artist']::text[]),
  (139, 'Song 139', 'Can''t Back Down', 'Camp Rock 2: The Final Jam', 2010, 'Demi Lovato, Alyson Stoner', 'https://open.spotify.com/track/51NrdlQOSTeq0d6U7xRKsz', true, 'deep', array['film','title','year','artist']::text[]),
  (140, 'Song 140', 'Oxygen', 'Teen Beach 2', 2015, 'Maia Mitchell', 'https://open.spotify.com/track/1TlpGVfJYKvSCgGt8nAFBj', true, 'deep', array['film','title','year','artist']::text[]),
  (143, 'Song 143', 'It''s Goin'' Down', 'Descendants 2', 2017, 'Dove Cameron, Sofia Carson, China Anne McClain, Thomas Doherty', 'https://open.spotify.com/track/537mRuCCiKQNFlN1vdSl1k', true, 'familiar', array['film','title','year','artist']::text[]),
  (144, 'Song 144', 'Surf Crazy', 'Teen Beach Movie', 2013, 'Teen Beach Movie Cast', 'https://open.spotify.com/track/4Xt0OKNJtbyqx5GEX2XpVF', true, 'deep', array['film','title','year','artist']::text[]),
  (145, 'Song 145', 'Gotta Be Me', 'Teen Beach 2', 2015, 'Ross Lynch, Maia Mitchell, Garrett Clayton, Grace Phipps', 'https://open.spotify.com/track/58iuuMeVzgGhCwhnx3zBAP', true, 'deep', array['film','title','year','artist']::text[]),
  (146, 'Song 146', 'Meant to Be', 'Teen Beach Movie', 2013, 'Ross Lynch, Maia Mitchell, Garrett Clayton, Grace Phipps', 'https://open.spotify.com/track/6gDPf8eJIRQ73rUktH17P3', true, 'deep', array['film','title','year','artist']::text[]),
  (147, 'Song 147', 'Here We Go', 'Lemonade Mouth', 2011, 'Adam Hicks, Bridgit Mendler, Hayley Kiyoko', 'https://open.spotify.com/track/2GYOC7EBfXulEeezqHzhfZ', true, 'deep', array['film','title','year','artist']::text[]),
  (148, 'Song 148', 'Better in Stereo', 'Liv and Maddie', 2013, 'Dove Cameron', 'https://open.spotify.com/track/2eKYRRrNhXXr7SSzE3X99F', true, 'deep', array['film','title','year','artist']::text[]),
  (151, 'Song 151', 'Chim Chim Cher-ee', 'Mary Poppins', 1964, 'Dick Van Dyke, Julie Andrews', 'https://open.spotify.com/track/23NtySnCSYOnjuhuLErsS5', true, 'familiar', array['film','title','year','artist']::text[]),
  (152, 'Song 152', 'Jolly Holiday', 'Mary Poppins', 1964, 'Dick Van Dyke, Julie Andrews', 'https://open.spotify.com/track/3sSpgPbDF16wncH7Zw4kqh', true, 'familiar', array['film','title','year','artist']::text[]),
  (153, 'Song 153', 'Let''s Get Together', 'The Parent Trap', 1961, 'Hayley Mills', 'https://open.spotify.com/track/6g3YUqir5Gngxn5lcA1wDL', true, 'deep', array['film','title','year','artist']::text[]),
  (154, 'Song 154', 'The Ugly Bug Ball', 'Summer Magic', 1963, 'Burl Ives', 'https://open.spotify.com/track/2CK9yTLAJEg6sLzLhn2LHY', true, 'deep', array['film','title','year','artist']::text[]),
  (155, 'Song 155', 'The Spectrum Song', 'An Adventure in Color', 1961, 'Paul Frees', 'https://open.spotify.com/track/6aMg4mBvBXotBg4zE6cJ4z', true, 'deep', array['film','title','year','artist']::text[]),
  (156, 'Song 156', 'Colonel Hathi''s March', 'The Jungle Book', 1967, 'J. Pat O''Malley', 'https://open.spotify.com/track/3VEV9UsGggVjjiworiuscR', true, 'familiar', array['film','title','year','artist']::text[]),
  (157, 'Song 157', 'A Whale of a Tale', '20,000 Leagues Under the Sea', 1954, 'Kirk Douglas', 'https://open.spotify.com/track/6ambk6KgfytRADHb0x8rx0', true, 'deep', array['film','title','year','artist']::text[]),
  (158, 'Song 158', 'You Can Fly! You Can Fly! You Can Fly!', 'Peter Pan', 1953, 'Bobby Driscoll, Kathryn Beaumont', 'https://open.spotify.com/track/7JD4aIrbFXH3eI7eqmIKhi', true, 'iconic', array['film','title','year','artist']::text[]),
  (159, 'Song 159', 'The Work Song', 'Cinderella', 1950, 'James MacDonald, The Mouse Chorus', 'https://open.spotify.com/track/38oDrV3xYjeivR8X10fFr1', true, 'familiar', array['film','title','year','artist']::text[]),
  (160, 'Song 160', 'Nutcracker Suite: Dance of the Reed Flutes', 'Fantasia', 1940, 'Pyotr Ilyich Tchaikovsky', 'https://open.spotify.com/track/6lvapUEO0jY0whLxFtXkNy', true, 'score', array['film','title','year']::text[]),
  (161, 'Song 161', 'Main Title (Love Is a Song)', 'Bambi', 1942, 'Donald Novis', 'https://open.spotify.com/track/6ZP66zQZjwN1P0QWR9fdSP', true, 'deep', array['film','title','year','artist']::text[]),
  (162, 'Song 162', 'Minnie''s Yoo Hoo', 'Mickey Mouse', 1929, 'Walt Disney, Carl Stalling', 'https://open.spotify.com/track/4Z5u4KsPcnTKPMcHzTbMTg', true, 'deep', array['film','title','year','artist']::text[]),
  (163, 'Song 163', 'Candle on the Water', 'Pete''s Dragon', 1977, 'Helen Reddy', 'https://open.spotify.com/track/74UZSX03wVCDrZoQQ0d2ZV', true, 'familiar', array['film','title','year','artist']::text[]),
  (164, 'Song 164', 'The Age of Not Believing', 'Bedknobs and Broomsticks', 1971, 'Angela Lansbury', 'https://open.spotify.com/track/1Afzcuo0XKgOiGS9sdq8ko', true, 'deep', array['film','title','year','artist']::text[]),
  (165, 'Song 165', 'Feed the Birds', 'Mary Poppins', 1964, 'Julie Andrews', 'https://open.spotify.com/track/4P73qgh9VA1S9Hct6VhLI4', true, 'iconic', array['film','title','year','artist']::text[]),
  (166, 'Song 166', 'Let''s Go Fly a Kite', 'Mary Poppins', 1964, 'David Tomlinson, Dick Van Dyke', 'https://open.spotify.com/track/3BHxMGVE3tN2dZsVU1l487', true, 'iconic', array['film','title','year','artist']::text[]),
  (167, 'Song 167', 'it''s a small world', 'Disneyland Park', 1964, 'Disneyland Children''s Chorus', 'https://open.spotify.com/track/5ouuPi1o6eOVSgHn2exemw', true, 'iconic', array['film','title','year','artist']::text[]),
  (168, 'Song 168', 'The Tiki, Tiki, Tiki Room', 'Disneyland Park', 1963, 'The Mellomen', 'https://open.spotify.com/track/0QQHnY4ZCg1m3NrmP5wI1B', true, 'familiar', array['film','title','year','artist']::text[]),
  (169, 'Song 169', 'Mickey Mouse March', 'The Mickey Mouse Club', 1955, 'Jimmie Dodd', 'https://open.spotify.com/track/1ejNfxKt0g11lIXsGsdZU0', true, 'iconic', array['film','title','year','artist']::text[]),
  (170, 'Song 170', 'The Second Star to the Right', 'Peter Pan', 1953, 'The Jud Conlon Chorus', 'https://open.spotify.com/track/2q1LwxkM3q9L96cPrykyzd', true, 'iconic', array['film','title','year','artist']::text[]),
  (171, 'Song 171', 'So This Is Love', 'Cinderella', 1950, 'Ilene Woods, Mike Douglas', 'https://open.spotify.com/track/1EwRMgWXS9U8Oet39tlYwY', true, 'iconic', array['film','title','year','artist']::text[]),
  (172, 'Song 172', 'Who''s Afraid of the Big Bad Wolf?', 'Three Little Pigs', 1933, 'Mary Moder, Dorothy Compton, Pinto Colvig', 'https://open.spotify.com/track/7e0SeoYblUCKeVHqFpKEt7', true, 'familiar', array['film','title','year','artist']::text[]),
  (173, 'Song 173', 'Family', 'James and the Giant Peach', 1996, 'James and the Giant Peach Cast', 'https://open.spotify.com/track/2AhzgGDcGC7jkimbYDN6Bc', true, 'deep', array['film','title','year','artist']::text[]),
  (174, 'Song 174', 'Les Poissons', 'The Little Mermaid', 1989, 'René Auberjonois', 'https://open.spotify.com/track/04LkB4linu702YDzlrQNDi', true, 'familiar', array['film','title','year','artist']::text[]),
  (175, 'Song 175', 'Mine, Mine, Mine', 'Pocahontas', 1995, 'David Ogden Stiers, Mel Gibson', 'https://open.spotify.com/track/41uJggpcL0qwQasVkKV50y', true, 'familiar', array['film','title','year','artist']::text[]),
  (176, 'Song 176', 'Jack''s Lament', 'The Nightmare Before Christmas', 1993, 'Danny Elfman', 'https://open.spotify.com/track/4VCexsNDyC2j8ZrY34RwV0', true, 'familiar', array['film','title','year','artist']::text[]),
  (177, 'Song 177', 'My Name Is James', 'James and the Giant Peach', 1996, 'Paul Terry', 'https://open.spotify.com/track/7EoLnnEPjNRWXdXrSxY4B5', true, 'deep', array['film','title','year','artist']::text[]),
  (178, 'Song 178', 'Heffalumps and Woozles', 'The Many Adventures of Winnie the Pooh', 1977, 'The Mellomen', 'https://open.spotify.com/track/2Nmmt8UIJATpJIdlmv4FrH', true, 'familiar', array['film','title','year','artist']::text[]),
  (179, 'Song 179', 'Portobello Road', 'Bedknobs and Broomsticks', 1971, 'David Tomlinson, Angela Lansbury', 'https://open.spotify.com/track/5IItAEDYGuoqvw6kRL7HO1', true, 'deep', array['film','title','year','artist']::text[]),
  (180, 'Song 180', 'Stay Awake', 'Mary Poppins', 1964, 'Julie Andrews', 'https://open.spotify.com/track/0DcxLrvPPkOQtytolEC5ZI', true, 'familiar', array['film','title','year','artist']::text[]),
  (181, 'Song 181', 'Following the Leader', 'Peter Pan', 1953, 'Bobby Driscoll, Paul Collins', 'https://open.spotify.com/track/5b4Z27O4GMxiqlHLZx8Pxb', true, 'familiar', array['film','title','year','artist']::text[]),
  (182, 'Song 182', 'The Ballad of Davy Crockett', 'Davy Crockett', 1955, 'The Wellingtons', 'https://open.spotify.com/track/5hDKXaqNk8QuwZoEIDAJU9', true, 'deep', array['film','title','year','artist']::text[]),
  (183, 'Song 183', 'Pink Elephants on Parade', 'Dumbo', 1941, 'The Sportsmen', 'https://open.spotify.com/track/06IWtDiU8D6DK8vSU072pa', true, 'familiar', array['film','title','year','artist']::text[]),
  (184, 'Song 184', 'Little April Shower', 'Bambi', 1942, 'Amy Lou Barnes, Sally Mueller', 'https://open.spotify.com/track/1ryI0iueOhVzXKSBO7ESxK', true, 'familiar', array['film','title','year','artist']::text[]),
  (185, 'Song 185', 'The Silly Song', 'Snow White and the Seven Dwarfs', 1937, 'The Dwarf Chorus', 'https://open.spotify.com/track/7qMriHg2jWHPQW9sdhLPZG', true, 'familiar', array['film','title','year','artist']::text[]),
  (186, 'Song 186', 'One Last Hope', 'Hercules', 1997, 'Danny DeVito', 'https://open.spotify.com/track/0Z06gAgsGv5hsLzvC06XMP', true, 'familiar', array['film','title','year','artist']::text[]),
  (187, 'Song 187', 'A Guy Like You', 'The Hunchback of Notre Dame', 1996, 'Jason Alexander, Charles Kimbrough, Mary Wickes', 'https://open.spotify.com/track/3BoaBZQsCU12IEEJeficPS', true, 'deep', array['film','title','year','artist']::text[]),
  (188, 'Song 188', 'On the Open Road', 'A Goofy Movie', 1995, 'Bill Farmer, Aaron Lohr', 'https://open.spotify.com/track/07XDfjpXYL8T0wOGMk81Xr', true, 'familiar', array['film','title','year','artist']::text[]),
  (189, 'Song 189', 'Fantasmic! Exit Music', 'Disneyland Park', 1992, 'Bruce Healey', 'https://open.spotify.com/track/0PZCJRizjjaygMsxthL0dr', true, 'score', array['film','title','year']::text[]),
  (190, 'Song 190', 'Oogie Boogie''s Song', 'The Nightmare Before Christmas', 1993, 'Ken Page, Ed Ivory', 'https://open.spotify.com/track/1TctVlWvNpmKGHMuPqJ5G2', true, 'iconic', array['film','title','year','artist']::text[]),
  (191, 'Song 191', 'I Will Go Sailing No More', 'Toy Story', 1995, 'Randy Newman', 'https://open.spotify.com/track/3oFSbVCS8conK9GwJWOSH6', true, 'familiar', array['film','title','year','artist']::text[]),
  (192, 'Song 192', 'Substitutiary Locomotion', 'Bedknobs and Broomsticks', 1971, 'Angela Lansbury, David Tomlinson', 'https://open.spotify.com/track/419PTTF9pRzns5EbDZoZ9y', true, 'deep', array['film','title','year','artist']::text[]),
  (193, 'Song 193', 'I''m No Fool', 'The Mickey Mouse Club', 1955, 'Cliff Edwards', 'https://open.spotify.com/track/5kYWUHX2dBohdyPo8upavM', true, 'deep', array['film','title','year','artist']::text[]),
  (194, 'Song 194', 'What Time Is It', 'High School Musical 2', 2007, 'Zac Efron, Vanessa Hudgens, Lucas Grabeel, Corbin Bleu, Ashley Tisdale, Monique Coleman', 'https://open.spotify.com/track/6NqfslFfCCOyBQ0Xw8kN8E', true, 'familiar', array['film','title','year','artist']::text[]),
  (195, 'Song 195', 'That''s What Friends Are For', 'The Jungle Book', 1967, 'The Vultures, J. Pat O''Malley', 'https://open.spotify.com/track/35mtjM30xXExEbkEj3z1a0', true, 'familiar', array['film','title','year','artist']::text[]),
  (196, 'Song 196', 'Femininity', 'Summer Magic', 1963, 'Hayley Mills, Deborah Walley', 'https://open.spotify.com/track/24V30chf3YZQ2NhdT6K2JU', true, 'deep', array['film','title','year','artist']::text[]),
  (197, 'Song 197', 'Enjoy It!', 'In Search of the Castaways', 1962, 'Maurice Chevalier, Hayley Mills', 'https://open.spotify.com/track/4qPeTt9TjJPb2mZ9jvtYSC', true, 'deep', array['film','title','year','artist']::text[]),
  (198, 'Song 198', 'Give a Little Whistle', 'Pinocchio', 1940, 'Cliff Edwards, Dickie Jones', 'https://open.spotify.com/track/7KjviLuYXOGgK2TiyxJFQA', true, 'familiar', array['film','title','year','artist']::text[]),
  (199, 'Song 199', 'Sing Sweet Nightingale', 'Cinderella', 1950, 'Ilene Woods', 'https://open.spotify.com/track/3juY6Hy2uRCs5R8EaRxfQZ', true, 'familiar', array['film','title','year','artist']::text[]),
  (200, 'Song 200', 'I Wonder', 'Sleeping Beauty', 1959, 'Mary Costa', 'https://open.spotify.com/track/3BbRu8weo3dhszKcdxKhmZ', true, 'familiar', array['film','title','year','artist']::text[]),
  (201, 'Song 201', 'Steal the Show', 'Elemental', 2023, 'Lauv', 'https://open.spotify.com/track/0SccFtYdj75y6lL2OW10Cf', true, 'familiar', array['film','title','year','artist']::text[]),
  (202, 'Song 202', 'Married Life', 'Up', 2009, 'Michael Giacchino', 'https://open.spotify.com/track/7iocNjLrxPHLl8njgRlv5U', true, 'score', array['film']::text[]),
  (203, 'Song 203', 'Elemental', 'Elemental', 2023, 'Thomas Newman', 'https://open.spotify.com/track/1iueGRdZSh7qdbOsdWe7tC', true, 'score', array['film']::text[]),
  (204, 'Song 204', 'Carl Goes Up', 'Up', 2009, 'Michael Giacchino', 'https://open.spotify.com/track/42ZSOGIZ8AuQBFgyyicone', true, 'score', array['film']::text[]),
  (205, 'Song 205', 'Stuff We Did', 'Up', 2009, 'Michael Giacchino', 'https://open.spotify.com/track/19blFYzqmPj7FtW7W4DFEl', true, 'score', array['film']::text[]),
  (206, 'Song 206', 'Main Street Electrical Parade', 'Disneyland Park', 1972, 'Don Dorsey', 'https://open.spotify.com/track/3BaE6wK2Sj5iyxtwRROlkK', true, 'score', array['film']::text[]),
  (207, 'Song 207', 'Soarin''', 'Disney California Adventure', 2001, 'Jerry Goldsmith', 'https://open.spotify.com/track/10n8QgSpFaTQDwpy73YCfC', true, 'score', array['film']::text[]),
  (208, 'Song 208', 'Space Mountain', 'Disneyland Park', 2005, 'Michael Giacchino', 'https://open.spotify.com/track/0QkQTr2snSjUVjnHkHzdIo', true, 'score', array['film']::text[]),
  (209, 'Song 209', 'California Screamin''', 'Disney California Adventure', 2001, 'Gary Hoey, George Wilkins', 'https://open.spotify.com/track/7H2qQ7bU8uPZziCBoR4voa', true, 'score', array['film']::text[]),
  (210, 'Song 210', 'Here Comes Elastigirl', 'Incredibles 2', 2018, 'Michael Giacchino', 'https://open.spotify.com/track/0mL1awDtKnXGZUVE2ijGIc', true, 'score', array['film']::text[]),
  (211, 'Song 211', 'Pow! Pow! Pow! - Mr. Incredible''s Theme', 'Incredibles 2', 2018, 'Michael Giacchino', 'https://open.spotify.com/track/7kyoJDOSu5qz5UgzHSdUyr', true, 'score', array['film']::text[]),
  (212, 'Song 212', 'Turning Red', 'Turning Red', 2022, 'Ludwig Göransson', 'https://open.spotify.com/track/14WCShU6Yz3a0xXVRaFkze', true, 'score', array['film']::text[]),
  (213, 'Song 213', 'Meet Luca', 'Luca', 2021, 'Dan Romer', 'https://open.spotify.com/track/0Dpbz2JbQcECzhED9Mh5v1', true, 'score', array['film']::text[]),
  (214, 'Song 214', 'It''s Tough to Be a Bug', 'Disney''s Animal Kingdom', 1998, 'George Wilkins, Kevin Rafferty', 'https://open.spotify.com/track/7pDwsbaKgXOi7RqBONfdoI', true, 'familiar', array['film','title','year','artist']::text[]),
  (215, 'Song 215', 'There''s a Great Big Beautiful Tomorrow', 'Walt Disney''s Carousel of Progress', 1964, 'Rex Allen', 'https://open.spotify.com/track/3rynFprrGTQdpYzdzdUGsj', true, 'familiar', array['film','title','year','artist']::text[]),
  (216, 'Song 216', 'Beyond (End Credit Version)', 'Moana 2', 2024, 'Auli''i Cravalho', 'https://open.spotify.com/track/3fzqWttckvSJS7KPGPiWAg', true, 'familiar', array['film','title','year','artist']::text[]),
  (217, 'Song 217', 'It''s Not Easy', 'Pete''s Dragon', 1977, 'Helen Reddy, Sean Marshall', 'https://open.spotify.com/track/05ZwvpRTSpE2fxnexxDIRq', true, 'familiar', array['film','title','year','artist']::text[]),
  (218, 'Song 218', 'Seize the Day', 'Newsies', 1992, 'David Moscow, Newsies Original Cast', 'https://open.spotify.com/track/1D14PtAZlLWiBvxqngjrYp', true, 'familiar', array['film','title','year','artist']::text[]),
  (219, 'Song 219', 'After Today', 'A Goofy Movie', 1995, 'Aaron Lohr, Chorus', 'https://open.spotify.com/track/79oesFYaS2VT39ShdA19u9', true, 'familiar', array['film','title','year','artist']::text[]),
  (220, 'Song 220', 'Aloha, E Komo Mai', 'Lilo & Stitch: The Series', 2003, 'Jump5', 'https://open.spotify.com/track/5JVcDjjtezbvIWdb4ZTG4p', true, 'familiar', array['film','title','year','artist']::text[]),
  (221, 'Song 221', 'Burning Love', 'Lilo & Stitch', 2002, 'Wynonna', 'https://open.spotify.com/track/7tg6qrdwIo0qKL5tgNWYh0', true, 'familiar', array['film','title','year','artist']::text[]),
  (222, 'Song 222', 'All in the Golden Afternoon', 'Alice in Wonderland', 1951, 'Kathryn Beaumont, Chorus', 'https://open.spotify.com/track/047tBni5kKhs4Eqo38HZWa', true, 'familiar', array['film','title','year','artist']::text[]),
  (223, 'Song 223', 'The Great Outdoors', 'Country Bear Vacation Hoedown', 1986, 'The Disney Chorus', 'https://open.spotify.com/track/2GmqDJBmQt9wNpz3RjYNOy', true, 'familiar', array['film','title','year','artist']::text[]),
  (224, 'Song 224', 'Nobody Else But You', 'A Goofy Movie', 1995, 'Bill Farmer, Aaron Lohr', 'https://open.spotify.com/track/7MHR84KUjQfp2OTJA4B2Dg', true, 'familiar', array['film','title','year','artist']::text[]),
  (225, 'Song 225', 'Lavender Blue (Dilly Dilly)', 'So Dear to My Heart', 1948, 'Burl Ives', 'https://open.spotify.com/track/1VO400MnY5LKHNI1fiF01B', true, 'familiar', array['film','title','year','artist']::text[]),
  (226, 'Song 226', 'The Triple R Song', 'The Adventures of Spin and Marty', 1955, 'Tim Considine, David Stollery', 'https://open.spotify.com/track/7hkOxqCoRTDZ6HAN2wMBZk', true, 'familiar', array['film','title','year','artist']::text[]),
  (227, 'Song 227', 'Get''cha Head in the Game', 'High School Musical', 2006, 'Troy, Disney', 'https://open.spotify.com/track/3sT37kCEpxM1zQ8s98i7ps', true, 'familiar', array['film','title','year','artist']::text[]),
  (228, 'Song 228', 'Someone''s Waiting for You', 'The Rescuers', 1977, 'Shelby Flint', 'https://open.spotify.com/track/20GJ94KHYugkULE81t7t4e', true, 'familiar', array['film','title','year','artist']::text[]),
  (229, 'Song 229', 'Universe of Energy', 'EPCOT', 1982, 'The Disney Chorus', 'https://open.spotify.com/track/1P9q3hhI8hGyc1Gc2L0Z7R', true, 'familiar', array['film','title','year','artist']::text[]),
  (230, 'Song 230', 'La La Lu', 'Lady and the Tramp', 1955, 'Peggy Lee', 'https://open.spotify.com/track/3Fou4O94pyR80OxdSj3pI8', true, 'familiar', array['film','title','year','artist']::text[]),
  (231, 'Song 231', 'Happy Working Song', 'Enchanted', 2007, 'Amy Adams', 'https://open.spotify.com/track/6oNKXDX7bpzkXohQdd0MLc', true, 'familiar', array['film','title','year','artist']::text[]),
  (232, 'Song 232', 'The Three Caballeros', 'The Three Caballeros', 1944, 'Joaquin Garay, Clarence Nash, José Oliveira', 'https://open.spotify.com/track/2RMsksGwk6UUnts8xzDhDO', true, 'familiar', array['film','title','year','artist']::text[]),
  (233, 'Song 233', 'The Best Time of Your Life', 'Walt Disney World', 1975, 'The Disney Chorus', 'https://open.spotify.com/track/4xckPeXypWr7q810K9T50L', true, 'familiar', array['film','title','year','artist']::text[]),
  (234, 'Song 234', 'One Little Spark', 'EPCOT', 1983, 'Chuck McCann, Billy Barty', 'https://open.spotify.com/track/3N9AhvVYdBneTR8905wB3O', true, 'familiar', array['film','title','year','artist']::text[]),
  (235, 'Song 235', 'DuckTales Theme', 'DuckTales', 1987, 'Jeff Pescetto', 'https://open.spotify.com/track/5pRpPmMdvAM0sHInhqRZXl', true, 'familiar', array['film','title','year','artist']::text[]),
  (236, 'Song 236', 'One Little Slip', 'Chicken Little', 2005, 'Barenaked Ladies', 'https://open.spotify.com/track/4LjOKmZbfhx2uOEQopXgcn', true, 'familiar', array['film','title','year','artist']::text[]),
  (237, 'Song 237', 'Rockin'' at the House of Mouse', 'House of Mouse', 2001, 'Brian Setzer', 'https://open.spotify.com/track/29qxC3821fP6CvORXxRmZR', true, 'familiar', array['film','title','year','artist']::text[]),
  (238, 'Song 238', 'Mickey Mouse Club Alma Mater', 'The Mickey Mouse Club', 1955, 'The Mouseketeers', 'https://open.spotify.com/track/0qxhucKlrket7p5dw37cpQ', true, 'familiar', array['film','title','year','artist']::text[]),
  (239, 'Song 239', 'Yo Ho (A Pirate''s Life for Me)', 'Pirates of the Caribbean', 1967, 'The Disney Chorus', 'https://open.spotify.com/track/0oa7hUynHu9czqX8ZjP2LW', true, 'familiar', array['film','title','year','artist']::text[]),
  (240, 'Song 240', 'The Monkey''s Uncle', 'The Monkey''s Uncle', 1965, 'Annette Funicello, The Beach Boys', 'https://open.spotify.com/track/75fi0OeQnaAAdCtC8Ob9rP', true, 'familiar', array['film','title','year','artist']::text[]),
  (241, 'Song 241', 'Fortuosity', 'The Happiest Millionaire', 1967, 'Tommy Steele', 'https://open.spotify.com/track/2hwh9Ezfef2NoBjiKyN8Sa', true, 'familiar', array['film','title','year','artist']::text[]),
  (242, 'Song 242', 'Naked Mole Rap', 'Kim Possible', 2003, 'Will Friedle, Nancy Cartwright', 'https://open.spotify.com/track/6KM0MhU7zuyzfRo470A86y', true, 'familiar', array['film','title','year','artist']::text[]),
  (243, 'Song 243', 'Theme from Zorro', 'Zorro', 1957, 'The Mellomen', 'https://open.spotify.com/track/1UIZRPq7OrgXucrLLXNTJq', true, 'familiar', array['film','title','year','artist']::text[]),
  (244, 'Song 244', 'The Scarecrow of Romney Marsh', 'The Scarecrow of Romney Marsh', 1964, 'The Disney Chorus', 'https://open.spotify.com/track/28UmfrnhJRxgsXqZrThXSN', true, 'familiar', array['film','title','year','artist']::text[]),
  (245, 'Song 245', 'Whoop-De-Dooper Bounce', 'The Tigger Movie', 2000, 'Jim Cummings', 'https://open.spotify.com/track/0CiYP8bUGpKhtbk5kYPWFB', true, 'familiar', array['film','title','year','artist']::text[]),
  (246, 'Song 246', 'Kitchen Kabaret', 'EPCOT', 1982, 'The Kitchen Krackpots', 'https://open.spotify.com/track/3sjSfBczoaurEZKFY4P54K', true, 'familiar', array['film','title','year','artist']::text[]),
  (247, 'Song 247', 'Darkwing Duck Theme', 'Darkwing Duck', 1991, 'Jeff Pescetto', 'https://open.spotify.com/track/2C50wOYaIRgenhIQZhgXXb', true, 'familiar', array['film','title','year','artist']::text[]),
  (248, 'Song 248', 'This Is Me', 'Camp Rock', 2008, 'Demi Lovato, Joe Jonas', 'https://open.spotify.com/track/0hCQZfphHl18vUhh0hB41f', true, 'familiar', array['film','title','year','artist']::text[]),
  (249, 'Song 249', 'The Time of Your Life', 'A Bug''s Life', 1998, 'Randy Newman', 'https://open.spotify.com/track/33GqT5sh9PQq8mnTPWUkco', true, 'familiar', array['film','title','year','artist']::text[]),
  (250, 'Song 250', 'Gitchee Gitchee Goo', 'Phineas and Ferb', 2008, 'Phineas and the Ferb-Tones', 'https://open.spotify.com/track/1ujI34NkQGLxiWxeLG7uNf', true, 'familiar', array['film','title','year','artist']::text[]),
  (251, 'Song 251', 'Look Through My Eyes', 'Brother Bear', 2003, 'Phil Collins', 'https://open.spotify.com/track/400abutrj9yS5YBkd3fE6P', true, 'familiar', array['film','title','year','artist']::text[]),
  (252, 'Song 252', 'Gummi Bears Theme', 'Disney''s Adventures of the Gummi Bears', 1985, 'Joseph Williams', 'https://open.spotify.com/track/6NosySWwM5j7uttw3olHDx', true, 'familiar', array['film','title','year','artist']::text[]),
  (253, 'Song 253', 'Cheetah Sisters', 'The Cheetah Girls', 2003, 'The Cheetah Girls', 'https://open.spotify.com/track/3WjbOhfEyBp4lvEf06jGRJ', true, 'familiar', array['film','title','year','artist']::text[]),
  (254, 'Song 254', 'Everything Is Not as It Seems', 'Wizards of Waverly Place', 2007, 'Selena Gomez', 'https://open.spotify.com/track/5U4wYRHrCRxRP6iQfM824C', true, 'familiar', array['film','title','year','artist']::text[]),
  (255, 'Song 255', 'Grim Grinning Ghosts', 'The Haunted Mansion', 1969, 'The Mellomen', 'https://open.spotify.com/track/2h33XtB73wPV6WTBNjaUpE', true, 'familiar', array['film','title','year','artist']::text[]),
  (256, 'Song 256', 'Although I Dropped $100,000 in the Market, Baby', 'A Symposium on Popular Songs', 1962, 'Paul Frees', 'https://open.spotify.com/track/48gG47vhhKVHBaxU69YtTp', true, 'familiar', array['film','title','year','artist']::text[]),
  (257, 'Song 257', 'Looking for Romance (I Bring You a Song)', 'Bambi', 1942, 'Donald Novis, Chorus', 'https://open.spotify.com/track/4a4nAiIKUPxCZXh5q9U2OC', true, 'familiar', array['film','title','year','artist']::text[]),
  (258, 'Song 258', 'Baby Mine', 'Dumbo', 1941, 'Betty Noyes', 'https://open.spotify.com/track/3Xna0BKUMMP7MNChdnoEwp', true, 'familiar', array['film','title','year','artist']::text[]),
  (259, 'Song 259', 'It''s All Right', 'Soul', 2020, 'Jon Batiste', 'https://open.spotify.com/track/4gzwK4RdSK9M43vPY68J2Y', true, 'familiar', array['film','title','year','artist']::text[]),
  (260, 'Song 260', 'Carried Me With You', 'Onward', 2020, 'Brandi Carlile', 'https://open.spotify.com/track/0HL3y3bsKSARBSP0qaImwb', true, 'familiar', array['film','title','year','artist']::text[]),
  (261, 'Song 261', 'Lead the Way', 'Raya and the Last Dragon', 2021, 'Jhené Aiko', 'https://open.spotify.com/track/2Vqbniz8jYoZPvecpdVPq9', true, 'familiar', array['film','title','year','artist']::text[]),
  (262, 'Song 262', 'Colombia, Mi Encanto', 'Encanto', 2021, 'Carlos Vives', 'https://open.spotify.com/track/2Q5q1q01KOdHt5fM00WUJ8', true, 'familiar', array['film','title','year','artist']::text[]),
  (263, 'Song 263', 'Such a Beautiful Day', 'Phineas and Ferb the Movie: Candace Against the Universe', 2020, 'Robbie Wyckoff', 'https://open.spotify.com/track/6c0uCLxpu895L5uEsgB2pw', true, 'familiar', array['film','title','year','artist']::text[]),
  (264, 'Song 264', 'The Next Right Thing', 'Frozen II', 2019, 'Kristen Bell', 'https://open.spotify.com/track/1gilgPrTkkZTp09Xf8zCmK', true, 'familiar', array['film','title','year','artist']::text[]),
  (265, 'Song 265', 'Dos Oruguitas', 'Encanto', 2021, 'Sebastián Yatra', 'https://open.spotify.com/track/5rohUzwEoRsUvAA1Bf3DLo', true, 'familiar', array['film','title','year','artist']::text[]),
  (266, 'Song 266', 'Parting Ways', 'Soul', 2020, 'Cody Chesnutt', 'https://open.spotify.com/track/7oYOgl26e4KPofzPKJhFxJ', true, 'familiar', array['film','title','year','artist']::text[]),
  (267, 'Song 267', 'I Can''t Let You Throw Yourself Away', 'Toy Story 4', 2019, 'Randy Newman', 'https://open.spotify.com/track/7tSODhfDkv0JEhkSMYSIBS', true, 'familiar', array['film','title','year','artist']::text[]),
  (268, 'Song 268', 'The Ballad of the Lonesome Cowboy', 'Toy Story 4', 2019, 'Chris Stapleton', 'https://open.spotify.com/track/3a24rUSZ1Ui3xmPNnqpor8', true, 'familiar', array['film','title','year','artist']::text[]),
  (269, 'Song 269', 'Reindeer(s) Are Better Than People (Cont.)', 'Frozen II', 2019, 'Jonathan Groff', 'https://open.spotify.com/track/1AHAYbZklQkUj7wgxhQPIo', true, 'familiar', array['film','title','year','artist']::text[]),
  (270, 'Song 270', 'When I Am Older', 'Frozen II', 2019, 'Josh Gad', 'https://open.spotify.com/track/1Tt7zr1yDbKbT8L4jzSZ74', true, 'familiar', array['film','title','year','artist']::text[]),
  (271, 'Song 271', 'I Am Moana (Song of the Ancestors)', 'Moana', 2016, 'Auli''i Cravalho, Rachel House', 'https://open.spotify.com/track/6uk7QQiWRDjPHSiSMZlez8', true, 'familiar', array['film','title','year','artist']::text[]),
  (272, 'Song 272', 'La Llorona', 'Coco', 2017, 'Alanna Ubach, Antonio Sol', 'https://open.spotify.com/track/5fBcRH4CnYTaFMQtM0JtSl', true, 'familiar', array['film','title','year','artist']::text[]),
  (273, 'Song 273', 'Good to Be Bad', 'Descendants 3', 2019, 'Dove Cameron, Sofia Carson, Booboo Stewart, Cameron Boyce, Jadah Marie, Anna Cathcart', 'https://open.spotify.com/track/1RIYF8NDIIWBvJe4vhQr6y', true, 'familiar', array['film','title','year','artist']::text[]),
  (274, 'Song 274', 'Introducing Me', 'Camp Rock 2: The Final Jam', 2010, 'Nick Jonas', 'https://open.spotify.com/track/74tQaH4CxM5Rs9BzerEbHr', true, 'familiar', array['film','title','year','artist']::text[]),
  (275, 'Song 275', 'Wouldn''t Change a Thing', 'Camp Rock 2: The Final Jam', 2010, 'Demi Lovato, Joe Jonas', 'https://open.spotify.com/track/0Di5p4ItolIUZB8c2P0pvs', true, 'familiar', array['film','title','year','artist']::text[]),
  (276, 'Song 276', 'She''s So Gone', 'Lemonade Mouth', 2011, 'Naomi Scott', 'https://open.spotify.com/track/4DTrKnvkHtwQN6kBu4XXIF', true, 'familiar', array['film','title','year','artist']::text[]),
  (277, 'Song 277', 'Queen of Mean', 'Descendants 3', 2019, 'Sarah Jeffery', 'https://open.spotify.com/track/4o05DiC0RQ9DNtGJGauwna', true, 'familiar', array['film','title','year','artist']::text[]),
  (278, 'Song 278', 'What''s My Name', 'Descendants 2', 2017, 'China Anne McClain, Thomas Doherty, Dylan Playfair', 'https://open.spotify.com/track/53xAT6jud1w0NqlBjSW4VB', true, 'familiar', array['film','title','year','artist']::text[]),
  (279, 'Song 279', 'Breaking Free', 'High School Musical', 2006, 'Troy, Gabriella', 'https://open.spotify.com/track/5zQ1Wq6HNYjGZWkVv5P8Eg', true, 'familiar', array['film','title','year','artist']::text[]),
  (280, 'Song 280', 'Chillin'' Like a Villain', 'Descendants 2', 2017, 'Sofia Carson, Cameron Boyce, Booboo Stewart, Mitchell Hope', 'https://open.spotify.com/track/1rM0CnyUiiw6A9CHJRXjZA', true, 'familiar', array['film','title','year','artist']::text[]),
  (281, 'Song 281', 'Determinate', 'Lemonade Mouth', 2011, 'Adam Hicks, Bridgit Mendler, Naomi Scott, Hayley Kiyoko', 'https://open.spotify.com/track/4qEoqyPbLYnLOii6mKlIjI', true, 'familiar', array['film','title','year','artist']::text[]),
  (282, 'Song 282', 'Ways to Be Wicked', 'Descendants 2', 2017, 'Dove Cameron, Sofia Carson, Cameron Boyce, Booboo Stewart', 'https://open.spotify.com/track/2ziVTVizQdVNC2QhQhNGvg', true, 'familiar', array['film','title','year','artist']::text[]),
  (283, 'Song 283', 'If Only', 'Descendants', 2015, 'Dove Cameron', 'https://open.spotify.com/track/1mRBJdpIgc3jZH8C3cN2WV', true, 'familiar', array['film','title','year','artist']::text[]),
  (284, 'Song 284', 'Set It Off', 'Descendants', 2015, 'Dove Cameron, Sofia Carson, Cameron Boyce, Booboo Stewart, Mitchell Hope', 'https://open.spotify.com/track/7I80zTBTDNnbOiJQ0JLjZr', true, 'familiar', array['film','title','year','artist']::text[]),
  (285, 'Song 285', 'Rotten to the Core', 'Descendants', 2015, 'Dove Cameron, Cameron Boyce, Booboo Stewart, Sofia Carson', 'https://open.spotify.com/track/2bNxCVI4Fub8BAwr0CQDyd', true, 'familiar', array['film','title','year','artist']::text[]),
  (286, 'Song 286', 'Someday', 'ZOMBIES', 2018, 'Milo Manheim, Meg Donnelly', 'https://open.spotify.com/track/2d1AiZExnhYoauaSWkB1Fm', true, 'familiar', array['film','title','year','artist']::text[]),
  (287, 'Song 287', 'BAMM', 'ZOMBIES', 2018, 'Milo Manheim, Meg Donnelly, Kylee Russell', 'https://open.spotify.com/track/1bFY36a62kXGJqNcN5aJkW', true, 'familiar', array['film','title','year','artist']::text[]),
  (288, 'Song 288', 'My Year', 'ZOMBIES', 2018, 'ZOMBIES Cast', 'https://open.spotify.com/track/77NgPW9Bt7QPU69YsYpiKV', true, 'familiar', array['film','title','year','artist']::text[]),
  (289, 'Song 289', 'The Best of Both Worlds', 'Hannah Montana', 2006, 'Hannah Montana', 'https://open.spotify.com/track/6Z0F3Mqj7tq1CBZo5qMlUg', true, 'familiar', array['film','title','year','artist']::text[]),
  (290, 'Song 290', 'Fabulous', 'High School Musical 2', 2007, 'Ashley Tisdale, Lucas Grabeel', 'https://open.spotify.com/track/6jyXQ8HGI7ikECGA0670uo', true, 'familiar', array['film','title','year','artist']::text[]),
  (291, 'Song 291', 'Strut', 'The Cheetah Girls 2', 2006, 'The Cheetah Girls', 'https://open.spotify.com/track/1g1Jor1zrllXn2ogj8KGAH', true, 'familiar', array['film','title','year','artist']::text[]),
  (292, 'Song 292', 'This Is Our Song', 'Camp Rock 2: The Final Jam', 2010, 'Demi Lovato, Joe Jonas, Nick Jonas, Alyson Stoner', 'https://open.spotify.com/track/6SyPnh5ysbRjmZHIlOKp4r', true, 'familiar', array['film','title','year','artist']::text[]),
  (293, 'Song 293', 'Gotta Find You', 'Camp Rock', 2008, 'Joe Jonas', 'https://open.spotify.com/track/2oOCYaGkOpOB5HPo15cEGl', true, 'familiar', array['film','title','year','artist']::text[]),
  (294, 'Song 294', 'The Party''s Just Begun', 'The Cheetah Girls 2', 2006, 'The Cheetah Girls', 'https://open.spotify.com/track/5Au8ObNQvrwFVEgGqQQL6D', true, 'familiar', array['film','title','year','artist']::text[]),
  (295, 'Song 295', 'Nobody Like U', 'Turning Red', 2022, '4*TOWN', 'https://open.spotify.com/track/4bV5sf2B4hWBBd5HQ8S7KB', true, 'familiar', array['film','title','year','artist']::text[]),
  (296, 'Song 296', '1 True Love', 'Turning Red', 2022, '4*TOWN', 'https://open.spotify.com/track/2dJ1UJEQQq3jkLSJP4ZIoi', true, 'familiar', array['film','title','year','artist']::text[]),
  (297, 'Song 297', 'U Know What''s Up', 'Turning Red', 2022, '4*TOWN', 'https://open.spotify.com/track/0d83zVs3OmdjrhfoAxg1dE', true, 'familiar', array['film','title','year','artist']::text[]),
  (298, 'Song 298', 'U Know What''s Up - The Panda Hustle Version', 'Turning Red', 2022, '4*TOWN', 'https://open.spotify.com/track/6Xi7ye58IILUXhxcOyibUj', true, 'familiar', array['film','title','year','artist']::text[]),
  (299, 'Song 299', 'Pandas Unite / Nobody Like U (Reprise)', 'Turning Red', 2022, 'Ludwig Göransson, 4*TOWN, Turning Red Cast', 'https://open.spotify.com/track/4dksoaJqf0k9mwrvAuUcqR', true, 'familiar', array['film','title','year','artist']::text[]),
  (300, 'Song 300', 'Born to Play', 'Soul', 2020, 'Jon Batiste', 'https://open.spotify.com/track/4BmuAIPAsCiS2NhqT0gSfL', true, 'familiar', array['film','title','year','artist']::text[])
)
insert into public.dmq_songs (song_number,label,title,film,year,artist,spotify_url,enabled,question_profile,allowed_questions)
select * from new_songs
on conflict (song_number) do update set label=excluded.label,title=excluded.title,film=excluded.film,year=excluded.year,artist=excluded.artist,spotify_url=excluded.spotify_url,enabled=excluded.enabled,question_profile=excluded.question_profile,allowed_questions=excluded.allowed_questions,updated_at=now();

update public.dmq_songs set question_profile='iconic' where song_number between 1 and 150 and song_number in (1,2,3,4,5,6,9,10,11,12,15,16,17,20,21,22,25,26,30,31,40,43,47,48,96,97,100,101,102,103,104,107,108,110,113,115,119,122,126,127,130,132,134,135,143,144,147,148,149,150);
update public.dmq_songs set question_profile='deep' where song_number between 1 and 150 and question_profile<>'iconic' and song_number in (38,39,45,46,54,55,59,61,62,65,66,69,71,74,77,81,82,84,85,86,87,88,89,90,91,93,94,95,99,105,106,109,111,112,114,116,117,118,120,121,123,124,125,128,129,131,133,136,137,138,139,140,141,142,145,146);
update public.dmq_songs set question_profile='familiar' where song_number between 1 and 150 and question_profile not in ('iconic','deep');
update public.dmq_songs set question_profile='deep' where song_number in (101,103,109,113,116,129,130,131,132,133,134,135,137,139,140,144,145,146,147,148);
update public.dmq_songs set question_profile='familiar' where song_number in (102,107,108,110,114,115,117,126,127,128,136,143);
update public.dmq_songs set allowed_questions=array['film']::text[] where question_profile='score';
commit;

select count(*) as actieve_songs,count(*) filter (where question_profile='iconic') as iconisch,count(*) filter (where question_profile='familiar') as bekend,count(*) filter (where question_profile='deep') as moeilijk,count(*) filter (where question_profile='score') as instrumentaal from public.dmq_songs where enabled=true;
