-- Disney Music Quest v2.8 Song Expansion (101-150)
-- Voegt 50 extra iconische Disney-songs toe aan de database om de herspeelbaarheid te vergroten naar 150 nummers.

alter table public.dmq_songs drop constraint if exists dmq_songs_song_number_check;
alter table public.dmq_songs add constraint dmq_songs_song_number_check check (song_number between 1 and 150);

insert into public.dmq_songs
(song_number, label, title, film, year, artist, spotify_url, enabled)
values
(101, 'Song 101', 'We Don''t Talk About Bruno', 'Encanto', 2021, 'Carolina Gaitán, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz', 'https://open.spotify.com/track/52xJxFP6TqMuO4Yt0eOkMz', true),
(102, 'Song 102', 'Surface Pressure', 'Encanto', 2021, 'Jessica Darrow', 'https://open.spotify.com/track/760jhRscwGbIIe1m1IIQpU', true),
(103, 'Song 103', 'The Family Madrigal', 'Encanto', 2021, 'Stephanie Beatriz, Olga Merediz', 'https://open.spotify.com/track/4b1yxSdlumA8N4fEk4UOZp', true),
(104, 'Song 104', 'This Wish', 'Wish', 2023, 'Ariana DeBose', 'https://open.spotify.com/track/5DJgVGikMm9NKyJO2wvDF6', true),
(105, 'Song 105', 'Knowing What I Know Now', 'Wish', 2023, 'Wish Cast', 'https://open.spotify.com/track/7I1QMEyw5T3nddOBbvoT9u', true),
(106, 'Song 106', 'I''m a Star', 'Wish', 2023, 'Wish Cast', 'https://open.spotify.com/track/1XHc1VYAdV3iwLDpMbLNEy', true),
(107, 'Song 107', 'Un Poco Loco', 'Coco', 2017, 'Anthony Gonzalez, Gael García Bernal', 'https://open.spotify.com/track/0inaxid9CcJYsu9CdF0s4m', true),
(108, 'Song 108', 'Remember Me', 'Coco', 2017, 'Benjamin Bratt', 'https://open.spotify.com/track/6gF8tPWPRoPt2j4SZWOUXC', true),
(109, 'Song 109', 'Proud Corazón', 'Coco', 2017, 'Anthony Gonzalez', 'https://open.spotify.com/track/4xUzgBNEzJCVerZZLwRRSH', true),
(110, 'Song 110', 'Try Everything', 'Zootopia', 2016, 'Shakira', 'https://open.spotify.com/track/1N3dZ7TTWO6VcD4Y3hHYLZ', true),
(111, 'Song 111', 'Immortals', 'Big Hero 6', 2014, 'Fall Out Boy', 'https://open.spotify.com/track/3c1ItvzDDDpmDgLH9SIUp4', true),
(112, 'Song 112', 'Touch the Sky', 'Brave', 2012, 'Julie Fowlis', 'https://open.spotify.com/track/5yyqx4brn6Bm9U1Rj9ENnz', true),
(113, 'Song 113', 'When Will My Life Begin?', 'Tangled', 2010, 'Mandy Moore', 'https://open.spotify.com/track/03xWMkKEbeO4SnylA53ipj', true),
(114, 'Song 114', 'I''ve Got a Dream', 'Tangled', 2010, 'Tangled Cast', 'https://open.spotify.com/track/0TCt7OFRdD8PQ6vTRQxNgQ', true),
(115, 'Song 115', 'Almost There', 'The Princess and the Frog', 2009, 'Anika Noni Rose', 'https://open.spotify.com/track/2GLyruWagsv8o7aGNXboH1', true),
(116, 'Song 116', 'Friends on the Other Side', 'The Princess and the Frog', 2009, 'Keith David', 'https://open.spotify.com/track/14mNTV7rsvzkVfBmRepX1X', true),
(117, 'Song 117', 'Dig a Little Deeper', 'The Princess and the Frog', 2009, 'Jenifer Lewis', 'https://open.spotify.com/track/7kh64k3P9Fk4EsA6vOdwmj', true),
(118, 'Song 118', 'Real Gone', 'Cars', 2006, 'Sheryl Crow', 'https://open.spotify.com/track/40oaXWRJALmKVIryVTSgyI', true),
(119, 'Song 119', 'Life Is a Highway', 'Cars', 2006, 'Rascal Flatts', 'https://open.spotify.com/track/5cAr657iTXwdYnyT4alvsX', true),
(120, 'Song 120', 'Our Town', 'Cars', 2006, 'James Taylor', 'https://open.spotify.com/track/3xGDZyWQ8bICKb1NlN5fd2', true),
(121, 'Song 121', 'Beyond the Sea', 'Finding Nemo', 2003, 'Robbie Williams', 'https://open.spotify.com/track/73nQWdQVd6hLrW8MPTQpP7', true),
(122, 'Song 122', 'Hawaiian Roller Coaster Ride', 'Lilo & Stitch', 2002, 'Mark Keali''i Ho''omalu, Kamehameha Schools Children''s Chorus', 'https://open.spotify.com/track/6pO5svQbrKKLZS08tIiEUA', true),
(123, 'Song 123', 'He Mele No Lilo', 'Lilo & Stitch', 2002, 'Mark Keali''i Ho''omalu, Kamehameha Schools Children''s Chorus', 'https://open.spotify.com/track/45cku3eLTd5hObrNM8q8PA', true),
(124, 'Song 124', 'Where the Dream Takes You', 'Atlantis: The Lost Empire', 2001, 'Mya', 'https://open.spotify.com/track/6Uj1B88LmhTcYSvAVdAYum', true),
(125, 'Song 125', 'My Funny Friend and Me', 'The Emperor''s New Groove', 2000, 'Sting', 'https://open.spotify.com/track/3VNVHB1pa63RIokenb7EKt', true),
(126, 'Song 126', 'Strangers Like Me', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/3T74kgnbHw8JqkYGJKD4Tl', true),
(127, 'Song 127', 'Son of Man', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/1LhFadk0aWYczltTjIbFlI', true),
(128, 'Song 128', 'Two Worlds', 'Tarzan', 1999, 'Phil Collins', 'https://open.spotify.com/track/3icOFPIciIN8FQSyVlpYSF', true),
(129, 'Song 129', 'Reflection', 'Mulan', 1998, 'Lea Salonga', 'https://open.spotify.com/track/2AILbz83cBnrAMAG06rZts', true),
(130, 'Song 130', 'I''ll Make a Man Out of You', 'Mulan', 1998, 'Donny Osmond & Chorus - Mulan', 'https://open.spotify.com/track/40lNlmrek40tfBOiQzf6qK', true),
(131, 'Song 131', 'A Girl Worth Fighting For', 'Mulan', 1998, 'Mulan Cast', 'https://open.spotify.com/track/3wjgPeXocinhLyPL37p70e', true),
(132, 'Song 132', 'Go the Distance', 'Hercules', 1997, 'Roger Bart', 'https://open.spotify.com/track/0D1OY0M5A0qD5HGBvFmFid', true),
(133, 'Song 133', 'Zero to Hero', 'Hercules', 1997, 'Tawatha Agee, Lillias White, LaChanze', 'https://open.spotify.com/track/4zDfgax6Ihb0UWdour1ZEs', true),
(134, 'Song 134', 'I Won''t Say (I''m in Love)', 'Hercules', 1997, 'Susan Egan', 'https://open.spotify.com/track/0PKmDncVOiNQLO6D1P6PXi', true),
(135, 'Song 135', 'Colors of the Wind', 'Pocahontas', 1995, 'Judy Kuhn', 'https://open.spotify.com/track/1O841LULHXexH8W7fqtctA', true),
(136, 'Song 136', 'Just Around the Riverbend', 'Pocahontas', 1995, 'Judy Kuhn', 'https://open.spotify.com/track/3SZXvtZabmTK2oRmdSjfBO', true),
(137, 'Song 137', 'Savages', 'Pocahontas', 1995, 'Pocahontas Cast', 'https://open.spotify.com/track/5KLCfUQh7sgWek4C0lbmvs', true),
(138, 'Song 138', 'God Help the Outcasts', 'The Hunchback of Notre Dame', 1996, 'Heidi Mollenhauer', 'https://open.spotify.com/track/67KymXb4OUQtUlO31EFOjS', true),
(139, 'Song 139', 'Out There', 'The Hunchback of Notre Dame', 1996, 'Tom Hulce, Tony Jay', 'https://open.spotify.com/track/7cX2nwvVfWW3bfScg2f15K', true),
(140, 'Song 140', 'Hellfire', 'The Hunchback of Notre Dame', 1996, 'Tony Jay', 'https://open.spotify.com/track/4rp9YObc6Q5xc6X1S8c7m9', true),
(141, 'Song 141', 'What''s This?', 'The Nightmare Before Christmas', 1993, 'Danny Elfman', 'https://open.spotify.com/track/7rRT1F75dJjTIu4fZp3eXx', true),
(142, 'Song 142', 'This Is Halloween', 'The Nightmare Before Christmas', 1993, 'Citizens of Halloween', 'https://open.spotify.com/track/0yURuYmnz9tl4K04e5Y6aQ', true),
(143, 'Song 143', 'Beauty and the Beast', 'Beauty and the Beast', 1991, 'Angela Lansbury', 'https://open.spotify.com/track/2xS0Aybg4e8cQ8xiv3DeoH', true),
(144, 'Song 144', 'Belle', 'Beauty and the Beast', 1991, 'Paige O''Hara, Richard White', 'https://open.spotify.com/track/4FrfQdZaZnudSHPwgliazB', true),
(145, 'Song 145', 'Gaston', 'Beauty and the Beast', 1991, 'Jesse Corti, Richard White', 'https://open.spotify.com/track/64lQ4g5QiFNDC7gTUCe3DY', true),
(146, 'Song 146', 'Cruella De Vil', '101 Dalmatians', 1961, 'Bill Lee', 'https://open.spotify.com/track/4VF8YWqMsY3Y1UcKJBg5XO', true),
(147, 'Song 147', 'The Bare Necessities', 'The Jungle Book', 1967, 'Phil Harris, Bruce Reitherman', 'https://open.spotify.com/track/0fzcz7acLp523Dyrd43Sm3', true),
(148, 'Song 148', 'I Wan''na Be Like You', 'The Jungle Book', 1967, 'Louis Prima, Phil Harris', 'https://open.spotify.com/track/517vxmOFgKFJvuucKuUdar', true),
(149, 'Song 149', 'A Spoonful of Sugar', 'Mary Poppins', 1964, 'Julie Andrews', 'https://open.spotify.com/track/5J554vlWIKAZMlAnsrBpRQ', true),
(150, 'Song 150', 'Supercalifragilisticexpialidocious', 'Mary Poppins', 1964, 'Julie Andrews, Dick Van Dyke', 'https://open.spotify.com/track/7fImDWw5bcUhRbZ0w1ny4J', true);
