// Curated expansion for Road Race. Factual records keep their source URL so
// future edits can be audited without relying on memory or generated claims.
export const CONTENT_SOURCES = Object.freeze({
  dlpHistory: 'https://news.disneylandparis.com/en/history/',
  dlpFacts: 'https://news.disneylandparis.com/app/uploads/2025/08/DLP-Fact-Sheet_FY25-Q3_EN.pdf',
  dlpFun: 'https://disneyparksblog.com/disney-experiences/10-fun-facts-in-celebration-of-disneyland-paris-30th-anniversary/',
  castleFacts: 'https://disneyparksblog.com/disney-experiences/disney-castles-hidden-details/',
  dlpCastle: 'https://www.disneylandparis.com/en-int/attractions/disneyland-park/sleeping-beauty-castle',
  towerFacts: 'https://disneyparksblog.com/wdw/20-facts-for-the-twilight-zone-tower-of-terrors-20th-anniversary/',
  rockFacts: 'https://disneyparksblog.com/wdw/rock-n-roller-coaster-starring-aerosmith-turns-15-at-walt-disney-world-resort/',
  animalFacts: 'https://disneyparksblog.com/ase/wild-stats-about-disney-conservation-animal-care/',
  disneyHistory: 'https://d23.com/a-to-z/',
  disneyMovies: 'https://movies.disney.com/',
  pixarFilms: 'https://www.pixar.com/feature-films',
  disneylandHistory: 'https://disneyland.disney.go.com/faq/parks/when-did-disneyland-open/',
  wdwHistory: 'https://disneyworld.disney.go.com/experience-updates/parks/',
  tokyoHistory: 'https://www.tokyodisneyresort.jp/en/tdr/resort/walt.html',
  hongKongHistory: 'https://news.hongkongdisneyland.com/en/press/fact-sheets/',
  shanghaiHistory: 'https://www.shanghaidisneyresort.com/en/about',
});

const NEWS = (text, source) => ({ text: `Magisch Nieuws: ${text}`, source });

export const VERIFIED_MAGIC_NEWS_RECORDS = [
  NEWS('Disneyland Paris opende officieel op 12 april 1992.', CONTENT_SOURCES.dlpHistory),
  NEWS('De overeenkomst die de basis legde voor Disneyland Paris werd op 24 maart 1987 ondertekend.', CONTENT_SOURCES.dlpHistory),
  NEWS('De bouw van het resort begon in 1988 in Marne-la-Vallée.', CONTENT_SOURCES.dlpHistory),
  NEWS('Het RER-station Marne-la-Vallée–Chessy ging al op 1 april 1992 open, elf dagen vóór het park.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disneyland Paris ligt ongeveer 32 kilometer ten oosten van Parijs.', CONTENT_SOURCES.dlpFacts),
  NEWS('Disneyland Park beslaat volgens het officiële factsheet ongeveer 124 acres.', CONTENT_SOURCES.dlpFacts),
  NEWS('Disneyland Park heeft vijf themalanden: Main Street, U.S.A., Frontierland, Adventureland, Fantasyland en Discoveryland.', CONTENT_SOURCES.dlpFacts),
  NEWS('Het tweede park van Disneyland Paris opende op 16 maart 2002.', CONTENT_SOURCES.dlpHistory),
  NEWS('Het tweede park was bij de opening gericht op de magie en geheimen van filmproductie.', CONTENT_SOURCES.dlpHistory),
  NEWS('De TGV-station van Marne-la-Vallée–Chessy opende op 26 mei 1994.', CONTENT_SOURCES.dlpHistory),
  NEWS('Bij de opening van het TGV-station reed een papieren trein van 300 meter over Main Street, U.S.A.', CONTENT_SOURCES.dlpHistory),
  NEWS('Indiana Jones et le Temple du Péril opende in 1993.', CONTENT_SOURCES.dlpHistory),
  NEWS('De eerste Parijse versie van Space Mountain opende in 1995 als From the Earth to the Moon.', CONTENT_SOURCES.dlpHistory),
  NEWS('Space Mountain: Mission 2 werd in 2005 ingewijd.', CONTENT_SOURCES.dlpHistory),
  NEWS('Buzz Lightyear Laser Blast opende in Disneyland Paris in 2006.', CONTENT_SOURCES.dlpHistory),
  NEWS('The Twilight Zone Tower of Terror opende in het Parijse tweede park in 2008.', CONTENT_SOURCES.dlpHistory),
  NEWS('Toy Story Playland opende in 2010 en was het eerste volledig aan Toy Story gewijde land in een Disneypark.', CONTENT_SOURCES.dlpHistory),
  NEWS('Place de Rémy, met de Ratatouille-attractie en Bistrot Chez Rémy, opende in 2014.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disneyland Paris begon in 2015 aan een groots renovatieprogramma voor klassieke attracties.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disneyland Paris vierde in 2017 zijn 25-jarig bestaan.', CONTENT_SOURCES.dlpHistory),
  NEWS('In 2018 werd een meerjarig investeringsplan van twee miljard euro aangekondigd.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disney Hotel New York heropende in 2021 als The Art of Marvel.', CONTENT_SOURCES.dlpHistory),
  NEWS('In Disney Hotel New York – The Art of Marvel zijn meer dan 350 Marvel-kunstwerken te zien.', CONTENT_SOURCES.dlpHistory),
  NEWS('De Marvel-kunstcollectie in Hotel New York omvat werk van meer dan 110 kunstenaars.', CONTENT_SOURCES.dlpHistory),
  NEWS('Ongeveer vijftig kunstwerken in Disney Hotel New York – The Art of Marvel zijn exclusief voor het hotel gemaakt.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disneyland Paris telt zeven Disney Hotels.', CONTENT_SOURCES.dlpFacts),
  NEWS('Disneyland Hotel heropende in 2024 met een vijfsterrenbeleving rond Disney-koninklijke verhalen.', CONTENT_SOURCES.dlpFacts),
  NEWS('Disney Village heeft een multiplex met vijftien bioscoopzalen.', CONTENT_SOURCES.dlpFacts),
  NEWS('De golfbaan bij Disneyland Paris heeft 27 holes.', CONTENT_SOURCES.dlpFacts),
  NEWS('Het resort beschikt over twee speciaal gebouwde congrescentra.', CONTENT_SOURCES.dlpFacts),
  NEWS('De congresfaciliteiten van Disneyland Paris omvatten 95 vergaderruimtes.', CONTENT_SOURCES.dlpFacts),
  NEWS('Cast Members van Disneyland Paris vertegenwoordigen meer dan 120 nationaliteiten.', CONTENT_SOURCES.dlpFacts),
  NEWS('Bij Disneyland Paris bestaan meer dan 500 verschillende soorten beroepen.', CONTENT_SOURCES.dlpFacts),
  NEWS('De tuinen van Disneyland Paris bevatten ongeveer 33.000 bomen.', CONTENT_SOURCES.dlpFacts),
  NEWS('In de tuinen van Disneyland Paris staan ongeveer 330.000 struiken.', CONTENT_SOURCES.dlpFacts),
  NEWS('Disneyland Paris onderhoudt circa 7.400 vierkante meter aan bloemperken.', CONTENT_SOURCES.dlpFacts),
  NEWS('Het resort omvat ongeveer 450 hectare aan groene ruimte.', CONTENT_SOURCES.dlpFacts),
  NEWS('Meer dan honderd medewerkers verzorgen de ecologische gebieden en biodiversiteit van Disneyland Paris.', CONTENT_SOURCES.dlpFacts),
  NEWS('De grote zonneoverkapping boven de parkeerplaatsen werd eind 2023 voltooid.', CONTENT_SOURCES.dlpFacts),
  NEWS('De zonneoverkapping helpt volgens Disneyland Paris ongeveer 890 ton CO₂-uitstoot per jaar te vermijden.', CONTENT_SOURCES.dlpFacts),
  NEWS('De familienaam Disney is verbonden met het Normandische dorp Isigny-sur-Mer.', CONTENT_SOURCES.dlpFacts),
  NEWS('Big Thunder Mountain in Parijs is de enige Disney-versie die op een eiland ligt.', CONTENT_SOURCES.dlpFun),
  NEWS('De treinen van Big Thunder Mountain bereiken het eiland via tunnels onder het water.', CONTENT_SOURCES.dlpFun),
  NEWS('Big Thunder Mountain beslaat in Parijs ongeveer vijf acres aan beide oevers van de Rivers of the Far West.', CONTENT_SOURCES.dlpFun),
  NEWS('De soundtrack van de dertigste verjaardag bevatte twintig Disney- en Pixar-liedjes.', CONTENT_SOURCES.dlpFun),
  NEWS('Voor de dertigste-verjaardagssoundtrack werden 448 audiosporen geprogrammeerd en gemixt.', CONTENT_SOURCES.dlpFun),
  NEWS('De jubileumshow Dream… and Shine Brighter! vond visuele inspiratie bij onder anderen Daniel Buren, Olafur Eliasson en Frank Gehry.', CONTENT_SOURCES.dlpFun),
  NEWS('De bekende gevangenisscène met de hond komt voor in verschillende versies van Pirates of the Caribbean.', CONTENT_SOURCES.dlpFun),
  NEWS('Voor de dertigste verjaardag werden meer dan tweehonderd kostuums gemaakt.', CONTENT_SOURCES.dlpFun),
  NEWS('Voor de dertigste verjaardag werden 190 sieraden en meer dan honderd paar schoenen vervaardigd.', CONTENT_SOURCES.dlpFun),
  NEWS('De kanonlancering van Space Mountain werd geïnspireerd door Jules Vernes Van de aarde naar de maan.', CONTENT_SOURCES.dlpFun),
  NEWS('In 2019 kreeg de Parijse Tower of Terror meerdere verhaallijnen en valprofielen.', CONTENT_SOURCES.dlpFun),
  NEWS('In de wachtrij van Peter Pan’s Flight verwijst de naam Kirriemuir naar de Schotse geboorteplaats van schrijver J.M. Barrie.', CONTENT_SOURCES.dlpFun),
  NEWS('De Parijse versie van “it’s a small world” gebruikt 281 verschillende kostuums.', CONTENT_SOURCES.dlpFun),
  NEWS('Voor de kostuums van “it’s a small world” bestudeerden ontwerpers boeken, musea en culturele festivals.', CONTENT_SOURCES.dlpFun),
  NEWS('Op twee gouden torens van het Parijse kasteel klimmen decoratieve slakken omhoog.', CONTENT_SOURCES.castleFacts),
  NEWS('Het Disney-familiewapen is als terugkerend detail op Disney-kastelen over de hele wereld aangebracht.', CONTENT_SOURCES.castleFacts),
  NEWS('Het Parijse kasteel kreeg in 1993, voor de eerste verjaardag van het park, een aardbeientaart-gedaante.', CONTENT_SOURCES.castleFacts),
  NEWS('Disney-kastelen worden gebouwd met moderne materialen zoals beton, staal, cement, pleister en glasvezel.', CONTENT_SOURCES.castleFacts),
  NEWS('In Shanghai verwijzen vier zwanen bij het kasteel naar Walt Disneys moeder, vrouw en twee dochters.', CONTENT_SOURCES.castleFacts),
  NEWS('Onder het kasteel van Doornroosje in Parijs bevindt zich La Tanière du Dragon.', CONTENT_SOURCES.dlpCastle),
  NEWS('Boven in het Parijse kasteel vertelt een galerie het verhaal van Doornroosje.', CONTENT_SOURCES.dlpCastle),
  NEWS('Phantom Manor staat in Frontierland; andere Haunted Mansion-versies staan juist in andere themalanden.', CONTENT_SOURCES.dlpFun),
  NEWS('De bibliotheek van Tower of Terror bevat een gebroken bril als verwijzing naar de Twilight Zone-aflevering Time Enough at Last.', CONTENT_SOURCES.dlpFun),
  NEWS('Een verborgen camera-object bij Tower of Terror verwijst naar de aflevering A Most Unusual Camera.', CONTENT_SOURCES.dlpFun),
  NEWS('Het achtergrondverhaal van de oorspronkelijke Tower of Terror speelt op Halloweenavond 1939.', CONTENT_SOURCES.towerFacts),
  NEWS('Imagineers bekeken 156 afleveringen van The Twilight Zone als onderzoek voor Tower of Terror.', CONTENT_SOURCES.towerFacts),
  NEWS('De architectuur van de oorspronkelijke Tower of Terror werd geïnspireerd door gebouwen uit Zuid-Californië.', CONTENT_SOURCES.towerFacts),
  NEWS('Het oorspronkelijke Disneyland in Californië opende op 17 juli 1955.', CONTENT_SOURCES.disneylandHistory),
  NEWS('Sleeping Beauty Castle in Californië werd genoemd naar een film die tijdens het ontwerp nog in productie was.', CONTENT_SOURCES.castleFacts),
  NEWS('Cinderella Castle werd het herkenningspunt van Magic Kingdom bij de opening van Walt Disney World in 1971.', CONTENT_SOURCES.disneyHistory),
  NEWS('EPCOT opende in Florida in 1982.', CONTENT_SOURCES.disneyHistory),
  NEWS('Figment maakte zijn debuut in de oorspronkelijke Journey Into Imagination in 1983.', CONTENT_SOURCES.disneyHistory),
  NEWS('Disney’s Hollywood Studios opende in 1989 onder de naam Disney-MGM Studios.', CONTENT_SOURCES.disneyHistory),
  NEWS('Disney’s Animal Kingdom opende op Earth Day in 1998.', CONTENT_SOURCES.disneyHistory),
  NEWS('Disney’s Animal Kingdom verzorgt meer dan 5.000 dieren van ruim 300 soorten.', CONTENT_SOURCES.animalFacts),
  NEWS('Walt Disney World plaatste meer dan vijfhonderd nestcompartimenten voor purperzwaluwen.', CONTENT_SOURCES.animalFacts),
  NEWS('Disney-natuurteams hielpen bij het volgen van meer dan twintigduizend zeeschildpadnesten bij Vero Beach.', CONTENT_SOURCES.animalFacts),
  NEWS('Tokyo Disneyland opende in 1983 als het eerste Disneypark buiten de Verenigde Staten.', CONTENT_SOURCES.tokyoHistory),
  NEWS('Tokyo DisneySea opende in 2001.', CONTENT_SOURCES.tokyoHistory),
  NEWS('Hong Kong Disneyland opende in 2005.', CONTENT_SOURCES.hongKongHistory),
  NEWS('Shanghai Disneyland opende in 2016.', CONTENT_SOURCES.shanghaiHistory),
  NEWS('Mystic Manor in Hong Kong staat in een speciaal themaland dat Mystic Point heet.', CONTENT_SOURCES.dlpFun),
  NEWS('Enchanted Storybook Castle in Shanghai vertegenwoordigt meerdere Disney-prinsessen, niet slechts één.', CONTENT_SOURCES.castleFacts),
  NEWS('De gevangenishond in de Pirates-attractie van Shanghai bewaakt skeletten in plaats van levende piraten.', CONTENT_SOURCES.dlpFun),
  NEWS('Haunted Mansion staat in New Orleans Square in Californië, maar in Liberty Square in Florida.', CONTENT_SOURCES.dlpFun),
  NEWS('De Haunted Mansion van Tokyo Disneyland staat in Fantasyland.', CONTENT_SOURCES.dlpFun),
  NEWS('Rock ’n’ Roller Coaster was de eerste achtbaan in Walt Disney World met meerdere inversies.', CONTENT_SOURCES.rockFacts),
  NEWS('Elke stretch-limousine van de oorspronkelijke Rock ’n’ Roller Coaster bood plaats aan 24 gasten.', CONTENT_SOURCES.rockFacts),
  NEWS('In de voertuigen van Rock ’n’ Roller Coaster zat rond iedere gast een systeem met vijf luidsprekers.', CONTENT_SOURCES.rockFacts),
  NEWS('De gigantische gitaar bij Rock ’n’ Roller Coaster in Florida was ongeveer twaalf meter hoog.', CONTENT_SOURCES.rockFacts),
  NEWS('Disneyland Paris brengt Europese schrijvers en ontwerpstijlen bewust terug in zijn thematisering.', CONTENT_SOURCES.dlpFacts),
  NEWS('Main Street, U.S.A. vormt in Parijs de toegang tot de vier overige themalanden van Disneyland Park.', CONTENT_SOURCES.dlpFacts),
  NEWS('Ratatouille: The Adventure laat bezoekers voor het verhaal krimpen tot het formaat van een rat.', CONTENT_SOURCES.dlpFacts),
  NEWS('De officiële geschiedenis noemt Disneyland Paris Europa’s belangrijkste toeristische bestemming.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disneyland Paris registreerde sinds 1992 meer dan 445 miljoen bezoeken volgens de actuele officiële geschiedenispagina.', CONTENT_SOURCES.dlpHistory),
  NEWS('Disneyland Paris heeft meer dan 20.000 medewerkers.', CONTENT_SOURCES.dlpHistory),
  NEWS('De locatie van Phantom Manor in Frontierland verbindt het spookverhaal direct met Thunder Mesa.', CONTENT_SOURCES.dlpFun),
  NEWS('De eerste versie van Space Mountain in Parijs beeldde letterlijk een reis van de aarde naar de maan uit.', CONTENT_SOURCES.dlpHistory),
  NEWS('Bij de vijfde verjaardag in 1997 kreeg het kasteel een carnavalsdecor rond De Klokkenluider van de Notre Dame.', CONTENT_SOURCES.dlpHistory),
];

export const VERIFIED_MAGIC_NEWS = VERIFIED_MAGIC_NEWS_RECORDS.map(item => item.text);
export const VERIFIED_MAGIC_NEWS_SOURCES = Object.fromEntries(VERIFIED_MAGIC_NEWS_RECORDS.map((item, index) => [`news-${String(index + 1).padStart(3, '0')}`, item.source]));

// Stable release years and protagonist/film relationships. These are based on
// the official Disney/Pixar film catalogues and D23's Disney A-to-Z archive.
const FILMS = [
  ['Snow White and the Seven Dwarfs', 1937, 'Snow White', 'Sneeuwwitje en de zeven dwergen'],
  ['Pinocchio', 1940, 'Pinocchio', 'Pinokkio'],
  ['Dumbo', 1941, 'Dumbo', 'Dombo'],
  ['Bambi', 1942, 'Bambi', 'Bambi'],
  ['Cinderella', 1950, 'Cinderella', 'Assepoester'],
  ['Alice in Wonderland', 1951, 'Alice', 'Alice in Wonderland'],
  ['Peter Pan', 1953, 'Peter Pan', 'Peter Pan'],
  ['Lady and the Tramp', 1955, 'Lady', 'Lady en de Vagebond'],
  ['Sleeping Beauty', 1959, 'Aurora', 'Doornroosje'],
  ['One Hundred and One Dalmatians', 1961, 'Pongo', '101 Dalmatiërs'],
  ['The Sword in the Stone', 1963, 'Wart', 'Merlijn de Tovenaar'],
  ['The Jungle Book', 1967, 'Mowgli', 'Jungle Boek'],
  ['The Aristocats', 1970, 'Duchess', 'De Aristokatten'],
  ['Robin Hood', 1973, 'Robin Hood', 'Robin Hood'],
  ['The Many Adventures of Winnie the Pooh', 1977, 'Winnie the Pooh', 'Het Grote Verhaal van Winnie de Poeh'],
  ['The Rescuers', 1977, 'Bianca', 'De Reddertjes'],
  ['The Fox and the Hound', 1981, 'Tod', 'Frank en Frey'],
  ['The Black Cauldron', 1985, 'Taran', 'Taran en de Toverketel'],
  ['The Great Mouse Detective', 1986, 'Basil', 'De Speurneuzen'],
  ['Oliver & Company', 1988, 'Oliver', 'Oliver & Co.'],
  ['The Little Mermaid', 1989, 'Ariel', 'De Kleine Zeemeermin'],
  ['The Rescuers Down Under', 1990, 'Cody', 'De Reddertjes in Kangoeroeland'],
  ['Beauty and the Beast', 1991, 'Belle', 'Belle en het Beest'],
  ['Aladdin', 1992, 'Aladdin', 'Aladdin'],
  ['The Lion King', 1994, 'Simba', 'De Leeuwenkoning'],
  ['Pocahontas', 1995, 'Pocahontas', 'Pocahontas'],
  ['The Hunchback of Notre Dame', 1996, 'Quasimodo', 'De Klokkenluider van de Notre Dame'],
  ['Hercules', 1997, 'Hercules', 'Hercules'],
  ['Mulan', 1998, 'Mulan', 'Mulan'],
  ['Tarzan', 1999, 'Tarzan', 'Tarzan'],
  ['Dinosaur', 2000, 'Aladar', 'Dinosaur'],
  ["The Emperor's New Groove", 2000, 'Kuzco', 'Keizer Kuzco'],
  ['Atlantis: The Lost Empire', 2001, 'Milo Thatch', 'Atlantis: De Verzonken Stad'],
  ['Lilo & Stitch', 2002, 'Lilo', 'Lilo & Stitch'],
  ['Treasure Planet', 2002, 'Jim Hawkins', 'Piratenplaneet'],
  ['Brother Bear', 2003, 'Kenai', 'Brother Bear'],
  ['Home on the Range', 2004, 'Maggie', 'Paniek op de Prairie'],
  ['Chicken Little', 2005, 'Chicken Little', 'Chicken Little'],
  ['Meet the Robinsons', 2007, 'Lewis', 'Meet the Robinsons'],
  ['Bolt', 2008, 'Bolt', 'Bolt'],
  ['The Princess and the Frog', 2009, 'Tiana', 'De Prinses en de Kikker'],
  ['Tangled', 2010, 'Rapunzel', 'Rapunzel'],
  ['Wreck-It Ralph', 2012, 'Ralph', 'Wreck-It Ralph'],
  ['Frozen', 2013, 'Anna', 'Frozen'],
  ['Big Hero 6', 2014, 'Hiro Hamada', 'Big Hero 6'],
  ['Zootopia', 2016, 'Judy Hopps', 'Zootropolis'],
  ['Moana', 2016, 'Moana', 'Vaiana'],
  ['Ralph Breaks the Internet', 2018, 'Vanellope', 'Ralph Breaks the Internet'],
  ['Frozen II', 2019, 'Elsa', 'Frozen II'],
  ['Raya and the Last Dragon', 2021, 'Raya', 'Raya en de Laatste Draak'],
  ['Encanto', 2021, 'Mirabel', 'Encanto'],
  ['Strange World', 2022, 'Searcher Clade', 'Strange World'],
  ['Wish', 2023, 'Asha', 'Wish'],
  ['Moana 2', 2024, 'Simea', 'Vaiana 2'],
  ['Toy Story', 1995, 'Woody', 'Toy Story'],
  ["A Bug's Life", 1998, 'Flik', 'Een Luizenleven'],
  ['Toy Story 2', 1999, 'Jessie', 'Toy Story 2'],
  ['Monsters, Inc.', 2001, 'Sulley', 'Monsters en Co.'],
  ['Finding Nemo', 2003, 'Marlin', 'Finding Nemo'],
  ['The Incredibles', 2004, 'Violet Parr', 'The Incredibles'],
  ['Cars', 2006, 'Lightning McQueen', 'Cars'],
  ['Ratatouille', 2007, 'Remy', 'Ratatouille'],
  ['WALL-E', 2008, 'WALL-E', 'WALL-E'],
  ['Up', 2009, 'Carl Fredricksen', 'Up'],
  ['Toy Story 3', 2010, 'Lotso', 'Toy Story 3'],
  ['Cars 2', 2011, 'Mater', 'Cars 2'],
  ['Brave', 2012, 'Merida', 'Brave'],
  ['Monsters University', 2013, 'Mike Wazowski', 'Monsters University'],
  ['Inside Out', 2015, 'Riley', 'Binnenstebuiten'],
  ['The Good Dinosaur', 2015, 'Arlo', 'The Good Dinosaur'],
  ['Finding Dory', 2016, 'Dory', 'Finding Dory'],
  ['Coco', 2017, 'Miguel', 'Coco'],
  ['Incredibles 2', 2018, 'Elastigirl', 'Incredibles 2'],
  ['Toy Story 4', 2019, 'Forky', 'Toy Story 4'],
  ['Soul', 2020, 'Joe Gardner', 'Soul'],
];

const MILESTONES = [
  ['de ondertekening van de oprichtingsovereenkomst van Disneyland Paris', 1987, CONTENT_SOURCES.dlpHistory],
  ['de start van de bouw van Disneyland Paris', 1988, CONTENT_SOURCES.dlpHistory],
  ['de opening van Disneyland Paris', 1992, CONTENT_SOURCES.dlpHistory],
  ['de opening van het RER-station Marne-la-Vallée–Chessy', 1992, CONTENT_SOURCES.dlpHistory],
  ['de opening van Indiana Jones et le Temple du Péril', 1993, CONTENT_SOURCES.dlpHistory],
  ['de opening van het TGV-station bij Disneyland Paris', 1994, CONTENT_SOURCES.dlpHistory],
  ['de opening van Space Mountain – From the Earth to the Moon', 1995, CONTENT_SOURCES.dlpHistory],
  ['het vijfjarig jubileum van Disneyland Paris', 1997, CONTENT_SOURCES.dlpHistory],
  ['de opening van het tweede park van Disneyland Paris', 2002, CONTENT_SOURCES.dlpHistory],
  ['het tienjarig jubileum van Disneyland Park', 2002, CONTENT_SOURCES.dlpHistory],
  ['de opening van Space Mountain: Mission 2', 2005, CONTENT_SOURCES.dlpHistory],
  ['de opening van Buzz Lightyear Laser Blast in Parijs', 2006, CONTENT_SOURCES.dlpHistory],
  ['de opening van Tower of Terror in Parijs', 2008, CONTENT_SOURCES.dlpHistory],
  ['de opening van Toy Story Playland', 2010, CONTENT_SOURCES.dlpHistory],
  ['het twintigjarig jubileum van Disneyland Paris', 2012, CONTENT_SOURCES.dlpHistory],
  ['de opening van Place de Rémy', 2014, CONTENT_SOURCES.dlpHistory],
  ['de start van het grote renovatieprogramma van Disneyland Paris', 2015, CONTENT_SOURCES.dlpHistory],
  ['het vijfentwintigjarig jubileum van Disneyland Paris', 2017, CONTENT_SOURCES.dlpHistory],
  ['de aankondiging van het investeringsplan van twee miljard euro', 2018, CONTENT_SOURCES.dlpHistory],
  ['de heropening van Disney Hotel New York als The Art of Marvel', 2021, CONTENT_SOURCES.dlpHistory],
  ['het dertigjarig jubileum van Disneyland Paris', 2022, CONTENT_SOURCES.dlpHistory],
  ['de heropening van Disneyland Hotel na de koninklijke transformatie', 2024, CONTENT_SOURCES.dlpFacts],
  ['de opening van Disneyland in Californië', 1955, CONTENT_SOURCES.disneylandHistory],
  ['de opening van Magic Kingdom in Florida', 1971, CONTENT_SOURCES.disneyHistory],
  ['de opening van EPCOT', 1982, CONTENT_SOURCES.disneyHistory],
  ['de opening van Tokyo Disneyland', 1983, CONTENT_SOURCES.tokyoHistory],
  ['de opening van Disney’s Hollywood Studios', 1989, CONTENT_SOURCES.disneyHistory],
  ['de opening van Disneyland Park in Parijs', 1992, CONTENT_SOURCES.dlpHistory],
  ['de opening van Disney’s Animal Kingdom', 1998, CONTENT_SOURCES.disneyHistory],
  ['de opening van Disney California Adventure', 2001, CONTENT_SOURCES.disneyHistory],
  ['de opening van Tokyo DisneySea', 2001, CONTENT_SOURCES.tokyoHistory],
  ['de opening van Hong Kong Disneyland', 2005, CONTENT_SOURCES.hongKongHistory],
  ['de opening van Shanghai Disneyland', 2016, CONTENT_SOURCES.shanghaiHistory],
  ['de première van Snow White and the Seven Dwarfs', 1937, CONTENT_SOURCES.disneyMovies],
  ['de première van Pinocchio', 1940, CONTENT_SOURCES.disneyMovies],
  ['de première van Cinderella', 1950, CONTENT_SOURCES.disneyMovies],
  ['de première van Sleeping Beauty', 1959, CONTENT_SOURCES.disneyMovies],
  ['de première van The Jungle Book', 1967, CONTENT_SOURCES.disneyMovies],
  ['de première van The Little Mermaid', 1989, CONTENT_SOURCES.disneyMovies],
  ['de première van Beauty and the Beast', 1991, CONTENT_SOURCES.disneyMovies],
  ['de première van Aladdin', 1992, CONTENT_SOURCES.disneyMovies],
  ['de première van The Lion King', 1994, CONTENT_SOURCES.disneyMovies],
  ['de première van Toy Story', 1995, CONTENT_SOURCES.pixarFilms],
  ['de première van Mulan', 1998, CONTENT_SOURCES.disneyMovies],
  ['de première van Monsters, Inc.', 2001, CONTENT_SOURCES.pixarFilms],
  ['de première van Finding Nemo', 2003, CONTENT_SOURCES.pixarFilms],
  ['de première van The Incredibles', 2004, CONTENT_SOURCES.pixarFilms],
  ['de première van Cars', 2006, CONTENT_SOURCES.pixarFilms],
  ['de première van Ratatouille', 2007, CONTENT_SOURCES.pixarFilms],
  ['de première van WALL-E', 2008, CONTENT_SOURCES.pixarFilms],
  ['de première van The Princess and the Frog', 2009, CONTENT_SOURCES.disneyMovies],
  ['de première van Tangled', 2010, CONTENT_SOURCES.disneyMovies],
  ['de première van Brave', 2012, CONTENT_SOURCES.pixarFilms],
  ['de première van Frozen', 2013, CONTENT_SOURCES.disneyMovies],
  ['de première van Inside Out', 2015, CONTENT_SOURCES.pixarFilms],
  ['de première van Moana', 2016, CONTENT_SOURCES.disneyMovies],
  ['de première van Coco', 2017, CONTENT_SOURCES.pixarFilms],
  ['de première van Encanto', 2021, CONTENT_SOURCES.disneyMovies],
  ['de première van Wish', 2023, CONTENT_SOURCES.disneyMovies],
  ['de première van Inside Out 2', 2024, CONTENT_SOURCES.pixarFilms],
];

const VERIFIED_METRICS = [
  ['Hoeveel kilometer ten oosten van Parijs ligt Disneyland Paris ongeveer?', 32, 'kilometer', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel themaparken telt Disneyland Paris?', 2, 'parken', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel Disney Hotels telt Disneyland Paris?', 7, 'hotels', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel themalanden heeft Disneyland Park in Parijs?', 5, 'themalanden', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel acres beslaat Disneyland Park volgens het officiële factsheet?', 124, 'acres', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel acres besloeg het tweede park volgens het officiële factsheet vóór de uitbreiding?', 62, 'acres', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel bioscoopzalen heeft de multiplex in Disney Village?', 15, 'zalen', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel speciaal gebouwde congrescentra heeft Disneyland Paris?', 2, 'centra', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel conferentiehallen vermeldt het officiële factsheet?', 3, 'hallen', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel vergaderruimtes heeft Disneyland Paris volgens het factsheet?', 95, 'ruimtes', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel holes heeft Golf Paris Val d’Europe?', 27, 'holes', CONTENT_SOURCES.dlpFacts],
  ['Uit hoeveel landen komen de Cast Members van Disneyland Paris volgens het factsheet minimaal?', 120, 'landen', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel verschillende soorten beroepen bestaan er bij Disneyland Paris?', 500, 'beroepen', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel bomen staan er ongeveer in de tuinen van Disneyland Paris?', 33000, 'bomen', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel struiken staan er ongeveer in de tuinen van Disneyland Paris?', 330000, 'struiken', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel vierkante meter bloemperken onderhoudt Disneyland Paris ongeveer?', 7400, 'm²', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel hectare groene ruimte omvat Disneyland Paris ongeveer?', 450, 'hectare', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel medewerkers verzorgen de ecologische gebieden van Disneyland Paris minimaal?', 100, 'medewerkers', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel ton CO₂-uitstoot helpt de zonneoverkapping jaarlijks ongeveer te vermijden?', 890, 'ton', CONTENT_SOURCES.dlpFacts],
  ['Hoeveel miljoen euro bedroeg het in 2018 aangekondigde investeringsplan?', 2000, 'miljoen euro', CONTENT_SOURCES.dlpHistory],
  ['Hoeveel kunstwerken hangen er minimaal in Disney Hotel New York – The Art of Marvel?', 350, 'kunstwerken', CONTENT_SOURCES.dlpHistory],
  ['Van hoeveel kunstenaars is werk te zien in Disney Hotel New York – The Art of Marvel?', 110, 'kunstenaars', CONTENT_SOURCES.dlpHistory],
  ['Hoeveel exclusieve werken omvat de Marvel-kunstcollectie in het hotel ongeveer?', 50, 'werken', CONTENT_SOURCES.dlpHistory],
  ['Hoeveel meter lang was de papieren trein bij de opening van het TGV-station?', 300, 'meter', CONTENT_SOURCES.dlpHistory],
  ['Hoeveel versies van Big Thunder Mountain noemt Disney Parks Blog wereldwijd?', 4, 'versies', CONTENT_SOURCES.dlpFun],
  ['Hoeveel acres beslaat Big Thunder Mountain in Parijs ongeveer?', 5, 'acres', CONTENT_SOURCES.dlpFun],
  ['Hoeveel liedjes bevatte de soundtrack van de dertigste verjaardag?', 20, 'liedjes', CONTENT_SOURCES.dlpFun],
  ['Hoeveel maanden ontwikkeling kostte de jubileum-soundtrack?', 6, 'maanden', CONTENT_SOURCES.dlpFun],
  ['Hoeveel maanden kostte het synchroniseren, programmeren en mixen daarna?', 3, 'maanden', CONTENT_SOURCES.dlpFun],
  ['Hoeveel audiosporen werden voor die jubileum-soundtrack verwerkt?', 448, 'audiosporen', CONTENT_SOURCES.dlpFun],
  ['Hoeveel jubileumkostuums werden voor de dertigste verjaardag minimaal gemaakt?', 200, 'kostuums', CONTENT_SOURCES.dlpFun],
  ['Hoeveel sieraden werden voor de dertigste verjaardag gemaakt?', 190, 'sieraden', CONTENT_SOURCES.dlpFun],
  ['Hoeveel verschillende kostuums gebruikt “it’s a small world” in Parijs?', 281, 'kostuums', CONTENT_SOURCES.dlpFun],
  ['Hoeveel afleveringen van The Twilight Zone bekeken Imagineers voor hun onderzoek?', 156, 'afleveringen', CONTENT_SOURCES.towerFacts],
  ['Hoeveel gasten passen in een stretch-limousine van de oorspronkelijke Rock ’n’ Roller Coaster?', 24, 'gasten', CONTENT_SOURCES.rockFacts],
  ['Hoeveel luidsprekers omringden iedere gast in zo’n Rock ’n’ Roller Coaster-voertuig?', 5, 'luidsprekers', CONTENT_SOURCES.rockFacts],
  ['Hoeveel diersoorten worden in Disney’s Animal Kingdom minimaal verzorgd?', 300, 'soorten', CONTENT_SOURCES.animalFacts],
  ['Hoeveel dieren worden in Disney’s Animal Kingdom ongeveer verzorgd?', 5000, 'dieren', CONTENT_SOURCES.animalFacts],
  ['Hoeveel nestcompartimenten voor purperzwaluwen plaatste Walt Disney World minimaal?', 500, 'nestplekken', CONTENT_SOURCES.animalFacts],
  ['Hoeveel zeeschildpadnesten hielpen Disney-teams bij Vero Beach minimaal volgen?', 20000, 'nesten', CONTENT_SOURCES.animalFacts],
];

const placeCorrectAnswer = (correct, wrong, index) => {
  const position = index % 4;
  const answers = [...wrong.slice(0, 3)];
  answers.splice(position, 0, correct);
  return { answers, correct: position };
};

const quizTasks = FILMS.flatMap((film, index) => {
  const [title, year, lead, dutchTitle] = film;
  const source = index < 55 ? CONTENT_SOURCES.disneyMovies : CONTENT_SOURCES.pixarFilms;
  const otherFilms = [1, 7, 13].map(offset => FILMS[(index + offset) % FILMS.length]);
  const easy = placeCorrectAnswer(dutchTitle, otherFilms.map(item => item[3]), index);
  const medium = placeCorrectAnswer(String(year), [String(year - 1), String(year + 1), String(year + 2)], index + 1);
  const hard = placeCorrectAnswer(
    `${title} — ${year}`,
    otherFilms.map((item, wrongIndex) => `${item[0]} — ${item[1] + wrongIndex + 1}`),
    index + 2
  );
  return [
    { id: `quiz-easy-${index + 51}`, cat: 'Quiz', type: 'quiz', difficulty: 'easy', title: 'Disney Filmquiz', text: `Welke oorspronkelijke animatiefilm uit ${year} hoort bij ${lead}?`, ...easy, points: 1, source },
    { id: `quiz-medium-${index + 51}`, cat: 'Quiz', type: 'quiz', difficulty: 'medium', title: 'Disney Filmgeschiedenis', text: `In welk jaar verscheen de oorspronkelijke animatiefilm ${title}?`, ...medium, points: 2, source },
    { id: `quiz-hard-${index + 51}`, cat: 'Quiz', type: 'quiz', difficulty: 'hard', title: 'Disney Archiefkenner', text: `Welke combinatie rond de filmgeschiedenis van ${lead} klopt?`, ...hard, points: 3, source },
  ];
});

const estimateTasks = [
  ...MILESTONES.map(([event, year, source]) => ({ text: `In welk jaar vond ${event} plaats?`, value: year, unit: 'jaar', source })),
  ...VERIFIED_METRICS.map(([text, value, unit, source]) => ({ text, value, unit, source })),
].map((item, index) => ({
  id: `estimate-${index + 1}`,
  cat: 'Inschattingsvragen',
  type: 'estimate',
  title: 'Disney Tijdlijn',
  text: item.text,
  correct_value: item.value,
  unit: item.unit,
  points: 2,
  source: item.source,
}));

// Every clue follows the adult 5+/3/1 model: a broad first clue, a second clue
// that leaves a small cluster of plausible characters, and a unique final clue.
// Neither the answer nor the film title is printed in the clues.
const WHOAMI_CHARACTERS = [
  ['Dopey', 1937, 'Ik hoor bij een hechte groep waarin uiterlijk en temperament belangrijker zijn dan individuele achtergrondverhalen.', 'Ik ben een klein, zwijgzaam personage dat vooral via mimiek en lichamelijke komedie communiceert.', 'Binnen mijn groep ben ik de enige zonder baard én de enige die nooit spreekt.'],
  ['Jiminy Cricket', 1940, 'Ik ben een niet-menselijke begeleider die probeert een onervaren hoofdpersoon moreel op koers te houden.', 'Mijn gezag is niet vanzelfsprekend: ik word officieel aangesteld voor een taak waarvoor ik nauwelijks ben voorbereid.', 'Mijn beloning voor die taak is een officieel geweten worden en uiteindelijk een gouden onderscheiding ontvangen.'],
  ['Timothy Q. Mouse', 1941, 'Ik ben een klein dier dat een veel groter buitenbeentje helpt om een vernederende situatie te overwinnen.', 'Ik combineer de rollen van vriend, coach en geïmproviseerde impresario in een reizende amusementswereld.', 'Mijn plan maakt van uitzonderlijk grote oren geen gebrek maar het middel waarmee mijn vriend kan vliegen.'],
  ['Thumper', 1942, 'Ik ben een jong dier dat een terughoudende hoofdpersoon kennis laat maken met zijn leefomgeving.', 'Mijn enthousiasme en spraakzaamheid contrasteren met de verlegenheid van mijn beste vriend.', 'Mijn naam verwijst naar wat mijn achterpoot voortdurend op de grond doet.'],
  ['Fairy Godmother', 1950, 'Ik gebruik magie om iemand tijdelijk toegang te geven tot een wereld die normaal gesloten blijft.', 'Mijn hulp verandert meerdere alledaagse dieren en voorwerpen, maar is nadrukkelijk aan een deadline gebonden.', 'Mijn betovering verandert een pompoen in vervoer en eindigt precies om middernacht.'],
  ['Mad Hatter', 1951, 'Ik ben een excentriek figuur in een wereld waar logica voortdurend van betekenis verandert.', 'Ik behandel een sociale bijeenkomst als een eindeloos ritueel en reageer vijandig op gewone etiquette.', 'Ik vier dagelijks een on-verjaardag aan een theetafel waar voortdurend van plaats wordt gewisseld.'],
  ['Wendy Darling', 1953, 'Ik verlaat tijdelijk mijn vertrouwde omgeving en neem in een gevaarlijke fantasiewereld een zorgende rol op mij.', 'Ik balanceer tussen de aantrekkingskracht van eeuwige jeugd en het besef dat volwassen worden onvermijdelijk is.', 'Mijn verhalen over een vliegende jongen lokken hem naar het slaapkamerraam dat ik met twee broertjes deel.'],
  ['Tramp', 1955, 'Ik leef buiten de gevestigde orde en leer iemand uit een beschermde omgeving een vrijer bestaan kennen.', 'Mijn charme verbergt dat ik gehechtheid vermijd, totdat een bedreiging voor een gezin mij tot verantwoordelijkheid dwingt.', 'Mijn beroemdste maaltijd deel ik in een steeg, waarbij één spaghettisliert onverwacht tot een kus leidt.'],
  ['Prince Phillip', 1959, 'Ik ben een koninklijk personage dat zich niet neerlegt bij een gearrangeerde toekomst.', 'Mijn tegenstander gebruikt een betoverd landschap en monsterlijke gedaante om mij van een slapend doelwit weg te houden.', 'Met een schild van deugd en een zwaard van waarheid versla ik een draak in een doornwoud.'],
  ['Perdita', 1961, 'Ik ben een ouderfiguur die een grote zoektocht onderneemt nadat jonge gezinsleden zijn verdwenen.', 'Mijn partner en ik gebruiken een communicatienetwerk van dieren om een spoor buiten de stad te vinden.', 'Ons gezin groeit na de redding van vijftien eigen pups uit tot negenennegentig honden.'],
  ['Merlin', 1963, 'Ik ben een oudere magische mentor die een onwaarschijnlijke jongere voorbereidt op een veel grotere bestemming.', 'Mijn lessen bestaan uit lichamelijke gedaantewisselingen die abstracte ideeën als verstand en liefde tastbaar maken.', 'Na een reis naar Bermuda keer ik terug om te ontdekken dat mijn leerling een zwaard uit een steen heeft getrokken.'],
  ['Baloo', 1967, 'Ik ben een zorgeloze dierlijke mentor die vrijheid belangrijker vindt dan regels of status.', 'Mijn levenshouding botst met die van een strenge beschermer die dezelfde jongen veilig wil afleveren.', 'Ik leer mijn mensenwelp zoeken naar de eenvoudige levensbehoeften en vermom mij later als dansende aap.'],
  ["Thomas O'Malley", 1970, 'Ik ben een straatwijze buitenstaander die een beschermd gezin tijdens een gevaarlijke terugreis helpt.', 'Mijn aanvankelijke interesse in één volwassen gezinslid groeit uit tot verantwoordelijkheid voor haar kinderen.', 'Ik ben de zelfbenoemde kat van de Abraham de Lacy Giuseppe Casey-familielijn.'],
  ['Little John', 1973, 'Ik ben de grote, goedmoedige metgezel van een vogelvrije held die onrecht met humor bestrijdt.', 'Mijn omvang maakt mij opvallend, maar vermommingen laten mij toch dicht bij het hof en de schatkist komen.', 'Ik speel de hertog van Chutney terwijl mijn beste vriend zich voordoet als waarzegster.'],
  ['Piglet', 1977, 'Ik ben een klein en angstig lid van een vriendengroep waarin eenvoudige problemen grote avonturen worden.', 'Mijn geringe formaat en aarzelende stem verhullen dat ik op beslissende momenten opmerkelijk moedig handel.', 'Mijn huis draagt een bord met de naam Trespassers William, die ik als familienaam interpreteer.'],
  ['Bernard', 1977, 'Ik werk binnen een internationale organisatie die mensen in nood helpt zonder door hen te worden opgemerkt.', 'Ik ben bijgelovig over het getal dertien en word gekoppeld aan een veel mondainere collega.', 'Onze opdracht begint met een boodschap in een fles van een ontvoerd weesmeisje.'],
  ['Tod', 1981, 'Ik sluit als jong dier een vriendschap die volgens de volwassen wereld niet zou mogen bestaan.', 'Wanneer mijn vriend wordt opgeleid voor een traditionele rol, verandert onze onschuldige band in een conflict.', 'Ik red de jachthond die mij moest opsporen uiteindelijk van een aanvallende beer.'],
  ['Taran', 1985, 'Ik ben een jonge held die verlangt naar roem voordat ik begrijp wat verantwoordelijkheid kost.', 'Mijn dagelijkse taak lijkt onbeduidend, maar het dier waarvoor ik zorg bezit een uitzonderlijk inzicht.', 'Ik moet een helderziend varken beschermen tegen een koning die met een zwarte ketel een leger wil maken.'],
  ['Basil', 1986, 'Ik los mysteries op vanuit een grote stad en vertrouw daarbij op observatie, vermomming en deductie.', 'Mijn woonadres en werkwijze verwijzen nadrukkelijk naar een beroemde menselijke speurder.', 'Ik achtervolg een rattenmisdadiger via speelgoedwinkels, een luchtschip en de tandwielen van Big Ben.'],
  ['Dodger', 1988, 'Ik ben een zelfverzekerde straatbewoner die een naïeve nieuwkomer in een stedelijke groep introduceert.', 'Mijn bravoure en muzikale uitstraling maken mij de informele leider van een bende zonder vast thuis.', 'Ik steel hotdogs met behulp van een taxi en leer een kitten dat hij zich nergens druk om hoeft te maken.'],
  ['Sebastian', 1989, 'Ik ben een kleine hofdienaar die tegelijk toezicht moet houden en problemen uit het zicht van een vorst probeert te houden.', 'Mijn plichtsgevoel botst met mijn liefde voor muziek en met de koppigheid van een jonge royal.', 'Ik dirigeer een onderwaterorkest en probeer op het land een romantische boottocht muzikaal te sturen.'],
  ['Cody', 1990, 'Ik ben een kind dat door mijn respect voor dieren in een avontuur met stropers en redders belandt.', 'Mijn gevangenschap ontstaat doordat ik de locatie van een uitzonderlijk dier geheim wil houden.', 'Ik vlieg op de rug van een zeldzame gouden adelaar die Marahute heet.'],
  ['Beast', 1991, 'Ik leef door een vloek geïsoleerd van de samenleving en moet mijn gedrag veranderen voordat de tijd opraakt.', 'Mijn uiterlijk weerspiegelt een morele tekortkoming, terwijl de mensen om mij heen eveneens van vorm zijn veranderd.', 'Een betoverde roos bepaalt hoeveel tijd ik heb om liefde te leren geven én ontvangen.'],
  ['Abu', 1992, 'Ik ben een kleine dierlijke metgezel die loyaliteit combineert met een slecht onderdrukte liefde voor kostbaarheden.', 'Mijn impulsiviteit brengt een zorgvuldig plan in gevaar wanneer één verboden voorwerp onweerstaanbaar blijkt.', 'In een wondergrot negeer ik de waarschuwing en grijp ik een enorme rode robijn.'],
  ['Timon', 1994, 'Ik ben een komische buitenstaander die een getraumatiseerde erfgenaam een zorgeloze levensfilosofie leert.', 'Mijn vriendschap met een veel groter dier is gebaseerd op wederzijdse loyaliteit én een gedeeld dieet.', 'Om een groep vijanden af te leiden voer ik verkleed een Hawaiiaanse culinaire show op.'],
  ['Esmeralda', 1996, 'Ik sta buiten de machtige instituties van mijn stad en kom openlijk op voor mensen die worden vervolgd.', 'Mijn empathie verbindt een geïsoleerde klokkenluider, een soldaat en een gemeenschap die zich verborgen houdt.', 'In een kathedraal vraag ik niet om rijkdom voor mezelf maar om hulp voor de verschoppelingen.'],
  ['Megara', 1997, 'Ik gebruik cynisme om te verhullen dat een eerdere liefdeskeuze mij mijn vrijheid heeft gekost.', 'Ik werk gedwongen voor een machthebber die via mij de zwakte van een jonge held wil ontdekken.', 'Mijn oprechte gevoel maakt de held tijdelijk sterfelijk, waarna ik hem red van een vallende zuil.'],
  ['Mushu', 1998, 'Ik ben een kleine, luidruchtige begeleider die zichzelf belangrijker presenteert dan mijn officiële status rechtvaardigt.', 'Mijn hulp is aanvankelijk bedoeld om mijn eigen reputatie binnen een familie te herstellen.', 'Ik wek een voorouder per ongeluk niet, breek diens stenen beeld en doe vervolgens alsof ik namens hem ben gestuurd.'],
  ['Jane Porter', 1999, 'Ik ben een onderzoeker die in een onbekende omgeving zowel wetenschappelijke nieuwsgierigheid als persoonlijke loyaliteit ontwikkelt.', 'Mijn waarnemingen botsen met de commerciële bedoelingen van iemand uit dezelfde expeditie.', 'Een geredde schets van een babybaviaan helpt mij communiceren met een man die door gorilla’s is opgevoed.'],
  ['Aladar', 2000, 'Ik word door een andere soort opgevoed en moet tijdens een ramp mijn plaats in een grotere kudde vinden.', 'Mijn empathie voor de zwaksten botst met een leider die uitsluitend snelheid en overleving waardeert.', 'Ik ben een iguanodon die als ei door lemuren wordt gevonden en later een alternatieve route naar de nestgronden ontdekt.'],
  ['Kuzco', 2000, 'Ik begin als een machthebber voor wie andere mensen vooral obstakels voor persoonlijk gemak zijn.', 'Een onvrijwillige gedaanteverwisseling dwingt mij afhankelijk te worden van iemand wiens huis ik wilde afbreken.', 'Het verkeerde flesje verandert mij in een lama in plaats van mij definitief uit de weg te ruimen.'],
  ['Milo Thatch', 2001, 'Ik ben een geleerde wiens expertise door mijn omgeving als obsessie wordt afgedaan.', 'Een onverwachte financier geeft mij toegang tot een expeditie die de ideeën van mijn familie kan rehabiliteren.', 'Mijn kennis van een vergeten taal activeert een vliegende stenen vis en helpt een verzonken beschaving begrijpen.'],
  ['Stitch', 2002, 'Ik ben gemaakt voor vernietiging maar ontwikkel binnen een gekozen gezin gedrag dat mijn ontwerp tegenspreekt.', 'Mijn aanwezigheid wordt aanvankelijk verborgen achter een verkeerd begrepen identiteit als huisdier.', 'Ik ben experiment 626 en gebruik een voorgelezen verhaal over een lelijk eendje om mijn eenzaamheid te begrijpen.'],
  ['Jim Hawkins', 2002, 'Ik ben een rusteloze jongere die via een gevaarlijke reis een mentor vindt op wie ik niet volledig kan vertrouwen.', 'Een kaart en een nalatenschap brengen mij aan boord van een schip waar muiterij en ouderlijke teleurstelling samenkomen.', 'Mijn bestemming is geen eiland op zee maar een planeet die bereikbaar is met een schip op zonnezeilen.'],
  ['Kenai', 2003, 'Ik moet letterlijk vanuit een ander perspectief leren kijken nadat woede mij tot een onomkeerbare daad brengt.', 'Mijn zoektocht naar herstel wordt bemoeilijkt doordat ik verantwoordelijkheid krijg voor iemand die door mijn daad familie verloor.', 'De geesten veranderen mij in een beer nadat ik uit wraak de broer van Koda heb gedood.'],
  ['Maggie', 2004, 'Ik ben een eigenzinnig boerderijdier dat na verlies van mijn thuis aansluiting zoekt bij een onwaarschijnlijk team.', 'Een financiële dreiging maakt de gevangenneming van een beruchte misdadiger belangrijker dan persoonlijke rivaliteit.', 'Ik probeer samen met twee andere koeien de premie op Alameda Slim te innen om onze boerderij te redden.'],
  ['Chicken Little', 2005, 'Mijn publieke reputatie is beschadigd doordat niemand mijn verklaring over een onwaarschijnlijke gebeurtenis gelooft.', 'Ik probeer via sport het vertrouwen van mijn ouder en gemeenschap terug te winnen voordat het bewijs terugkeert.', 'Het voorwerp dat uit de lucht valt blijkt een camouflerend paneel van een buitenaards schip.'],
  ['Lewis', 2007, 'Ik ben een jonge uitvinder die denkt dat kennis over mijn afkomst belangrijker is dan mijn mislukkingen.', 'Een bezoek aan de toekomst laat mij de gevolgen zien van zowel doorzetten als blijven hangen in afwijzing.', 'Mijn geheugen-scanner mislukt door sabotage van een bolhoed die zelfstandig plannen maakt.'],
  ['Bolt', 2008, 'Ik begrijp aanvankelijk niet dat mijn professionele identiteit geënsceneerd is.', 'Buiten mijn vertrouwde omgeving moet ik zonder vermeende krachten leren wie ik werkelijk ben.', 'Ik denk dat een piepschuimen verpakking mij verzwakt zoals kryptoniet, omdat ik een televisiesuperhond speel.'],
  ['Prince Naveen', 2009, 'Mijn bevoorrechte levensstijl heeft mij slecht voorbereid op verantwoordelijkheid en zelfstandig werk.', 'Een magische overeenkomst die rijkdom belooft verandert mijn uiterlijk en koppelt mijn lot aan dat van een ambitieuze vrouw.', 'Na een kus blijven we allebei kikkers omdat zij op dat moment geen echte prinses is.'],
  ['Flynn Rider', 2010, 'Mijn publieke naam en zelfverzekerde verhalen zijn middelen om afstand te houden van een minder glamoureus verleden.', 'Een gestolen koninklijk voorwerp brengt mij in een verborgen verblijf waar ik een onwaarschijnlijke overeenkomst sluit.', 'Mijn beroemde gezicht in opsporingsposters heeft volgens mij telkens de verkeerde neus.'],
  ['Ralph', 2012, 'Mijn functie maakt mij noodzakelijk voor een gemeenschap die mij buiten werktijd toch als bedreiging behandelt.', 'Ik verlaat mijn vaste omgeving om erkenning te verdienen, maar neem daardoor een gevaarlijk element mee naar elders.', 'Ik breek gebouwen in een arcadekast en gebruik later een mentoskrater om een kartwereld te redden.'],
  ['Elsa', 2013, 'Ik isoleer mij om anderen te beschermen tegen een eigenschap die ik niet volledig beheers.', 'Een familierelatie, niet een romantische redding, blijkt de sleutel tot herstel van een bevroren koninkrijk.', 'Mijn kroning loopt mis wanneer een handschoen verdwijnt en een eeuwige winter zichtbaar uit mijn handen ontstaat.'],
  ['Hiro Hamada', 2014, 'Ik ben een technisch wonderkind dat verlies aanvankelijk omzet in een verlangen naar vergelding.', 'Een zachte zorgverlener en een groep jonge wetenschappers helpen mij mijn uitvindingen anders te gebruiken.', 'Mijn zwerm microbots reageert op een neurale zender die verborgen blijkt in het masker van de dader.'],
  ['Judy Hopps', 2016, 'Ik wil een beroep uitoefenen waarvoor mijn omgeving mijn soort ongeschikt acht.', 'Een vermissingszaak dwingt mij samen te werken met iemand tegenover wie ik zelf vooroordelen heb.', 'Ik word de eerste konijnenagent van een grote zoogdierenstad en begin met parkeerbonnen.'],
  ['Moana', 2016, 'Mijn verantwoordelijkheid voor een gemeenschap botst met een sterke aantrekking tot een verboden horizon.', 'Ik moet een beschadigd natuurlijk evenwicht herstellen met hulp van iemand die vooral zijn eigen legende vertelt.', 'De steen die ik terugbreng is het hart van een eilandgodin die als lavamonster tegenover mij staat.'],
  ['Vanellope', 2018, 'Een technische afwijking die anderen tegen mij gebruiken blijkt samen te hangen met een gestolen identiteit.', 'Mijn verlangen om vrij te kiezen brengt een hechte vriendschap onder druk wanneer ik een nieuwe spelwereld ontdek.', 'Mijn glitch wordt een racekracht en ik blijkt de verdwenen prinses van een snoepwereld.'],
  ['Raya', 2021, 'Een mislukte poging tot samenwerking maakt vertrouwen voor mij zowel gevaarlijk als noodzakelijk.', 'Ik verzamel leden uit verdeelde gebieden om een bedreiging te herstellen die mensen in steen verandert.', 'Ik zoek de laatste draak om een gebroken edelsteen uit vijf landen weer samen te voegen.'],
  ['Mirabel', 2021, 'Binnen mijn familie lijkt iedereen een duidelijke bijzondere rol te hebben behalve ik.', 'Juist doordat ik buiten het patroon val, zie ik de scheuren in zowel het huis als het familieverhaal.', 'Tijdens mijn ceremonie verdwijnt mijn magische deur, maar later verschijnt mijn beeltenis op de nieuwe voordeur.'],
  ['Asha', 2023, 'Ik ontdek dat een ogenschijnlijk welwillende leider de verlangens van anderen gebruikt om macht te behouden.', 'Mijn wens trekt een zwijgende kosmische bondgenoot aan die gewone dieren tijdelijk een stem geeft.', 'Ik wil de opgeslagen wensen van Rosas teruggeven aan de mensen die ze ooit hebben afgestaan.'],
  ['Woody', 1995, 'Mijn identiteit hangt sterk samen met leiderschap en de aandacht van iemand die niet weet dat ik leef.', 'De komst van een modernere rivaal bedreigt mijn positie, maar dwingt mij uiteindelijk tot samenwerking.', 'Ik ben een cowboypop met een trekkoord en de woorden van mijn eigenaar onder mijn laars.'],
  ['Flik', 1998, 'Mijn uitvindingen en ideeën maken mij binnen mijn gemeenschap eerder lastig dan bewonderd.', 'Een fout tijdens een jaarlijks ritueel dwingt mij hulp te zoeken, maar ik rekruteer per ongeluk artiesten.', 'Ik bouw een mechanische vogel om sprinkhanen af te schrikken nadat ik circusbeestjes voor krijgers aanzie.'],
  ['Jessie', 1999, 'Een eerdere ervaring met verlaten worden beïnvloedt hoe ik reageer op verandering en nieuwe eigenaren.', 'Ik hoor bij een speelgoedcollectie waarvan een ander lid pas later zijn eigen fictieve verleden ontdekt.', 'Mijn claustrofobie en herinnering aan Emily komen naar boven wanneer ik opnieuw in een doos dreig te verdwijnen.'],
  ['Mike Wazowski', 2001, 'Mijn ambitie draait om een beroep waarin prestaties letterlijk worden gemeten en opgeslagen.', 'Mijn gebrek aan een traditioneel indrukwekkend uiterlijk compenseer ik met voorbereiding en organisatietalent.', 'Op mijn identiteitsbewijs staat maar één oog en in advertenties wordt mijn gezicht steeds door logo’s bedekt.'],
  ['Violet Parr', 2004, 'Ik probeer op te gaan in mijn omgeving terwijl mijn familie juist door uitzonderlijke eigenschappen wordt bepaald.', 'Mijn onzekerheid past symbolisch bij krachten waarmee ik mijzelf en anderen aan het zicht kan onttrekken.', 'Ik kan onzichtbaar worden én violette krachtvelden vormen, maar durf aanvankelijk nauwelijks met Tony te praten.'],
  ['Mater', 2006, 'Ik ben technisch beschadigd maar sociaal onbevangen, waardoor anderen mijn intelligentie vaak onderschatten.', 'Mijn vriendschap met een ambitieuze nieuwkomer ontstaat in een kleine gemeenschap waar ik als sleepdienst werk.', 'Ik rijd achteruit uitzonderlijk goed omdat ik naar eigen zeggen geen achteruitkijkspiegels nodig heb.'],
  ['Carl Fredricksen', 2009, 'Verdriet maakt mij koppig en beschermend tegenover een huis dat meer vertegenwoordigt dan alleen bezit.', 'Een onbedoelde jonge passagier verandert een lang uitgestelde reis in een nieuwe verantwoordelijkheid.', 'Duizenden ballonnen tillen mijn huis op naar Zuid-Amerika, waar ik het bij Paradise Falls wilde neerzetten.'],
  ['Miguel', 2017, 'Mijn persoonlijke roeping botst met een familieverbod dat voortkomt uit een onvolledig verhaal over het verleden.', 'Ik betreed een wereld van voorouders en moet vóór zonsopgang een zegen ontvangen zonder mijn droom op te geven.', 'Met een witte gitaar speel ik Remember Me voor mijn overgrootmoeder zodat een vergeten familielid blijft bestaan.'],
  ['Merida', 2012, 'Ik verzet mij tegen een traditie die mijn toekomst vastlegt zonder mijn toestemming.', 'Mijn poging om een ouder te veranderen veroorzaakt een letterlijke gedaanteverwisseling die vóór de tweede zonsopgang moet worden hersteld.', 'Ik schiet voor mijn eigen hand en splijt daarbij de pijl van een kandidaat precies in tweeën.'],
  ['Joe Gardner', 2020, 'Ik verwar lange tijd het bereiken van een professioneel doel met de betekenis van een volledig leven.', 'Een ongeluk brengt mij in een omgeving waar persoonlijkheden worden voorbereid voordat zij geboren worden.', 'Na mijn langverwachte jazzoptreden besef ik door alledaagse voorwerpen van 22 waarom leven niet hetzelfde is als een vonk vinden.'],
];

const WHOAMI_BROAD_HINTS = [
  'Mijn rol krijgt betekenis door de spanning tussen persoonlijke motieven en de gevolgen die mijn keuzes voor anderen hebben.',
  'In mijn verhaal blijken relaties en beslissingen belangrijker dan de eerste indruk die mijn uiterlijk, status of reputatie wekt.',
  'Ik word niet alleen bepaald door wie ik aan het begin lijk te zijn; een beslissende handeling onthult mijn werkelijke rol.',
];

const whoAmITasks = WHOAMI_CHARACTERS.map(([lead, , hint2, hint3], index) => {
  const peers = [1, 9, 17].map(offset => WHOAMI_CHARACTERS[(index + offset) % WHOAMI_CHARACTERS.length][0]);
  const answer = placeCorrectAnswer(lead, peers, index + 1);
  return {
    id: `whoami-${index + 41}`,
    cat: 'Wie ben ik?',
    type: 'whoami',
    title: 'Hint Quest',
    hint1: WHOAMI_BROAD_HINTS[index % WHOAMI_BROAD_HINTS.length],
    hint2,
    hint3,
    ...answer,
    points: 3,
    source: CONTENT_SOURCES.disneyHistory,
  };
});

const DRAW_PROMPTS = [
  'Mickey die een kasteel bouwt van speelkaarten', 'Minnie met een veel te grote strik', 'Donald in een kano zonder peddel',
  'Goofy die probeert te jongleren', 'Pluto die een verborgen schat ruikt', 'Stitch die een ruimteschip repareert',
  'Remy die een torenhoge taart bakt', 'Wall-E die een plantje beschermt', 'EVE die door een sterrenregen vliegt',
  'Mike Wazowski bij de oogarts', 'Sulley die sokken sorteert', 'Lightning McQueen in een Parijse file',
  'Mater als ridder', 'Woody op een op hol geslagen speelgoedtrein', 'Buzz Lightyear die de weg vraagt',
  'Jessie die een lasso om een maan werpt', 'Forky die zichzelf in een kunstwerk verandert', 'Nemo in een piepklein duikpak',
  'Dory met een boodschappenlijst', 'Carl met een huis vol ballonnen', 'Dug die achter tien eekhoorns aanrent',
  'Joy die een regenboog schildert', 'Sadness met een zonnige paraplu', 'Anger die een sneeuwpop maakt',
  'Miguel op een podium van goudsbloemen', 'Héctor die zijn gitaar stemt', 'Luca op een zelfgebouwde Vespa',
  'Mei Lee als rode panda in de metro', 'Joe Gardner die op een wolk piano speelt', 'Merida die een roos van haar pijl maakt',
  'Rapunzel met haar haar als hangbrug', 'Pascal die zich als schilderij camoufleert', 'Flynn Rider met tien koekenpannen',
  'Tiana die een kikker een menukaart geeft', 'Louis die trompet speelt onder water', 'Ariel die een vork als microfoon gebruikt',
  'Sebastian die een krabbenorkest dirigeert', 'Ursula die een contract van kilometers lang uitrolt', 'Belle op een vliegende stapel boeken',
  'Het Beest dat voorzichtig thee inschenkt', 'Lumière die een verjaardagstaart aansteekt', 'Aladdin op een tapijt in de spits',
  'De Geest die uit een piepkleine lamp komt', 'Jasmine die een sterrenkaart leest', 'Simba die zijn eigen schaduw achterna zit',
  'Timon en Pumbaa bij een chic diner', 'Rafiki die een selfie schildert', 'Mulan die Mushu leert schaatsen',
  'Mushu in een gigantisch harnas', 'Hercules die een veertje probeert op te tillen', 'Hades met haar van confetti',
  'Quasimodo die een miniatuurklok repareert', 'Esmeralda die met Djali danst', 'Pocahontas die bladeren als brief verstuurt',
  'Kuzco als lama op een troon', 'Yzma in een laboratorium vol paarse flesjes', 'Kronk die eekhoorntaal lesgeeft',
  'Peter Pan die zijn schaduw vastnaait', 'Kapitein Haak met een tikkende wekker', 'Tinker Bell in een lantaarn van sterrenstof',
];

const DILEMMAS = [
  ['Een nacht opgesloten zitten in Phantom Manor', 'Een nacht verdwalen in Pirates of the Caribbean'],
  ['Altijd achterstevoren in Big Thunder Mountain', 'Altijd in het donker door “it’s a small world”'],
  ['Met Donald een week op vakantie', 'Met Stitch een week je huis delen'],
  ['Alleen nog Disney-schurkenliedjes horen', 'Nooit meer een Disney-liedje mogen meezingen'],
  ['Een dag kunnen vliegen als Peter Pan', 'Een dag onder water ademen als Ariel'],
  ['Remy voor je laten koken', 'Tiana voor je laten koken'],
  ['Een eigen lichtzwaard krijgen', 'Een eigen vliegend tapijt krijgen'],
  ['In Arendelle wonen', 'In Motunui wonen'],
  ['Een gesprek met de Magische Spiegel', 'Drie wensen van de Geest'],
  ['Een uur met Edna Mode winkelen', 'Een uur met Cruella kleding ontwerpen'],
  ['Een race tegen Lightning McQueen', 'Een vliegwedstrijd tegen Buzz Lightyear'],
  ['Nooit meer in een wachtrij staan', 'Elke parade vanaf de beste plek zien'],
  ['Alle Disney-films uit je hoofd kennen', 'Elk Disney-lied perfect kunnen zingen'],
  ['Een dag als Cast Member in Fantasyland', 'Een nacht als Imagineer in Discoveryland'],
  ['Een huis als dat van Carl', 'Een kamer als die van Andy'],
  ['Een knuffel van Baymax', 'Een avontuur met WALL-E'],
  ['De emoties van Riley kunnen zien', 'De dromen van Miguel kunnen bezoeken'],
  ['Een eigen Pascal', 'Een eigen Abu'],
  ['Een diner in het kasteel', 'Een ontbijt in Avengers Campus'],
  ['De hele dag alleen achtbanen', 'De hele dag alleen shows'],
  ['Je favoriete attractie één keer zonder wachtrij', 'Vijf willekeurige attracties zonder wachtrij'],
  ['Een dag zonder telefoon in Disneyland Paris', 'Een dag zonder snacks in Disneyland Paris'],
  ['Met Hades onderhandelen', 'Met Ursula een contract tekenen'],
  ['Een speurtocht met Judy Hopps', 'Een mysterie oplossen met Basil'],
  ['Een kookwedstrijd tegen Kronk', 'Een zangwedstrijd tegen Tamatoa'],
  ['Een boogschietles van Merida', 'Een zwaardvechtles van Mulan'],
  ['Een sneeuwballengevecht met Elsa', 'Een watergevecht met Moana'],
  ['Een kamer delen met de zeven dwergen', 'Een tafel delen met Mad Hatter'],
  ['Een jaar lang elke dag Mickey-oren', 'Een jaar lang elke dag prinsessenkleding'],
  ['Alleen nog Disney-snacks eten', 'Alleen nog eten uit Ratatouille'],
  ['Je stem laten inspreken door de Geest', 'Je entree laten aankondigen door Lumière'],
  ['Een rit in de Nautilus', 'Een vlucht in de Millennium Falcon'],
  ['Een eigen droid bouwen', 'Een eigen Spider-Bot bouwen'],
  ['Een dag onzichtbaar zijn als Violet', 'Een dag supersnel zijn als Dash'],
  ['Een wandeling door Wonderland', 'Een wandeling door Halloween Town'],
  ['Een concert van Powerline', 'Een concert van 4*Town'],
  ['Met Olaf naar het strand', 'Met Baloe naar de sneeuw'],
  ['Een kaartspel tegen de Queen of Hearts', 'Schaken tegen Yzma'],
  ['Een ritje met Cruella', 'Een vliegles met Orville'],
  ['Een feest in Casa Madrigal', 'Een feest op Pride Rock'],
  ['Je verjaardag vieren in Main Street', 'Oud en nieuw vieren bij het kasteel'],
  ['Een eigen kamer in Tower of Terror', 'Een eigen hut op de Black Pearl'],
  ['Alle Hidden Mickeys kunnen zien', 'Elke Audio-Animatronic kunnen verstaan'],
  ['Een dag als klein speelgoed', 'Een dag zo klein als Remy'],
  ['Een reis door de tijd met Lewis', 'Een reis door de ruimte met Jim Hawkins'],
  ['Een vriend als Baymax', 'Een mentor als Rafiki'],
  ['Een middag in de bibliotheek van Belle', 'Een middag in het laboratorium van Yzma'],
  ['Een boze Donald kalmeren', 'Een enthousiaste Olaf stil krijgen'],
  ['Een parade mogen ontwerpen', 'Een Disney-attractie mogen ontwerpen'],
  ['Nooit meer een Disneyfilm opnieuw kijken', 'Nooit meer een nieuwe Disneyfilm zien'],
  ['Een perfect fotografisch geheugen', 'Elke taal van “it’s a small world” spreken'],
  ['Een uur vast in Space Mountain', 'Een uur vast in een bootje van Pirates'],
  ['Een dag met Chip en Dale', 'Een dag met Pain en Panic'],
  ['Je eigen Disney-schurk kiezen', 'Je eigen Disney-sidekick kiezen'],
  ['Een nacht onder de sterren in Cars Land', 'Een nacht bij de Tree of Life'],
  ['Alleen attracties uit 1992 beleven', 'Alleen de nieuwste attracties beleven'],
  ['Een eigen Main Street-winkel', 'Een eigen kraampje op een Disneyfestival'],
  ['Met Jack Sparrow een schat zoeken', 'Met Indiana Jones een tempel ontdekken'],
  ['Een rol in een Pixarfilm', 'Een rol in een klassieke Disneyfilm'],
  ['De openingsceremonie mogen doen', 'De slotshow vanaf het podium bekijken'],
];

const GROUP_TASKS = [
  'Bedenk samen binnen één minuut een nieuwe naam voor een Disney-achtbaan.',
  'Noem om de beurt een Disney-dier; wie vijf seconden stilvalt, valt af.',
  'Maak samen een top drie van de beste Disney-schurken en verdedig de nummer één.',
  'Bedenk een menu van drie gangen rond één Disneyfilm.',
  'Speel zonder woorden een scène uit een Disneyfilm; de anderen raden.',
  'Maak samen een reclameslogan voor Phantom Manor.',
  'Noem binnen zestig seconden tien Disney-personages met een hoed.',
  'Bedenk een nieuwe emotie die in Inside Out zou passen en geef haar een kleur.',
  'Ontwerp samen een hotelkamer rond één Disney-sidekick.',
  'Maak een verhaal van precies zes zinnen waarin Mickey, Ursula en Baymax voorkomen.',
  'Noem samen zoveel mogelijk Disneyfilms met een dier in de hoofdrol.',
  'Kies één Disney-attractie die naar een andere parkzone moet en leg uit waarom.',
  'Maak gezamenlijk het geluid van een Disney-achtbaan vanaf vertrek tot finish.',
  'Bedenk een nieuwe snack voor Main Street en geef hem een Disney-naam.',
  'Zet vijf Disney-schurken van minst naar meest gevaarlijk.',
  'Noem om de beurt een Disney-lied; een herhaling betekent afvallen.',
  'Maak met jullie handen samen de vorm van een Disneykasteel.',
  'Bedenk een nieuwe wens die de Geest nog nooit heeft gehoord.',
  'Kies samen de perfecte Disney-sidekick voor een lange autorit.',
  'Verzin een alternatieve afloop voor The Little Mermaid in maximaal drie zinnen.',
  'Noem binnen één minuut twaalf attracties van Disneyland Paris.',
  'Bedenk een nieuwe naam voor de Black Pearl en een bijpassende vlag.',
  'Maak samen een top drie van Disneyfilms die een attractie verdienen.',
  'Kies welk Disney-personage jullie reisleider zou moeten zijn.',
  'Speel een gesprek tussen Hades en Olaf zonder hun namen te noemen.',
  'Bedenk een geheime kamer voor Casa Madrigal en de kracht die erbij hoort.',
  'Noem zoveel mogelijk Disney-personages die kunnen vliegen.',
  'Maak samen een weerbericht voor Arendelle.',
  'Bedenk een sportwedstrijd tussen Pixar-personages.',
  'Kies drie voorwerpen die je meeneemt op een avontuur met Indiana Jones.',
  'Maak een groepsfoto alsof jullie Audio-Animatronics in een attractie zijn.',
  'Noem binnen één minuut acht Disneyfilms die zich grotendeels buiten de Verenigde Staten afspelen.',
  'Ontwerp samen een paradewagen voor Stitch.',
  'Bedenk een nieuwe bijnaam voor Lightning McQueen.',
  'Kies één Disneyfilm die als musical beter zou worden en verdeel de rollen.',
  'Maak een korte yell voor Team Mickey en voer hem samen uit.',
  'Noem om de beurt een Disney-moeder of -vader; stop niet langer dan vijf seconden.',
  'Bedenk een nieuw bordspel dat in Toy Story gespeeld kan worden.',
  'Geef drie veiligheidsregels voor een vlucht op een vliegend tapijt.',
  'Kies samen het beste Disney-personage om een escape room mee te doen.',
  'Maak een alfabetketting van Disney-namen; iedere volgende naam begint met de laatste letter.',
  'Bedenk een nieuw drankje voor Gaston’s Tavern zonder alcohol.',
  'Noem vijf Disney-voorwerpen die in een museum thuishoren.',
  'Maak samen een rap van vier regels over jullie favoriete attractie.',
  'Ontwerp een medaille voor iemand die alle Disneyparken bezoekt.',
  'Kies welke drie personages jullie in een Disney-superteam zetten.',
  'Bedenk een attractie waarin geen voertuig nodig is.',
  'Noem samen tien Disney-personages met een niet-menselijke beste vriend.',
  'Maak een nieuwe naam en slogan voor een restaurant van Remy.',
  'Kies een Disneyfilm en vat hem samen in precies vijf woorden.',
  'Bedenk een souvenir dat alleen in Discoveryland verkocht kan worden.',
  'Verdeel samen de rollen voor een missie op de Millennium Falcon.',
  'Noem binnen één minuut zoveel mogelijk kleuren die in Disney-personagenamen voorkomen.',
  'Maak een levende standbeeldpose van een beroemde Disney-scène.',
  'Bedenk een nieuw couplet voor “Hakuna Matata” zonder de originele tekst te gebruiken.',
  'Kies de vier Disney-personages die het beste een restaurant kunnen runnen.',
  'Ontwerp samen een nieuwe deur voor Monsters, Inc. en vertel waar die uitkomt.',
  'Noem vijf Disneyfilms waarin een reis centraal staat.',
  'Bedenk een nieuwe feestdag voor Disneyland Paris en de bijbehorende traditie.',
  'Maak samen een slotzin voor een nooit gemaakte Disneyfilm.',
];

const EMOJI_FILMS = [
  ['🐘 🎪 🪶 🚂', 'Dumbo', 'Dombo'], ['🦊 🐶 🌲 🤝', 'The Fox and the Hound', 'Frank en Frey'],
  ['🐭 🔍 🕰️ 🦇', 'The Great Mouse Detective', 'De Speurneuzen'], ['🐈 🗽 🐶 🎵', 'Oliver & Company', 'Oliver & Co.'],
  ['🐻 🦅 🌌 🐟', 'Brother Bear', 'Brother Bear'], ['🐔 🌰 ☁️ 🛸', 'Chicken Little', 'Chicken Little'],
  ['👦 🤖 🕰️ 👨‍👩‍👦', 'Meet the Robinsons', 'Meet the Robinsons'], ['🐕 ⚡ 📺 🐹', 'Bolt', 'Bolt'],
  ['🎮 🔨 🍬 👑', 'Wreck-It Ralph', 'Wreck-It Ralph'], ['🐰 🦊 🚓 🦥', 'Zootopia', 'Zootropolis'],
  ['🐉 ⚔️ 💎 🌧️', 'Raya and the Last Dragon', 'Raya en de Laatste Draak'], ['🌟 👑 🐐 🪄', 'Wish', 'Wish'],
  ['🐜 🍃 🦗 🎪', "A Bug's Life", 'Een Luizenleven'], ['🤠 🚀 🐴 🧸', 'Toy Story 2', 'Toy Story 2'],
  ['🏫 👁️ 💙 🏆', 'Monsters University', 'Monsters University'], ['🦕 👦 🌽 ⛰️', 'The Good Dinosaur', 'The Good Dinosaur'],
  ['🐟 🐙 🐋 🐚', 'Finding Dory', 'Finding Dory'], ['🦸‍♀️ 🍼 🦝 🏙️', 'Incredibles 2', 'Incredibles 2'],
  ['🧸 🎡 🗑️ 🥄', 'Toy Story 4', 'Toy Story 4'], ['🧙‍♂️ 🚐 💎 👖', 'Onward', 'Onward'],
  ['🎹 🌌 🐈 🎷', 'Soul', 'Soul'], ['🌊 🐟 🛵 🇮🇹', 'Luca', 'Luca'],
  ['🐼 🎤 👭 🌙', 'Turning Red', 'Turning Red'], ['🚀 🪐 🤖 🐈', 'Lightyear', 'Lightyear'],
  ['🔥 💧 🌆 🌸', 'Elemental', 'Elemental'], ['😰 😊 🧠 🏒', 'Inside Out 2', 'Binnenstebuiten 2'],
  ['🐭 🧵 👗 🕛', 'Cinderella', 'Assepoester'], ['🗡️ 🏰 🐿️ 🧙‍♂️', 'The Sword in the Stone', 'Merlijn de Tovenaar'],
  ['🐭 💎 🐊 🛟', 'The Rescuers', 'De Reddertjes'], ['🦘 🦅 🐭 ⛰️', 'The Rescuers Down Under', 'De Reddertjes in Kangoeroeland'],
  ['🔥 🔔 🏰 🎭', 'The Hunchback of Notre Dame', 'De Klokkenluider van de Notre Dame'], ['🦕 🥚 ☄️ 🌿', 'Dinosaur', 'Dinosaur'],
  ['🌊 💎 🛩️ 🏛️', 'Atlantis: The Lost Empire', 'Atlantis: De Verzonken Stad'], ['🚀 🗺️ 🏴‍☠️ 🌌', 'Treasure Planet', 'Piratenplaneet'],
  ['🐄 🏜️ 💰 🐎', 'Home on the Range', 'Paniek op de Prairie'], ['🏎️ 🕵️‍♂️ 🌍 🔧', 'Cars 2', 'Cars 2'],
  ['🏹 🐻 👑 🔥', 'Brave', 'Brave'], ['🧝‍♂️ 🐉 🗡️ 🚌', 'Onward', 'Onward'],
  ['🎸 💀 🌼 🌉', 'Coco', 'Coco'], ['👸 🐉 💧 ⚔️', 'Raya and the Last Dragon', 'Raya en de Laatste Draak'],
  ['🦁 🐒 🌅 👑', 'The Lion King', 'De Leeuwenkoning'], ['🌹 🕯️ 🫖 🏰', 'Beauty and the Beast', 'Belle en het Beest'],
  ['🧞‍♂️ 🪔 🐒 🕌', 'Aladdin', 'Aladdin'], ['🦍 🌿 🚢 📖', 'Tarzan', 'Tarzan'],
  ['🐸 🎺 🍲 🌙', 'The Princess and the Frog', 'De Prinses en de Kikker'], ['🗼 🦎 ✨ 🍳', 'Tangled', 'Rapunzel'],
  ['❄️ 🦌 ⛄ 👭', 'Frozen II', 'Frozen II'], ['🌊 ⛵ 🐚 🪝', 'Moana 2', 'Vaiana 2'],
  ['🛸 👽 🌺 🐶', 'Lilo & Stitch', 'Lilo & Stitch'], ['🐀 🍲 🗼 ⭐', 'Ratatouille', 'Ratatouille'],
  ['🤖 🪴 ❤️ 🌍', 'WALL-E', 'WALL-E'], ['🎈 🏠 🐕 🦜', 'Up', 'Up'],
  ['🚗 ⚡ 🏁 🛞', 'Cars', 'Cars'], ['👻 🚪 🧦 👁️', 'Monsters, Inc.', 'Monsters en Co.'],
  ['🐠 🌊 🔍 🐢', 'Finding Nemo', 'Finding Nemo'], ['🦸‍♂️ 👨‍👩‍👧‍👦 🏝️ 🤖', 'The Incredibles', 'The Incredibles'],
  ['🧠 😊 😡 😢', 'Inside Out', 'Binnenstebuiten'], ['🏠 🕯️ 🦋 🌺', 'Encanto', 'Encanto'],
  ['🧊 👸 ⛄ 🏰', 'Frozen', 'Frozen'], ['🐉 🏮 ⚔️ 🌸', 'Mulan', 'Mulan'],
  ['🎼 🐋 🌆 🦋', 'Fantasia 2000', 'Fantasia 2000'], ['🐻 🍯 🐯 📖', 'Winnie the Pooh', 'Winnie de Poeh'],
  ['✈️ 🌎 🦜 🎨', 'Saludos Amigos', 'Saludos Amigos'], ['🦆 🦜 🐓 🎺', 'The Three Caballeros', 'De Drie Caballeros'],
  ['🎵 🌙 🐋 🏞️', 'Make Mine Music', 'Make Mine Music'], ['🐻 🫘 🎪 🏰', 'Fun and Fancy Free', 'Vrij en Vrolijk'],
  ['🎶 🌳 🐝 🚂', 'Melody Time', 'Melody Time'], ['🐸 🐎 🎃 📚', 'The Adventures of Ichabod and Mr. Toad', 'De Avonturen van Ichabod en Meneer Pad'],
  ['👦 🐻 🐍 🌴', 'The Jungle Book 2', 'Jungle Boek 2'], ['🧜‍♀️ 👶 🐙 ❄️', 'The Little Mermaid II: Return to the Sea', 'De Kleine Zeemeermin II'],
  ['🦁 👑 🐾 🌴', 'The Lion King II: Simba’s Pride', 'De Leeuwenkoning II'], ['🕌 🧞‍♂️ 👑 🗡️', 'Aladdin and the King of Thieves', 'Aladdin en de Dievenkoning'],
  ['☂️ 🎠 🐧 🎵', 'Mary Poppins', 'Mary Poppins'], ['🛏️ 🧙‍♀️ ⚽ 🏝️', 'Bedknobs and Broomsticks', 'Heksen & Bezemstelen'],
  ['🐉 🏚️ 🌊 🎨', "Pete's Dragon", 'Peter en de Draak'], ['💻 🏍️ 💿 ⚡', 'TRON', 'TRON'],
  ['🐰 🎬 🔍 🚕', 'Who Framed Roger Rabbit', 'Who Framed Roger Rabbit'], ['🎃 🎄 💀 🎁', 'The Nightmare Before Christmas', 'The Nightmare Before Christmas'],
  ['🍑 🐛 🕷️ 🌊', 'James and the Giant Peach', 'James en de Reuzenperzik'], ['👸 🗽 🐿️ 💍', 'Enchanted', 'Enchanted'],
  ['🐕 🛷 ❄️ 🐺', 'Togo', 'Togo'], ['🏴‍☠️ 🧚‍♀️ 🐊 🗺️', 'Return to Never Land', 'Terug naar Nooitgedachtland'],
  ['👽 🏫 🐶 🛸', 'Lilo & Stitch 2: Stitch Has a Glitch', 'Lilo & Stitch 2'], ['🧙‍♀️ 🎃 👭 📖', 'Hocus Pocus', 'Hocus Pocus'],
];

const drawTasks = DRAW_PROMPTS.map((text, index) => ({ id: `draw-${index + 41}`, cat: 'Pictionary', type: 'draw', title: 'Tekenopdracht', text, points: 2 }));
const dilemmaTasks = DILEMMAS.map(([optionA, optionB], index) => ({ id: `dilemma-${index + 41}`, cat: 'Dilemma', type: 'dilemma', title: 'Disney Dilemma', text: 'Welke keuze maak jij?', optionA, optionB, points: 1 }));
const groupTasks = GROUP_TASKS.map((text, index) => ({ id: `group-${index + 21}`, cat: 'Samen', type: 'group', title: 'Magisch Teamwerk', text, seconds: 60, points: 2 }));
const EXISTING_EMOJI_TITLES = new Set([
  'Dumbo', 'Cinderella', 'The Hunchback of Notre Dame', 'The Lion King', 'Beauty and the Beast',
  'Aladdin', 'Tarzan', 'The Princess and the Frog', 'Tangled', 'Lilo & Stitch', 'Ratatouille',
  'WALL-E', 'Up', 'Cars', 'Monsters, Inc.', 'Finding Nemo', 'The Incredibles', 'Inside Out',
  'Encanto', 'Frozen', 'Mulan', 'Coco',
]);
const uniqueEmojiFilms = EMOJI_FILMS.filter((entry, index, all) => (
  !EXISTING_EMOJI_TITLES.has(entry[1]) && all.findIndex(candidate => candidate[1] === entry[1]) === index
)).slice(0, 60);
const emojiTasks = uniqueEmojiFilms.map(([text, movie_en, movie_nl], index) => ({
  id: `emoji-${index + 41}`,
  cat: 'Emoji Quiz',
  type: 'emoji',
  title: 'Emoji Filmcode',
  text,
  movie_nl,
  movie_en,
  movie_aliases: [],
  points: 2,
  active: true,
  source: CONTENT_SOURCES.disneyMovies,
}));

export const CONTENT_EXPANSION_TASKS = [
  ...quizTasks,
  ...estimateTasks,
  ...whoAmITasks,
  ...drawTasks,
  ...dilemmaTasks,
  ...groupTasks,
  ...emojiTasks,
];
